// Code generated by ent, DO NOT EDIT.

package scheduleentry

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the scheduleentry type in the database.
	Label = "schedule_entry"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldShiftDate holds the string denoting the shift_date field in the database.
	FieldShiftDate = "shift_date"
	// FieldShiftName holds the string denoting the shift_name field in the database.
	FieldShiftName = "shift_name"
	// FieldStartTime holds the string denoting the start_time field in the database.
	FieldStartTime = "start_time"
	// FieldEndTime holds the string denoting the end_time field in the database.
	FieldEndTime = "end_time"
	// FieldHours holds the string denoting the hours field in the database.
	FieldHours = "hours"
	// FieldClassCode holds the string denoting the class_code field in the database.
	FieldClassCode = "class_code"
	// FieldRawJSON holds the string denoting the raw_json field in the database.
	FieldRawJSON = "raw_json"
	// FieldSyncedAt holds the string denoting the synced_at field in the database.
	FieldSyncedAt = "synced_at"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// EdgeUser holds the string denoting the user edge name in mutations.
	EdgeUser = "user"
	// Table holds the table name of the scheduleentry in the database.
	Table = "schedule_entries"
	// UserTable is the table that holds the user relation/edge.
	UserTable = "schedule_entries"
	// UserInverseTable is the table name for the User entity.
	// It exists in this package in order to avoid circular dependency with the "user" package.
	UserInverseTable = "users"
	// UserColumn is the table column denoting the user relation/edge.
	UserColumn = "user_schedule_entries"
)

// Columns holds all SQL columns for scheduleentry fields.
var Columns = []string{
	FieldID,
	FieldShiftDate,
	FieldShiftName,
	FieldStartTime,
	FieldEndTime,
	FieldHours,
	FieldClassCode,
	FieldRawJSON,
	FieldSyncedAt,
	FieldCreatedAt,
	FieldUpdatedAt,
}

// ForeignKeys holds the SQL foreign-keys that are owned by the "schedule_entries"
// table and are not defined as standalone fields in the schema.
var ForeignKeys = []string{
	"user_schedule_entries",
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	for i := range ForeignKeys {
		if column == ForeignKeys[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultSyncedAt holds the default value on creation for the "synced_at" field.
	DefaultSyncedAt func() time.Time
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
)

// OrderOption defines the ordering options for the ScheduleEntry queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByShiftDate orders the results by the shift_date field.
func ByShiftDate(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldShiftDate, opts...).ToFunc()
}

// ByShiftName orders the results by the shift_name field.
func ByShiftName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldShiftName, opts...).ToFunc()
}

// ByStartTime orders the results by the start_time field.
func ByStartTime(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStartTime, opts...).ToFunc()
}

// ByEndTime orders the results by the end_time field.
func ByEndTime(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEndTime, opts...).ToFunc()
}

// ByHours orders the results by the hours field.
func ByHours(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldHours, opts...).ToFunc()
}

// ByClassCode orders the results by the class_code field.
func ByClassCode(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldClassCode, opts...).ToFunc()
}

// ByRawJSON orders the results by the raw_json field.
func ByRawJSON(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRawJSON, opts...).ToFunc()
}

// BySyncedAt orders the results by the synced_at field.
func BySyncedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSyncedAt, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByUserField orders the results by user field.
func ByUserField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newUserStep(), sql.OrderByField(field, opts...))
	}
}
func newUserStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(UserInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, UserTable, UserColumn),
	)
}
