// Code generated by ent, DO NOT EDIT.

package scheduleentry

import (
	"gaia-calendar/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.ScheduleEntry {
	return predicate.ScheduleEntry(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.ScheduleEntry {
	return predicate.ScheduleEntry(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.ScheduleEntry {
	return predicate.ScheduleEntry(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.ScheduleEntry {
	return predicate.ScheduleEntry(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.ScheduleEntry {
	return predicate.ScheduleEntry(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.ScheduleEntry {
	return predicate.ScheduleEntry(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.ScheduleEntry {
	return predicate.ScheduleEntry(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.ScheduleEntry {
	return predicate.ScheduleEntry(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.ScheduleEntry {
	return predicate.ScheduleEntry(sql.FieldLTE(FieldID, id))
}

// ShiftDate applies equality check predicate on the "shift_date" field. It's identical to ShiftDateEQ.
func ShiftDate(v time.Time) predicate.ScheduleEntry {
	return predicate.ScheduleEntry(sql.FieldEQ(FieldShiftDate, v))
}

// ShiftName applies equality check predicate on the "shift_name" field. It's identical to ShiftNameEQ.
func ShiftName(v string) predicate.ScheduleEntry {
	return predicate.ScheduleEntry(sql.FieldEQ(FieldShiftName, v))
}

// StartTime applies equality check predicate on the "start_time" field. It's identical to StartTimeEQ.
func StartTime(v time.Time) predicate.ScheduleEntry {
	return predicate.ScheduleEntry(sql.FieldEQ(FieldStartTime, v))
}

// EndTime applies equality check predicate on the "end_time" field. It's identical to EndTimeEQ.
func EndTime(v time.Time) predicate.ScheduleEntry {
	return predicate.ScheduleEntry(sql.FieldEQ(FieldEndTime, v))
}

// Hours applies equality check predicate on the "hours" field. It's identical to HoursEQ.
func Hours(v float64) predicate.ScheduleEntry {
	return predicate.ScheduleEntry(sql.FieldEQ(FieldHours, v))
}

// ClassCode applies equality check predicate on the "class_code" field. It's identical to ClassCodeEQ.
func ClassCode(v string) predicate.ScheduleEntry {
	return predicate.ScheduleEntry(sql.FieldEQ(FieldClassCode, v))
}

// RawJSON applies equality check predicate on the "raw_json" field. It's identical to RawJSONEQ.
func RawJSON(v string) predicate.ScheduleEntry {
	return predicate.ScheduleEntry(sql.FieldEQ(FieldRawJSON, v))
}

// SyncedAt applies equality check predicate on the "synced_at" field. It's identical to SyncedAtEQ.
func SyncedAt(v time.Time) predicate.ScheduleEntry {
	return predicate.ScheduleEntry(sql.FieldEQ(FieldSyncedAt, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.ScheduleEntry {
	return predicate.ScheduleEntry(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.ScheduleEntry {
	return predicate.ScheduleEntry(sql.FieldEQ(FieldUpdatedAt, v))
}

// ShiftDateEQ applies the EQ predicate on the "shift_date" field.
func ShiftDateEQ(v time.Time) predicate.ScheduleEntry {
	return predicate.ScheduleEntry(sql.FieldEQ(FieldShiftDate, v))
}

// ShiftDateNEQ applies the NEQ predicate on the "shift_date" field.
func ShiftDateNEQ(v time.Time) predicate.ScheduleEntry {
	return predicate.ScheduleEntry(sql.FieldNEQ(FieldShiftDate, v))
}

// ShiftDateIn applies the In predicate on the "shift_date" field.
func ShiftDateIn(vs ...time.Time) predicate.ScheduleEntry {
	return predicate.ScheduleEntry(sql.FieldIn(FieldShiftDate, vs...))
}

// ShiftDateNotIn applies the NotIn predicate on the "shift_date" field.
func ShiftDateNotIn(vs ...time.Time) predicate.ScheduleEntry {
	return predicate.ScheduleEntry(sql.FieldNotIn(FieldShiftDate, vs...))
}

// ShiftDateGT applies the GT predicate on the "shift_date" field.
func ShiftDateGT(v time.Time) predicate.ScheduleEntry {
	return predicate.ScheduleEntry(sql.FieldGT(FieldShiftDate, v))
}

// ShiftDateGTE applies the GTE predicate on the "shift_date" field.
func ShiftDateGTE(v time.Time) predicate.ScheduleEntry {
	return predicate.ScheduleEntry(sql.FieldGTE(FieldShiftDate, v))
}

// ShiftDateLT applies the LT predicate on the "shift_date" field.
func ShiftDateLT(v time.Time) predicate.ScheduleEntry {
	return predicate.ScheduleEntry(sql.FieldLT(FieldShiftDate, v))
}

// ShiftDateLTE applies the LTE predicate on the "shift_date" field.
func ShiftDateLTE(v time.Time) predicate.ScheduleEntry {
	return predicate.ScheduleEntry(sql.FieldLTE(FieldShiftDate, v))
}

// ShiftNameEQ applies the EQ predicate on the "shift_name" field.
func ShiftNameEQ(v string) predicate.ScheduleEntry {
	return predicate.ScheduleEntry(sql.FieldEQ(FieldShiftName, v))
}

// ShiftNameNEQ applies the NEQ predicate on the "shift_name" field.
func ShiftNameNEQ(v string) predicate.ScheduleEntry {
	return predicate.ScheduleEntry(sql.FieldNEQ(FieldShiftName, v))
}

// ShiftNameIn applies the In predicate on the "shift_name" field.
func ShiftNameIn(vs ...string) predicate.ScheduleEntry {
	return predicate.ScheduleEntry(sql.FieldIn(FieldShiftName, vs...))
}

// ShiftNameNotIn applies the NotIn predicate on the "shift_name" field.
func ShiftNameNotIn(vs ...string) predicate.ScheduleEntry {
	return predicate.ScheduleEntry(sql.FieldNotIn(FieldShiftName, vs...))
}

// ShiftNameGT applies the GT predicate on the "shift_name" field.
func ShiftNameGT(v string) predicate.ScheduleEntry {
	return predicate.ScheduleEntry(sql.FieldGT(FieldShiftName, v))
}

// ShiftNameGTE applies the GTE predicate on the "shift_name" field.
func ShiftNameGTE(v string) predicate.ScheduleEntry {
	return predicate.ScheduleEntry(sql.FieldGTE(FieldShiftName, v))
}

// ShiftNameLT applies the LT predicate on the "shift_name" field.
func ShiftNameLT(v string) predicate.ScheduleEntry {
	return predicate.ScheduleEntry(sql.FieldLT(FieldShiftName, v))
}

// ShiftNameLTE applies the LTE predicate on the "shift_name" field.
func ShiftNameLTE(v string) predicate.ScheduleEntry {
	return predicate.ScheduleEntry(sql.FieldLTE(FieldShiftName, v))
}

// ShiftNameContains applies the Contains predicate on the "shift_name" field.
func ShiftNameContains(v string) predicate.ScheduleEntry {
	return predicate.ScheduleEntry(sql.FieldContains(FieldShiftName, v))
}

// ShiftNameHasPrefix applies the HasPrefix predicate on the "shift_name" field.
func ShiftNameHasPrefix(v string) predicate.ScheduleEntry {
	return predicate.ScheduleEntry(sql.FieldHasPrefix(FieldShiftName, v))
}

// ShiftNameHasSuffix applies the HasSuffix predicate on the "shift_name" field.
func ShiftNameHasSuffix(v string) predicate.ScheduleEntry {
	return predicate.ScheduleEntry(sql.FieldHasSuffix(FieldShiftName, v))
}

// ShiftNameIsNil applies the IsNil predicate on the "shift_name" field.
func ShiftNameIsNil() predicate.ScheduleEntry {
	return predicate.ScheduleEntry(sql.FieldIsNull(FieldShiftName))
}

// ShiftNameNotNil applies the NotNil predicate on the "shift_name" field.
func ShiftNameNotNil() predicate.ScheduleEntry {
	return predicate.ScheduleEntry(sql.FieldNotNull(FieldShiftName))
}

// ShiftNameEqualFold applies the EqualFold predicate on the "shift_name" field.
func ShiftNameEqualFold(v string) predicate.ScheduleEntry {
	return predicate.ScheduleEntry(sql.FieldEqualFold(FieldShiftName, v))
}

// ShiftNameContainsFold applies the ContainsFold predicate on the "shift_name" field.
func ShiftNameContainsFold(v string) predicate.ScheduleEntry {
	return predicate.ScheduleEntry(sql.FieldContainsFold(FieldShiftName, v))
}

// StartTimeEQ applies the EQ predicate on the "start_time" field.
func StartTimeEQ(v time.Time) predicate.ScheduleEntry {
	return predicate.ScheduleEntry(sql.FieldEQ(FieldStartTime, v))
}

// StartTimeNEQ applies the NEQ predicate on the "start_time" field.
func StartTimeNEQ(v time.Time) predicate.ScheduleEntry {
	return predicate.ScheduleEntry(sql.FieldNEQ(FieldStartTime, v))
}

// StartTimeIn applies the In predicate on the "start_time" field.
func StartTimeIn(vs ...time.Time) predicate.ScheduleEntry {
	return predicate.ScheduleEntry(sql.FieldIn(FieldStartTime, vs...))
}

// StartTimeNotIn applies the NotIn predicate on the "start_time" field.
func StartTimeNotIn(vs ...time.Time) predicate.ScheduleEntry {
	return predicate.ScheduleEntry(sql.FieldNotIn(FieldStartTime, vs...))
}

// StartTimeGT applies the GT predicate on the "start_time" field.
func StartTimeGT(v time.Time) predicate.ScheduleEntry {
	return predicate.ScheduleEntry(sql.FieldGT(FieldStartTime, v))
}

// StartTimeGTE applies the GTE predicate on the "start_time" field.
func StartTimeGTE(v time.Time) predicate.ScheduleEntry {
	return predicate.ScheduleEntry(sql.FieldGTE(FieldStartTime, v))
}

// StartTimeLT applies the LT predicate on the "start_time" field.
func StartTimeLT(v time.Time) predicate.ScheduleEntry {
	return predicate.ScheduleEntry(sql.FieldLT(FieldStartTime, v))
}

// StartTimeLTE applies the LTE predicate on the "start_time" field.
func StartTimeLTE(v time.Time) predicate.ScheduleEntry {
	return predicate.ScheduleEntry(sql.FieldLTE(FieldStartTime, v))
}

// StartTimeIsNil applies the IsNil predicate on the "start_time" field.
func StartTimeIsNil() predicate.ScheduleEntry {
	return predicate.ScheduleEntry(sql.FieldIsNull(FieldStartTime))
}

// StartTimeNotNil applies the NotNil predicate on the "start_time" field.
func StartTimeNotNil() predicate.ScheduleEntry {
	return predicate.ScheduleEntry(sql.FieldNotNull(FieldStartTime))
}

// EndTimeEQ applies the EQ predicate on the "end_time" field.
func EndTimeEQ(v time.Time) predicate.ScheduleEntry {
	return predicate.ScheduleEntry(sql.FieldEQ(FieldEndTime, v))
}

// EndTimeNEQ applies the NEQ predicate on the "end_time" field.
func EndTimeNEQ(v time.Time) predicate.ScheduleEntry {
	return predicate.ScheduleEntry(sql.FieldNEQ(FieldEndTime, v))
}

// EndTimeIn applies the In predicate on the "end_time" field.
func EndTimeIn(vs ...time.Time) predicate.ScheduleEntry {
	return predicate.ScheduleEntry(sql.FieldIn(FieldEndTime, vs...))
}

// EndTimeNotIn applies the NotIn predicate on the "end_time" field.
func EndTimeNotIn(vs ...time.Time) predicate.ScheduleEntry {
	return predicate.ScheduleEntry(sql.FieldNotIn(FieldEndTime, vs...))
}

// EndTimeGT applies the GT predicate on the "end_time" field.
func EndTimeGT(v time.Time) predicate.ScheduleEntry {
	return predicate.ScheduleEntry(sql.FieldGT(FieldEndTime, v))
}

// EndTimeGTE applies the GTE predicate on the "end_time" field.
func EndTimeGTE(v time.Time) predicate.ScheduleEntry {
	return predicate.ScheduleEntry(sql.FieldGTE(FieldEndTime, v))
}

// EndTimeLT applies the LT predicate on the "end_time" field.
func EndTimeLT(v time.Time) predicate.ScheduleEntry {
	return predicate.ScheduleEntry(sql.FieldLT(FieldEndTime, v))
}

// EndTimeLTE applies the LTE predicate on the "end_time" field.
func EndTimeLTE(v time.Time) predicate.ScheduleEntry {
	return predicate.ScheduleEntry(sql.FieldLTE(FieldEndTime, v))
}

// EndTimeIsNil applies the IsNil predicate on the "end_time" field.
func EndTimeIsNil() predicate.ScheduleEntry {
	return predicate.ScheduleEntry(sql.FieldIsNull(FieldEndTime))
}

// EndTimeNotNil applies the NotNil predicate on the "end_time" field.
func EndTimeNotNil() predicate.ScheduleEntry {
	return predicate.ScheduleEntry(sql.FieldNotNull(FieldEndTime))
}

// HoursEQ applies the EQ predicate on the "hours" field.
func HoursEQ(v float64) predicate.ScheduleEntry {
	return predicate.ScheduleEntry(sql.FieldEQ(FieldHours, v))
}

// HoursNEQ applies the NEQ predicate on the "hours" field.
func HoursNEQ(v float64) predicate.ScheduleEntry {
	return predicate.ScheduleEntry(sql.FieldNEQ(FieldHours, v))
}

// HoursIn applies the In predicate on the "hours" field.
func HoursIn(vs ...float64) predicate.ScheduleEntry {
	return predicate.ScheduleEntry(sql.FieldIn(FieldHours, vs...))
}

// HoursNotIn applies the NotIn predicate on the "hours" field.
func HoursNotIn(vs ...float64) predicate.ScheduleEntry {
	return predicate.ScheduleEntry(sql.FieldNotIn(FieldHours, vs...))
}

// HoursGT applies the GT predicate on the "hours" field.
func HoursGT(v float64) predicate.ScheduleEntry {
	return predicate.ScheduleEntry(sql.FieldGT(FieldHours, v))
}

// HoursGTE applies the GTE predicate on the "hours" field.
func HoursGTE(v float64) predicate.ScheduleEntry {
	return predicate.ScheduleEntry(sql.FieldGTE(FieldHours, v))
}

// HoursLT applies the LT predicate on the "hours" field.
func HoursLT(v float64) predicate.ScheduleEntry {
	return predicate.ScheduleEntry(sql.FieldLT(FieldHours, v))
}

// HoursLTE applies the LTE predicate on the "hours" field.
func HoursLTE(v float64) predicate.ScheduleEntry {
	return predicate.ScheduleEntry(sql.FieldLTE(FieldHours, v))
}

// HoursIsNil applies the IsNil predicate on the "hours" field.
func HoursIsNil() predicate.ScheduleEntry {
	return predicate.ScheduleEntry(sql.FieldIsNull(FieldHours))
}

// HoursNotNil applies the NotNil predicate on the "hours" field.
func HoursNotNil() predicate.ScheduleEntry {
	return predicate.ScheduleEntry(sql.FieldNotNull(FieldHours))
}

// ClassCodeEQ applies the EQ predicate on the "class_code" field.
func ClassCodeEQ(v string) predicate.ScheduleEntry {
	return predicate.ScheduleEntry(sql.FieldEQ(FieldClassCode, v))
}

// ClassCodeNEQ applies the NEQ predicate on the "class_code" field.
func ClassCodeNEQ(v string) predicate.ScheduleEntry {
	return predicate.ScheduleEntry(sql.FieldNEQ(FieldClassCode, v))
}

// ClassCodeIn applies the In predicate on the "class_code" field.
func ClassCodeIn(vs ...string) predicate.ScheduleEntry {
	return predicate.ScheduleEntry(sql.FieldIn(FieldClassCode, vs...))
}

// ClassCodeNotIn applies the NotIn predicate on the "class_code" field.
func ClassCodeNotIn(vs ...string) predicate.ScheduleEntry {
	return predicate.ScheduleEntry(sql.FieldNotIn(FieldClassCode, vs...))
}

// ClassCodeGT applies the GT predicate on the "class_code" field.
func ClassCodeGT(v string) predicate.ScheduleEntry {
	return predicate.ScheduleEntry(sql.FieldGT(FieldClassCode, v))
}

// ClassCodeGTE applies the GTE predicate on the "class_code" field.
func ClassCodeGTE(v string) predicate.ScheduleEntry {
	return predicate.ScheduleEntry(sql.FieldGTE(FieldClassCode, v))
}

// ClassCodeLT applies the LT predicate on the "class_code" field.
func ClassCodeLT(v string) predicate.ScheduleEntry {
	return predicate.ScheduleEntry(sql.FieldLT(FieldClassCode, v))
}

// ClassCodeLTE applies the LTE predicate on the "class_code" field.
func ClassCodeLTE(v string) predicate.ScheduleEntry {
	return predicate.ScheduleEntry(sql.FieldLTE(FieldClassCode, v))
}

// ClassCodeContains applies the Contains predicate on the "class_code" field.
func ClassCodeContains(v string) predicate.ScheduleEntry {
	return predicate.ScheduleEntry(sql.FieldContains(FieldClassCode, v))
}

// ClassCodeHasPrefix applies the HasPrefix predicate on the "class_code" field.
func ClassCodeHasPrefix(v string) predicate.ScheduleEntry {
	return predicate.ScheduleEntry(sql.FieldHasPrefix(FieldClassCode, v))
}

// ClassCodeHasSuffix applies the HasSuffix predicate on the "class_code" field.
func ClassCodeHasSuffix(v string) predicate.ScheduleEntry {
	return predicate.ScheduleEntry(sql.FieldHasSuffix(FieldClassCode, v))
}

// ClassCodeIsNil applies the IsNil predicate on the "class_code" field.
func ClassCodeIsNil() predicate.ScheduleEntry {
	return predicate.ScheduleEntry(sql.FieldIsNull(FieldClassCode))
}

// ClassCodeNotNil applies the NotNil predicate on the "class_code" field.
func ClassCodeNotNil() predicate.ScheduleEntry {
	return predicate.ScheduleEntry(sql.FieldNotNull(FieldClassCode))
}

// ClassCodeEqualFold applies the EqualFold predicate on the "class_code" field.
func ClassCodeEqualFold(v string) predicate.ScheduleEntry {
	return predicate.ScheduleEntry(sql.FieldEqualFold(FieldClassCode, v))
}

// ClassCodeContainsFold applies the ContainsFold predicate on the "class_code" field.
func ClassCodeContainsFold(v string) predicate.ScheduleEntry {
	return predicate.ScheduleEntry(sql.FieldContainsFold(FieldClassCode, v))
}

// RawJSONEQ applies the EQ predicate on the "raw_json" field.
func RawJSONEQ(v string) predicate.ScheduleEntry {
	return predicate.ScheduleEntry(sql.FieldEQ(FieldRawJSON, v))
}

// RawJSONNEQ applies the NEQ predicate on the "raw_json" field.
func RawJSONNEQ(v string) predicate.ScheduleEntry {
	return predicate.ScheduleEntry(sql.FieldNEQ(FieldRawJSON, v))
}

// RawJSONIn applies the In predicate on the "raw_json" field.
func RawJSONIn(vs ...string) predicate.ScheduleEntry {
	return predicate.ScheduleEntry(sql.FieldIn(FieldRawJSON, vs...))
}

// RawJSONNotIn applies the NotIn predicate on the "raw_json" field.
func RawJSONNotIn(vs ...string) predicate.ScheduleEntry {
	return predicate.ScheduleEntry(sql.FieldNotIn(FieldRawJSON, vs...))
}

// RawJSONGT applies the GT predicate on the "raw_json" field.
func RawJSONGT(v string) predicate.ScheduleEntry {
	return predicate.ScheduleEntry(sql.FieldGT(FieldRawJSON, v))
}

// RawJSONGTE applies the GTE predicate on the "raw_json" field.
func RawJSONGTE(v string) predicate.ScheduleEntry {
	return predicate.ScheduleEntry(sql.FieldGTE(FieldRawJSON, v))
}

// RawJSONLT applies the LT predicate on the "raw_json" field.
func RawJSONLT(v string) predicate.ScheduleEntry {
	return predicate.ScheduleEntry(sql.FieldLT(FieldRawJSON, v))
}

// RawJSONLTE applies the LTE predicate on the "raw_json" field.
func RawJSONLTE(v string) predicate.ScheduleEntry {
	return predicate.ScheduleEntry(sql.FieldLTE(FieldRawJSON, v))
}

// RawJSONContains applies the Contains predicate on the "raw_json" field.
func RawJSONContains(v string) predicate.ScheduleEntry {
	return predicate.ScheduleEntry(sql.FieldContains(FieldRawJSON, v))
}

// RawJSONHasPrefix applies the HasPrefix predicate on the "raw_json" field.
func RawJSONHasPrefix(v string) predicate.ScheduleEntry {
	return predicate.ScheduleEntry(sql.FieldHasPrefix(FieldRawJSON, v))
}

// RawJSONHasSuffix applies the HasSuffix predicate on the "raw_json" field.
func RawJSONHasSuffix(v string) predicate.ScheduleEntry {
	return predicate.ScheduleEntry(sql.FieldHasSuffix(FieldRawJSON, v))
}

// RawJSONIsNil applies the IsNil predicate on the "raw_json" field.
func RawJSONIsNil() predicate.ScheduleEntry {
	return predicate.ScheduleEntry(sql.FieldIsNull(FieldRawJSON))
}

// RawJSONNotNil applies the NotNil predicate on the "raw_json" field.
func RawJSONNotNil() predicate.ScheduleEntry {
	return predicate.ScheduleEntry(sql.FieldNotNull(FieldRawJSON))
}

// RawJSONEqualFold applies the EqualFold predicate on the "raw_json" field.
func RawJSONEqualFold(v string) predicate.ScheduleEntry {
	return predicate.ScheduleEntry(sql.FieldEqualFold(FieldRawJSON, v))
}

// RawJSONContainsFold applies the ContainsFold predicate on the "raw_json" field.
func RawJSONContainsFold(v string) predicate.ScheduleEntry {
	return predicate.ScheduleEntry(sql.FieldContainsFold(FieldRawJSON, v))
}

// SyncedAtEQ applies the EQ predicate on the "synced_at" field.
func SyncedAtEQ(v time.Time) predicate.ScheduleEntry {
	return predicate.ScheduleEntry(sql.FieldEQ(FieldSyncedAt, v))
}

// SyncedAtNEQ applies the NEQ predicate on the "synced_at" field.
func SyncedAtNEQ(v time.Time) predicate.ScheduleEntry {
	return predicate.ScheduleEntry(sql.FieldNEQ(FieldSyncedAt, v))
}

// SyncedAtIn applies the In predicate on the "synced_at" field.
func SyncedAtIn(vs ...time.Time) predicate.ScheduleEntry {
	return predicate.ScheduleEntry(sql.FieldIn(FieldSyncedAt, vs...))
}

// SyncedAtNotIn applies the NotIn predicate on the "synced_at" field.
func SyncedAtNotIn(vs ...time.Time) predicate.ScheduleEntry {
	return predicate.ScheduleEntry(sql.FieldNotIn(FieldSyncedAt, vs...))
}

// SyncedAtGT applies the GT predicate on the "synced_at" field.
func SyncedAtGT(v time.Time) predicate.ScheduleEntry {
	return predicate.ScheduleEntry(sql.FieldGT(FieldSyncedAt, v))
}

// SyncedAtGTE applies the GTE predicate on the "synced_at" field.
func SyncedAtGTE(v time.Time) predicate.ScheduleEntry {
	return predicate.ScheduleEntry(sql.FieldGTE(FieldSyncedAt, v))
}

// SyncedAtLT applies the LT predicate on the "synced_at" field.
func SyncedAtLT(v time.Time) predicate.ScheduleEntry {
	return predicate.ScheduleEntry(sql.FieldLT(FieldSyncedAt, v))
}

// SyncedAtLTE applies the LTE predicate on the "synced_at" field.
func SyncedAtLTE(v time.Time) predicate.ScheduleEntry {
	return predicate.ScheduleEntry(sql.FieldLTE(FieldSyncedAt, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.ScheduleEntry {
	return predicate.ScheduleEntry(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.ScheduleEntry {
	return predicate.ScheduleEntry(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.ScheduleEntry {
	return predicate.ScheduleEntry(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.ScheduleEntry {
	return predicate.ScheduleEntry(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.ScheduleEntry {
	return predicate.ScheduleEntry(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.ScheduleEntry {
	return predicate.ScheduleEntry(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.ScheduleEntry {
	return predicate.ScheduleEntry(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.ScheduleEntry {
	return predicate.ScheduleEntry(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.ScheduleEntry {
	return predicate.ScheduleEntry(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.ScheduleEntry {
	return predicate.ScheduleEntry(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.ScheduleEntry {
	return predicate.ScheduleEntry(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.ScheduleEntry {
	return predicate.ScheduleEntry(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.ScheduleEntry {
	return predicate.ScheduleEntry(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.ScheduleEntry {
	return predicate.ScheduleEntry(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.ScheduleEntry {
	return predicate.ScheduleEntry(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.ScheduleEntry {
	return predicate.ScheduleEntry(sql.FieldLTE(FieldUpdatedAt, v))
}

// HasUser applies the HasEdge predicate on the "user" edge.
func HasUser() predicate.ScheduleEntry {
	return predicate.ScheduleEntry(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, UserTable, UserColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasUserWith applies the HasEdge predicate on the "user" edge with a given conditions (other predicates).
func HasUserWith(preds ...predicate.User) predicate.ScheduleEntry {
	return predicate.ScheduleEntry(func(s *sql.Selector) {
		step := newUserStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.ScheduleEntry) predicate.ScheduleEntry {
	return predicate.ScheduleEntry(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.ScheduleEntry) predicate.ScheduleEntry {
	return predicate.ScheduleEntry(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.ScheduleEntry) predicate.ScheduleEntry {
	return predicate.ScheduleEntry(sql.NotPredicates(p))
}
