// Code generated by ent, DO NOT EDIT.

package calendarsubscription

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the calendarsubscription type in the database.
	Label = "calendar_subscription"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldTokenHash holds the string denoting the token_hash field in the database.
	FieldTokenHash = "token_hash"
	// FieldEncryptedToken holds the string denoting the encrypted_token field in the database.
	FieldEncryptedToken = "encrypted_token"
	// FieldEnabled holds the string denoting the enabled field in the database.
	FieldEnabled = "enabled"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// EdgeUser holds the string denoting the user edge name in mutations.
	EdgeUser = "user"
	// EdgeRequestLogs holds the string denoting the request_logs edge name in mutations.
	EdgeRequestLogs = "request_logs"
	// Table holds the table name of the calendarsubscription in the database.
	Table = "calendar_subscriptions"
	// UserTable is the table that holds the user relation/edge.
	UserTable = "calendar_subscriptions"
	// UserInverseTable is the table name for the User entity.
	// It exists in this package in order to avoid circular dependency with the "user" package.
	UserInverseTable = "users"
	// UserColumn is the table column denoting the user relation/edge.
	UserColumn = "user_calendar_subscriptions"
	// RequestLogsTable is the table that holds the request_logs relation/edge.
	RequestLogsTable = "calendar_request_logs"
	// RequestLogsInverseTable is the table name for the CalendarRequestLog entity.
	// It exists in this package in order to avoid circular dependency with the "calendarrequestlog" package.
	RequestLogsInverseTable = "calendar_request_logs"
	// RequestLogsColumn is the table column denoting the request_logs relation/edge.
	RequestLogsColumn = "calendar_subscription_request_logs"
)

// Columns holds all SQL columns for calendarsubscription fields.
var Columns = []string{
	FieldID,
	FieldTokenHash,
	FieldEncryptedToken,
	FieldEnabled,
	FieldCreatedAt,
	FieldUpdatedAt,
}

// ForeignKeys holds the SQL foreign-keys that are owned by the "calendar_subscriptions"
// table and are not defined as standalone fields in the schema.
var ForeignKeys = []string{
	"user_calendar_subscriptions",
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	for i := range ForeignKeys {
		if column == ForeignKeys[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultEnabled holds the default value on creation for the "enabled" field.
	DefaultEnabled bool
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
)

// OrderOption defines the ordering options for the CalendarSubscription queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByTokenHash orders the results by the token_hash field.
func ByTokenHash(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTokenHash, opts...).ToFunc()
}

// ByEncryptedToken orders the results by the encrypted_token field.
func ByEncryptedToken(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEncryptedToken, opts...).ToFunc()
}

// ByEnabled orders the results by the enabled field.
func ByEnabled(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEnabled, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByUserField orders the results by user field.
func ByUserField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newUserStep(), sql.OrderByField(field, opts...))
	}
}

// ByRequestLogsCount orders the results by request_logs count.
func ByRequestLogsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newRequestLogsStep(), opts...)
	}
}

// ByRequestLogs orders the results by request_logs terms.
func ByRequestLogs(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newRequestLogsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}
func newUserStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(UserInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, UserTable, UserColumn),
	)
}
func newRequestLogsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(RequestLogsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, RequestLogsTable, RequestLogsColumn),
	)
}
