// Code generated by ent, DO NOT EDIT.

package calendarsubscription

import (
	"gaia-calendar/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.CalendarSubscription {
	return predicate.CalendarSubscription(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.CalendarSubscription {
	return predicate.CalendarSubscription(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.CalendarSubscription {
	return predicate.CalendarSubscription(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.CalendarSubscription {
	return predicate.CalendarSubscription(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.CalendarSubscription {
	return predicate.CalendarSubscription(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.CalendarSubscription {
	return predicate.CalendarSubscription(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.CalendarSubscription {
	return predicate.CalendarSubscription(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.CalendarSubscription {
	return predicate.CalendarSubscription(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.CalendarSubscription {
	return predicate.CalendarSubscription(sql.FieldLTE(FieldID, id))
}

// TokenHash applies equality check predicate on the "token_hash" field. It's identical to TokenHashEQ.
func TokenHash(v string) predicate.CalendarSubscription {
	return predicate.CalendarSubscription(sql.FieldEQ(FieldTokenHash, v))
}

// EncryptedToken applies equality check predicate on the "encrypted_token" field. It's identical to EncryptedTokenEQ.
func EncryptedToken(v string) predicate.CalendarSubscription {
	return predicate.CalendarSubscription(sql.FieldEQ(FieldEncryptedToken, v))
}

// Enabled applies equality check predicate on the "enabled" field. It's identical to EnabledEQ.
func Enabled(v bool) predicate.CalendarSubscription {
	return predicate.CalendarSubscription(sql.FieldEQ(FieldEnabled, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.CalendarSubscription {
	return predicate.CalendarSubscription(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.CalendarSubscription {
	return predicate.CalendarSubscription(sql.FieldEQ(FieldUpdatedAt, v))
}

// TokenHashEQ applies the EQ predicate on the "token_hash" field.
func TokenHashEQ(v string) predicate.CalendarSubscription {
	return predicate.CalendarSubscription(sql.FieldEQ(FieldTokenHash, v))
}

// TokenHashNEQ applies the NEQ predicate on the "token_hash" field.
func TokenHashNEQ(v string) predicate.CalendarSubscription {
	return predicate.CalendarSubscription(sql.FieldNEQ(FieldTokenHash, v))
}

// TokenHashIn applies the In predicate on the "token_hash" field.
func TokenHashIn(vs ...string) predicate.CalendarSubscription {
	return predicate.CalendarSubscription(sql.FieldIn(FieldTokenHash, vs...))
}

// TokenHashNotIn applies the NotIn predicate on the "token_hash" field.
func TokenHashNotIn(vs ...string) predicate.CalendarSubscription {
	return predicate.CalendarSubscription(sql.FieldNotIn(FieldTokenHash, vs...))
}

// TokenHashGT applies the GT predicate on the "token_hash" field.
func TokenHashGT(v string) predicate.CalendarSubscription {
	return predicate.CalendarSubscription(sql.FieldGT(FieldTokenHash, v))
}

// TokenHashGTE applies the GTE predicate on the "token_hash" field.
func TokenHashGTE(v string) predicate.CalendarSubscription {
	return predicate.CalendarSubscription(sql.FieldGTE(FieldTokenHash, v))
}

// TokenHashLT applies the LT predicate on the "token_hash" field.
func TokenHashLT(v string) predicate.CalendarSubscription {
	return predicate.CalendarSubscription(sql.FieldLT(FieldTokenHash, v))
}

// TokenHashLTE applies the LTE predicate on the "token_hash" field.
func TokenHashLTE(v string) predicate.CalendarSubscription {
	return predicate.CalendarSubscription(sql.FieldLTE(FieldTokenHash, v))
}

// TokenHashContains applies the Contains predicate on the "token_hash" field.
func TokenHashContains(v string) predicate.CalendarSubscription {
	return predicate.CalendarSubscription(sql.FieldContains(FieldTokenHash, v))
}

// TokenHashHasPrefix applies the HasPrefix predicate on the "token_hash" field.
func TokenHashHasPrefix(v string) predicate.CalendarSubscription {
	return predicate.CalendarSubscription(sql.FieldHasPrefix(FieldTokenHash, v))
}

// TokenHashHasSuffix applies the HasSuffix predicate on the "token_hash" field.
func TokenHashHasSuffix(v string) predicate.CalendarSubscription {
	return predicate.CalendarSubscription(sql.FieldHasSuffix(FieldTokenHash, v))
}

// TokenHashEqualFold applies the EqualFold predicate on the "token_hash" field.
func TokenHashEqualFold(v string) predicate.CalendarSubscription {
	return predicate.CalendarSubscription(sql.FieldEqualFold(FieldTokenHash, v))
}

// TokenHashContainsFold applies the ContainsFold predicate on the "token_hash" field.
func TokenHashContainsFold(v string) predicate.CalendarSubscription {
	return predicate.CalendarSubscription(sql.FieldContainsFold(FieldTokenHash, v))
}

// EncryptedTokenEQ applies the EQ predicate on the "encrypted_token" field.
func EncryptedTokenEQ(v string) predicate.CalendarSubscription {
	return predicate.CalendarSubscription(sql.FieldEQ(FieldEncryptedToken, v))
}

// EncryptedTokenNEQ applies the NEQ predicate on the "encrypted_token" field.
func EncryptedTokenNEQ(v string) predicate.CalendarSubscription {
	return predicate.CalendarSubscription(sql.FieldNEQ(FieldEncryptedToken, v))
}

// EncryptedTokenIn applies the In predicate on the "encrypted_token" field.
func EncryptedTokenIn(vs ...string) predicate.CalendarSubscription {
	return predicate.CalendarSubscription(sql.FieldIn(FieldEncryptedToken, vs...))
}

// EncryptedTokenNotIn applies the NotIn predicate on the "encrypted_token" field.
func EncryptedTokenNotIn(vs ...string) predicate.CalendarSubscription {
	return predicate.CalendarSubscription(sql.FieldNotIn(FieldEncryptedToken, vs...))
}

// EncryptedTokenGT applies the GT predicate on the "encrypted_token" field.
func EncryptedTokenGT(v string) predicate.CalendarSubscription {
	return predicate.CalendarSubscription(sql.FieldGT(FieldEncryptedToken, v))
}

// EncryptedTokenGTE applies the GTE predicate on the "encrypted_token" field.
func EncryptedTokenGTE(v string) predicate.CalendarSubscription {
	return predicate.CalendarSubscription(sql.FieldGTE(FieldEncryptedToken, v))
}

// EncryptedTokenLT applies the LT predicate on the "encrypted_token" field.
func EncryptedTokenLT(v string) predicate.CalendarSubscription {
	return predicate.CalendarSubscription(sql.FieldLT(FieldEncryptedToken, v))
}

// EncryptedTokenLTE applies the LTE predicate on the "encrypted_token" field.
func EncryptedTokenLTE(v string) predicate.CalendarSubscription {
	return predicate.CalendarSubscription(sql.FieldLTE(FieldEncryptedToken, v))
}

// EncryptedTokenContains applies the Contains predicate on the "encrypted_token" field.
func EncryptedTokenContains(v string) predicate.CalendarSubscription {
	return predicate.CalendarSubscription(sql.FieldContains(FieldEncryptedToken, v))
}

// EncryptedTokenHasPrefix applies the HasPrefix predicate on the "encrypted_token" field.
func EncryptedTokenHasPrefix(v string) predicate.CalendarSubscription {
	return predicate.CalendarSubscription(sql.FieldHasPrefix(FieldEncryptedToken, v))
}

// EncryptedTokenHasSuffix applies the HasSuffix predicate on the "encrypted_token" field.
func EncryptedTokenHasSuffix(v string) predicate.CalendarSubscription {
	return predicate.CalendarSubscription(sql.FieldHasSuffix(FieldEncryptedToken, v))
}

// EncryptedTokenEqualFold applies the EqualFold predicate on the "encrypted_token" field.
func EncryptedTokenEqualFold(v string) predicate.CalendarSubscription {
	return predicate.CalendarSubscription(sql.FieldEqualFold(FieldEncryptedToken, v))
}

// EncryptedTokenContainsFold applies the ContainsFold predicate on the "encrypted_token" field.
func EncryptedTokenContainsFold(v string) predicate.CalendarSubscription {
	return predicate.CalendarSubscription(sql.FieldContainsFold(FieldEncryptedToken, v))
}

// EnabledEQ applies the EQ predicate on the "enabled" field.
func EnabledEQ(v bool) predicate.CalendarSubscription {
	return predicate.CalendarSubscription(sql.FieldEQ(FieldEnabled, v))
}

// EnabledNEQ applies the NEQ predicate on the "enabled" field.
func EnabledNEQ(v bool) predicate.CalendarSubscription {
	return predicate.CalendarSubscription(sql.FieldNEQ(FieldEnabled, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.CalendarSubscription {
	return predicate.CalendarSubscription(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.CalendarSubscription {
	return predicate.CalendarSubscription(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.CalendarSubscription {
	return predicate.CalendarSubscription(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.CalendarSubscription {
	return predicate.CalendarSubscription(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.CalendarSubscription {
	return predicate.CalendarSubscription(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.CalendarSubscription {
	return predicate.CalendarSubscription(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.CalendarSubscription {
	return predicate.CalendarSubscription(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.CalendarSubscription {
	return predicate.CalendarSubscription(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.CalendarSubscription {
	return predicate.CalendarSubscription(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.CalendarSubscription {
	return predicate.CalendarSubscription(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.CalendarSubscription {
	return predicate.CalendarSubscription(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.CalendarSubscription {
	return predicate.CalendarSubscription(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.CalendarSubscription {
	return predicate.CalendarSubscription(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.CalendarSubscription {
	return predicate.CalendarSubscription(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.CalendarSubscription {
	return predicate.CalendarSubscription(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.CalendarSubscription {
	return predicate.CalendarSubscription(sql.FieldLTE(FieldUpdatedAt, v))
}

// HasUser applies the HasEdge predicate on the "user" edge.
func HasUser() predicate.CalendarSubscription {
	return predicate.CalendarSubscription(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, UserTable, UserColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasUserWith applies the HasEdge predicate on the "user" edge with a given conditions (other predicates).
func HasUserWith(preds ...predicate.User) predicate.CalendarSubscription {
	return predicate.CalendarSubscription(func(s *sql.Selector) {
		step := newUserStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasRequestLogs applies the HasEdge predicate on the "request_logs" edge.
func HasRequestLogs() predicate.CalendarSubscription {
	return predicate.CalendarSubscription(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, RequestLogsTable, RequestLogsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasRequestLogsWith applies the HasEdge predicate on the "request_logs" edge with a given conditions (other predicates).
func HasRequestLogsWith(preds ...predicate.CalendarRequestLog) predicate.CalendarSubscription {
	return predicate.CalendarSubscription(func(s *sql.Selector) {
		step := newRequestLogsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.CalendarSubscription) predicate.CalendarSubscription {
	return predicate.CalendarSubscription(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.CalendarSubscription) predicate.CalendarSubscription {
	return predicate.CalendarSubscription(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.CalendarSubscription) predicate.CalendarSubscription {
	return predicate.CalendarSubscription(sql.NotPredicates(p))
}
