// Code generated by ent, DO NOT EDIT.

package gaiacredential

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the gaiacredential type in the database.
	Label = "gaia_credential"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCompanyCode holds the string denoting the company_code field in the database.
	FieldCompanyCode = "company_code"
	// FieldEmployeeAccount holds the string denoting the employee_account field in the database.
	FieldEmployeeAccount = "employee_account"
	// FieldEncryptedPassword holds the string denoting the encrypted_password field in the database.
	FieldEncryptedPassword = "encrypted_password"
	// FieldCredentialStatus holds the string denoting the credential_status field in the database.
	FieldCredentialStatus = "credential_status"
	// FieldLastLoginAt holds the string denoting the last_login_at field in the database.
	FieldLastLoginAt = "last_login_at"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// EdgeUser holds the string denoting the user edge name in mutations.
	EdgeUser = "user"
	// Table holds the table name of the gaiacredential in the database.
	Table = "gaia_credentials"
	// UserTable is the table that holds the user relation/edge.
	UserTable = "gaia_credentials"
	// UserInverseTable is the table name for the User entity.
	// It exists in this package in order to avoid circular dependency with the "user" package.
	UserInverseTable = "users"
	// UserColumn is the table column denoting the user relation/edge.
	UserColumn = "user_gaia_credentials"
)

// Columns holds all SQL columns for gaiacredential fields.
var Columns = []string{
	FieldID,
	FieldCompanyCode,
	FieldEmployeeAccount,
	FieldEncryptedPassword,
	FieldCredentialStatus,
	FieldLastLoginAt,
	FieldCreatedAt,
	FieldUpdatedAt,
}

// ForeignKeys holds the SQL foreign-keys that are owned by the "gaia_credentials"
// table and are not defined as standalone fields in the schema.
var ForeignKeys = []string{
	"user_gaia_credentials",
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	for i := range ForeignKeys {
		if column == ForeignKeys[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCompanyCode holds the default value on creation for the "company_code" field.
	DefaultCompanyCode string
	// EmployeeAccountValidator is a validator for the "employee_account" field. It is called by the builders before save.
	EmployeeAccountValidator func(string) error
	// DefaultCredentialStatus holds the default value on creation for the "credential_status" field.
	DefaultCredentialStatus string
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
)

// OrderOption defines the ordering options for the GaiaCredential queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCompanyCode orders the results by the company_code field.
func ByCompanyCode(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCompanyCode, opts...).ToFunc()
}

// ByEmployeeAccount orders the results by the employee_account field.
func ByEmployeeAccount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEmployeeAccount, opts...).ToFunc()
}

// ByEncryptedPassword orders the results by the encrypted_password field.
func ByEncryptedPassword(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEncryptedPassword, opts...).ToFunc()
}

// ByCredentialStatus orders the results by the credential_status field.
func ByCredentialStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCredentialStatus, opts...).ToFunc()
}

// ByLastLoginAt orders the results by the last_login_at field.
func ByLastLoginAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLastLoginAt, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByUserField orders the results by user field.
func ByUserField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newUserStep(), sql.OrderByField(field, opts...))
	}
}
func newUserStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(UserInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, UserTable, UserColumn),
	)
}
