// Code generated by ent, DO NOT EDIT.

package gaiacredential

import (
	"gaia-calendar/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.GaiaCredential {
	return predicate.GaiaCredential(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.GaiaCredential {
	return predicate.GaiaCredential(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.GaiaCredential {
	return predicate.GaiaCredential(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.GaiaCredential {
	return predicate.GaiaCredential(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.GaiaCredential {
	return predicate.GaiaCredential(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.GaiaCredential {
	return predicate.GaiaCredential(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.GaiaCredential {
	return predicate.GaiaCredential(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.GaiaCredential {
	return predicate.GaiaCredential(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.GaiaCredential {
	return predicate.GaiaCredential(sql.FieldLTE(FieldID, id))
}

// CompanyCode applies equality check predicate on the "company_code" field. It's identical to CompanyCodeEQ.
func CompanyCode(v string) predicate.GaiaCredential {
	return predicate.GaiaCredential(sql.FieldEQ(FieldCompanyCode, v))
}

// EmployeeAccount applies equality check predicate on the "employee_account" field. It's identical to EmployeeAccountEQ.
func EmployeeAccount(v string) predicate.GaiaCredential {
	return predicate.GaiaCredential(sql.FieldEQ(FieldEmployeeAccount, v))
}

// EncryptedPassword applies equality check predicate on the "encrypted_password" field. It's identical to EncryptedPasswordEQ.
func EncryptedPassword(v string) predicate.GaiaCredential {
	return predicate.GaiaCredential(sql.FieldEQ(FieldEncryptedPassword, v))
}

// CredentialStatus applies equality check predicate on the "credential_status" field. It's identical to CredentialStatusEQ.
func CredentialStatus(v string) predicate.GaiaCredential {
	return predicate.GaiaCredential(sql.FieldEQ(FieldCredentialStatus, v))
}

// LastLoginAt applies equality check predicate on the "last_login_at" field. It's identical to LastLoginAtEQ.
func LastLoginAt(v time.Time) predicate.GaiaCredential {
	return predicate.GaiaCredential(sql.FieldEQ(FieldLastLoginAt, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.GaiaCredential {
	return predicate.GaiaCredential(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.GaiaCredential {
	return predicate.GaiaCredential(sql.FieldEQ(FieldUpdatedAt, v))
}

// CompanyCodeEQ applies the EQ predicate on the "company_code" field.
func CompanyCodeEQ(v string) predicate.GaiaCredential {
	return predicate.GaiaCredential(sql.FieldEQ(FieldCompanyCode, v))
}

// CompanyCodeNEQ applies the NEQ predicate on the "company_code" field.
func CompanyCodeNEQ(v string) predicate.GaiaCredential {
	return predicate.GaiaCredential(sql.FieldNEQ(FieldCompanyCode, v))
}

// CompanyCodeIn applies the In predicate on the "company_code" field.
func CompanyCodeIn(vs ...string) predicate.GaiaCredential {
	return predicate.GaiaCredential(sql.FieldIn(FieldCompanyCode, vs...))
}

// CompanyCodeNotIn applies the NotIn predicate on the "company_code" field.
func CompanyCodeNotIn(vs ...string) predicate.GaiaCredential {
	return predicate.GaiaCredential(sql.FieldNotIn(FieldCompanyCode, vs...))
}

// CompanyCodeGT applies the GT predicate on the "company_code" field.
func CompanyCodeGT(v string) predicate.GaiaCredential {
	return predicate.GaiaCredential(sql.FieldGT(FieldCompanyCode, v))
}

// CompanyCodeGTE applies the GTE predicate on the "company_code" field.
func CompanyCodeGTE(v string) predicate.GaiaCredential {
	return predicate.GaiaCredential(sql.FieldGTE(FieldCompanyCode, v))
}

// CompanyCodeLT applies the LT predicate on the "company_code" field.
func CompanyCodeLT(v string) predicate.GaiaCredential {
	return predicate.GaiaCredential(sql.FieldLT(FieldCompanyCode, v))
}

// CompanyCodeLTE applies the LTE predicate on the "company_code" field.
func CompanyCodeLTE(v string) predicate.GaiaCredential {
	return predicate.GaiaCredential(sql.FieldLTE(FieldCompanyCode, v))
}

// CompanyCodeContains applies the Contains predicate on the "company_code" field.
func CompanyCodeContains(v string) predicate.GaiaCredential {
	return predicate.GaiaCredential(sql.FieldContains(FieldCompanyCode, v))
}

// CompanyCodeHasPrefix applies the HasPrefix predicate on the "company_code" field.
func CompanyCodeHasPrefix(v string) predicate.GaiaCredential {
	return predicate.GaiaCredential(sql.FieldHasPrefix(FieldCompanyCode, v))
}

// CompanyCodeHasSuffix applies the HasSuffix predicate on the "company_code" field.
func CompanyCodeHasSuffix(v string) predicate.GaiaCredential {
	return predicate.GaiaCredential(sql.FieldHasSuffix(FieldCompanyCode, v))
}

// CompanyCodeEqualFold applies the EqualFold predicate on the "company_code" field.
func CompanyCodeEqualFold(v string) predicate.GaiaCredential {
	return predicate.GaiaCredential(sql.FieldEqualFold(FieldCompanyCode, v))
}

// CompanyCodeContainsFold applies the ContainsFold predicate on the "company_code" field.
func CompanyCodeContainsFold(v string) predicate.GaiaCredential {
	return predicate.GaiaCredential(sql.FieldContainsFold(FieldCompanyCode, v))
}

// EmployeeAccountEQ applies the EQ predicate on the "employee_account" field.
func EmployeeAccountEQ(v string) predicate.GaiaCredential {
	return predicate.GaiaCredential(sql.FieldEQ(FieldEmployeeAccount, v))
}

// EmployeeAccountNEQ applies the NEQ predicate on the "employee_account" field.
func EmployeeAccountNEQ(v string) predicate.GaiaCredential {
	return predicate.GaiaCredential(sql.FieldNEQ(FieldEmployeeAccount, v))
}

// EmployeeAccountIn applies the In predicate on the "employee_account" field.
func EmployeeAccountIn(vs ...string) predicate.GaiaCredential {
	return predicate.GaiaCredential(sql.FieldIn(FieldEmployeeAccount, vs...))
}

// EmployeeAccountNotIn applies the NotIn predicate on the "employee_account" field.
func EmployeeAccountNotIn(vs ...string) predicate.GaiaCredential {
	return predicate.GaiaCredential(sql.FieldNotIn(FieldEmployeeAccount, vs...))
}

// EmployeeAccountGT applies the GT predicate on the "employee_account" field.
func EmployeeAccountGT(v string) predicate.GaiaCredential {
	return predicate.GaiaCredential(sql.FieldGT(FieldEmployeeAccount, v))
}

// EmployeeAccountGTE applies the GTE predicate on the "employee_account" field.
func EmployeeAccountGTE(v string) predicate.GaiaCredential {
	return predicate.GaiaCredential(sql.FieldGTE(FieldEmployeeAccount, v))
}

// EmployeeAccountLT applies the LT predicate on the "employee_account" field.
func EmployeeAccountLT(v string) predicate.GaiaCredential {
	return predicate.GaiaCredential(sql.FieldLT(FieldEmployeeAccount, v))
}

// EmployeeAccountLTE applies the LTE predicate on the "employee_account" field.
func EmployeeAccountLTE(v string) predicate.GaiaCredential {
	return predicate.GaiaCredential(sql.FieldLTE(FieldEmployeeAccount, v))
}

// EmployeeAccountContains applies the Contains predicate on the "employee_account" field.
func EmployeeAccountContains(v string) predicate.GaiaCredential {
	return predicate.GaiaCredential(sql.FieldContains(FieldEmployeeAccount, v))
}

// EmployeeAccountHasPrefix applies the HasPrefix predicate on the "employee_account" field.
func EmployeeAccountHasPrefix(v string) predicate.GaiaCredential {
	return predicate.GaiaCredential(sql.FieldHasPrefix(FieldEmployeeAccount, v))
}

// EmployeeAccountHasSuffix applies the HasSuffix predicate on the "employee_account" field.
func EmployeeAccountHasSuffix(v string) predicate.GaiaCredential {
	return predicate.GaiaCredential(sql.FieldHasSuffix(FieldEmployeeAccount, v))
}

// EmployeeAccountEqualFold applies the EqualFold predicate on the "employee_account" field.
func EmployeeAccountEqualFold(v string) predicate.GaiaCredential {
	return predicate.GaiaCredential(sql.FieldEqualFold(FieldEmployeeAccount, v))
}

// EmployeeAccountContainsFold applies the ContainsFold predicate on the "employee_account" field.
func EmployeeAccountContainsFold(v string) predicate.GaiaCredential {
	return predicate.GaiaCredential(sql.FieldContainsFold(FieldEmployeeAccount, v))
}

// EncryptedPasswordEQ applies the EQ predicate on the "encrypted_password" field.
func EncryptedPasswordEQ(v string) predicate.GaiaCredential {
	return predicate.GaiaCredential(sql.FieldEQ(FieldEncryptedPassword, v))
}

// EncryptedPasswordNEQ applies the NEQ predicate on the "encrypted_password" field.
func EncryptedPasswordNEQ(v string) predicate.GaiaCredential {
	return predicate.GaiaCredential(sql.FieldNEQ(FieldEncryptedPassword, v))
}

// EncryptedPasswordIn applies the In predicate on the "encrypted_password" field.
func EncryptedPasswordIn(vs ...string) predicate.GaiaCredential {
	return predicate.GaiaCredential(sql.FieldIn(FieldEncryptedPassword, vs...))
}

// EncryptedPasswordNotIn applies the NotIn predicate on the "encrypted_password" field.
func EncryptedPasswordNotIn(vs ...string) predicate.GaiaCredential {
	return predicate.GaiaCredential(sql.FieldNotIn(FieldEncryptedPassword, vs...))
}

// EncryptedPasswordGT applies the GT predicate on the "encrypted_password" field.
func EncryptedPasswordGT(v string) predicate.GaiaCredential {
	return predicate.GaiaCredential(sql.FieldGT(FieldEncryptedPassword, v))
}

// EncryptedPasswordGTE applies the GTE predicate on the "encrypted_password" field.
func EncryptedPasswordGTE(v string) predicate.GaiaCredential {
	return predicate.GaiaCredential(sql.FieldGTE(FieldEncryptedPassword, v))
}

// EncryptedPasswordLT applies the LT predicate on the "encrypted_password" field.
func EncryptedPasswordLT(v string) predicate.GaiaCredential {
	return predicate.GaiaCredential(sql.FieldLT(FieldEncryptedPassword, v))
}

// EncryptedPasswordLTE applies the LTE predicate on the "encrypted_password" field.
func EncryptedPasswordLTE(v string) predicate.GaiaCredential {
	return predicate.GaiaCredential(sql.FieldLTE(FieldEncryptedPassword, v))
}

// EncryptedPasswordContains applies the Contains predicate on the "encrypted_password" field.
func EncryptedPasswordContains(v string) predicate.GaiaCredential {
	return predicate.GaiaCredential(sql.FieldContains(FieldEncryptedPassword, v))
}

// EncryptedPasswordHasPrefix applies the HasPrefix predicate on the "encrypted_password" field.
func EncryptedPasswordHasPrefix(v string) predicate.GaiaCredential {
	return predicate.GaiaCredential(sql.FieldHasPrefix(FieldEncryptedPassword, v))
}

// EncryptedPasswordHasSuffix applies the HasSuffix predicate on the "encrypted_password" field.
func EncryptedPasswordHasSuffix(v string) predicate.GaiaCredential {
	return predicate.GaiaCredential(sql.FieldHasSuffix(FieldEncryptedPassword, v))
}

// EncryptedPasswordEqualFold applies the EqualFold predicate on the "encrypted_password" field.
func EncryptedPasswordEqualFold(v string) predicate.GaiaCredential {
	return predicate.GaiaCredential(sql.FieldEqualFold(FieldEncryptedPassword, v))
}

// EncryptedPasswordContainsFold applies the ContainsFold predicate on the "encrypted_password" field.
func EncryptedPasswordContainsFold(v string) predicate.GaiaCredential {
	return predicate.GaiaCredential(sql.FieldContainsFold(FieldEncryptedPassword, v))
}

// CredentialStatusEQ applies the EQ predicate on the "credential_status" field.
func CredentialStatusEQ(v string) predicate.GaiaCredential {
	return predicate.GaiaCredential(sql.FieldEQ(FieldCredentialStatus, v))
}

// CredentialStatusNEQ applies the NEQ predicate on the "credential_status" field.
func CredentialStatusNEQ(v string) predicate.GaiaCredential {
	return predicate.GaiaCredential(sql.FieldNEQ(FieldCredentialStatus, v))
}

// CredentialStatusIn applies the In predicate on the "credential_status" field.
func CredentialStatusIn(vs ...string) predicate.GaiaCredential {
	return predicate.GaiaCredential(sql.FieldIn(FieldCredentialStatus, vs...))
}

// CredentialStatusNotIn applies the NotIn predicate on the "credential_status" field.
func CredentialStatusNotIn(vs ...string) predicate.GaiaCredential {
	return predicate.GaiaCredential(sql.FieldNotIn(FieldCredentialStatus, vs...))
}

// CredentialStatusGT applies the GT predicate on the "credential_status" field.
func CredentialStatusGT(v string) predicate.GaiaCredential {
	return predicate.GaiaCredential(sql.FieldGT(FieldCredentialStatus, v))
}

// CredentialStatusGTE applies the GTE predicate on the "credential_status" field.
func CredentialStatusGTE(v string) predicate.GaiaCredential {
	return predicate.GaiaCredential(sql.FieldGTE(FieldCredentialStatus, v))
}

// CredentialStatusLT applies the LT predicate on the "credential_status" field.
func CredentialStatusLT(v string) predicate.GaiaCredential {
	return predicate.GaiaCredential(sql.FieldLT(FieldCredentialStatus, v))
}

// CredentialStatusLTE applies the LTE predicate on the "credential_status" field.
func CredentialStatusLTE(v string) predicate.GaiaCredential {
	return predicate.GaiaCredential(sql.FieldLTE(FieldCredentialStatus, v))
}

// CredentialStatusContains applies the Contains predicate on the "credential_status" field.
func CredentialStatusContains(v string) predicate.GaiaCredential {
	return predicate.GaiaCredential(sql.FieldContains(FieldCredentialStatus, v))
}

// CredentialStatusHasPrefix applies the HasPrefix predicate on the "credential_status" field.
func CredentialStatusHasPrefix(v string) predicate.GaiaCredential {
	return predicate.GaiaCredential(sql.FieldHasPrefix(FieldCredentialStatus, v))
}

// CredentialStatusHasSuffix applies the HasSuffix predicate on the "credential_status" field.
func CredentialStatusHasSuffix(v string) predicate.GaiaCredential {
	return predicate.GaiaCredential(sql.FieldHasSuffix(FieldCredentialStatus, v))
}

// CredentialStatusEqualFold applies the EqualFold predicate on the "credential_status" field.
func CredentialStatusEqualFold(v string) predicate.GaiaCredential {
	return predicate.GaiaCredential(sql.FieldEqualFold(FieldCredentialStatus, v))
}

// CredentialStatusContainsFold applies the ContainsFold predicate on the "credential_status" field.
func CredentialStatusContainsFold(v string) predicate.GaiaCredential {
	return predicate.GaiaCredential(sql.FieldContainsFold(FieldCredentialStatus, v))
}

// LastLoginAtEQ applies the EQ predicate on the "last_login_at" field.
func LastLoginAtEQ(v time.Time) predicate.GaiaCredential {
	return predicate.GaiaCredential(sql.FieldEQ(FieldLastLoginAt, v))
}

// LastLoginAtNEQ applies the NEQ predicate on the "last_login_at" field.
func LastLoginAtNEQ(v time.Time) predicate.GaiaCredential {
	return predicate.GaiaCredential(sql.FieldNEQ(FieldLastLoginAt, v))
}

// LastLoginAtIn applies the In predicate on the "last_login_at" field.
func LastLoginAtIn(vs ...time.Time) predicate.GaiaCredential {
	return predicate.GaiaCredential(sql.FieldIn(FieldLastLoginAt, vs...))
}

// LastLoginAtNotIn applies the NotIn predicate on the "last_login_at" field.
func LastLoginAtNotIn(vs ...time.Time) predicate.GaiaCredential {
	return predicate.GaiaCredential(sql.FieldNotIn(FieldLastLoginAt, vs...))
}

// LastLoginAtGT applies the GT predicate on the "last_login_at" field.
func LastLoginAtGT(v time.Time) predicate.GaiaCredential {
	return predicate.GaiaCredential(sql.FieldGT(FieldLastLoginAt, v))
}

// LastLoginAtGTE applies the GTE predicate on the "last_login_at" field.
func LastLoginAtGTE(v time.Time) predicate.GaiaCredential {
	return predicate.GaiaCredential(sql.FieldGTE(FieldLastLoginAt, v))
}

// LastLoginAtLT applies the LT predicate on the "last_login_at" field.
func LastLoginAtLT(v time.Time) predicate.GaiaCredential {
	return predicate.GaiaCredential(sql.FieldLT(FieldLastLoginAt, v))
}

// LastLoginAtLTE applies the LTE predicate on the "last_login_at" field.
func LastLoginAtLTE(v time.Time) predicate.GaiaCredential {
	return predicate.GaiaCredential(sql.FieldLTE(FieldLastLoginAt, v))
}

// LastLoginAtIsNil applies the IsNil predicate on the "last_login_at" field.
func LastLoginAtIsNil() predicate.GaiaCredential {
	return predicate.GaiaCredential(sql.FieldIsNull(FieldLastLoginAt))
}

// LastLoginAtNotNil applies the NotNil predicate on the "last_login_at" field.
func LastLoginAtNotNil() predicate.GaiaCredential {
	return predicate.GaiaCredential(sql.FieldNotNull(FieldLastLoginAt))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.GaiaCredential {
	return predicate.GaiaCredential(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.GaiaCredential {
	return predicate.GaiaCredential(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.GaiaCredential {
	return predicate.GaiaCredential(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.GaiaCredential {
	return predicate.GaiaCredential(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.GaiaCredential {
	return predicate.GaiaCredential(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.GaiaCredential {
	return predicate.GaiaCredential(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.GaiaCredential {
	return predicate.GaiaCredential(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.GaiaCredential {
	return predicate.GaiaCredential(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.GaiaCredential {
	return predicate.GaiaCredential(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.GaiaCredential {
	return predicate.GaiaCredential(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.GaiaCredential {
	return predicate.GaiaCredential(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.GaiaCredential {
	return predicate.GaiaCredential(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.GaiaCredential {
	return predicate.GaiaCredential(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.GaiaCredential {
	return predicate.GaiaCredential(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.GaiaCredential {
	return predicate.GaiaCredential(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.GaiaCredential {
	return predicate.GaiaCredential(sql.FieldLTE(FieldUpdatedAt, v))
}

// HasUser applies the HasEdge predicate on the "user" edge.
func HasUser() predicate.GaiaCredential {
	return predicate.GaiaCredential(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, UserTable, UserColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasUserWith applies the HasEdge predicate on the "user" edge with a given conditions (other predicates).
func HasUserWith(preds ...predicate.User) predicate.GaiaCredential {
	return predicate.GaiaCredential(func(s *sql.Selector) {
		step := newUserStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.GaiaCredential) predicate.GaiaCredential {
	return predicate.GaiaCredential(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.GaiaCredential) predicate.GaiaCredential {
	return predicate.GaiaCredential(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.GaiaCredential) predicate.GaiaCredential {
	return predicate.GaiaCredential(sql.NotPredicates(p))
}
