// Code generated by ent, DO NOT EDIT.

package gaiasession

import (
	"gaia-calendar/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.GaiaSession {
	return predicate.GaiaSession(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.GaiaSession {
	return predicate.GaiaSession(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.GaiaSession {
	return predicate.GaiaSession(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.GaiaSession {
	return predicate.GaiaSession(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.GaiaSession {
	return predicate.GaiaSession(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.GaiaSession {
	return predicate.GaiaSession(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.GaiaSession {
	return predicate.GaiaSession(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.GaiaSession {
	return predicate.GaiaSession(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.GaiaSession {
	return predicate.GaiaSession(sql.FieldLTE(FieldID, id))
}

// CompanyCode applies equality check predicate on the "company_code" field. It's identical to CompanyCodeEQ.
func CompanyCode(v string) predicate.GaiaSession {
	return predicate.GaiaSession(sql.FieldEQ(FieldCompanyCode, v))
}

// EncryptedPayload applies equality check predicate on the "encrypted_payload" field. It's identical to EncryptedPayloadEQ.
func EncryptedPayload(v string) predicate.GaiaSession {
	return predicate.GaiaSession(sql.FieldEQ(FieldEncryptedPayload, v))
}

// ExpiresAt applies equality check predicate on the "expires_at" field. It's identical to ExpiresAtEQ.
func ExpiresAt(v time.Time) predicate.GaiaSession {
	return predicate.GaiaSession(sql.FieldEQ(FieldExpiresAt, v))
}

// LastError applies equality check predicate on the "last_error" field. It's identical to LastErrorEQ.
func LastError(v string) predicate.GaiaSession {
	return predicate.GaiaSession(sql.FieldEQ(FieldLastError, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.GaiaSession {
	return predicate.GaiaSession(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.GaiaSession {
	return predicate.GaiaSession(sql.FieldEQ(FieldUpdatedAt, v))
}

// CompanyCodeEQ applies the EQ predicate on the "company_code" field.
func CompanyCodeEQ(v string) predicate.GaiaSession {
	return predicate.GaiaSession(sql.FieldEQ(FieldCompanyCode, v))
}

// CompanyCodeNEQ applies the NEQ predicate on the "company_code" field.
func CompanyCodeNEQ(v string) predicate.GaiaSession {
	return predicate.GaiaSession(sql.FieldNEQ(FieldCompanyCode, v))
}

// CompanyCodeIn applies the In predicate on the "company_code" field.
func CompanyCodeIn(vs ...string) predicate.GaiaSession {
	return predicate.GaiaSession(sql.FieldIn(FieldCompanyCode, vs...))
}

// CompanyCodeNotIn applies the NotIn predicate on the "company_code" field.
func CompanyCodeNotIn(vs ...string) predicate.GaiaSession {
	return predicate.GaiaSession(sql.FieldNotIn(FieldCompanyCode, vs...))
}

// CompanyCodeGT applies the GT predicate on the "company_code" field.
func CompanyCodeGT(v string) predicate.GaiaSession {
	return predicate.GaiaSession(sql.FieldGT(FieldCompanyCode, v))
}

// CompanyCodeGTE applies the GTE predicate on the "company_code" field.
func CompanyCodeGTE(v string) predicate.GaiaSession {
	return predicate.GaiaSession(sql.FieldGTE(FieldCompanyCode, v))
}

// CompanyCodeLT applies the LT predicate on the "company_code" field.
func CompanyCodeLT(v string) predicate.GaiaSession {
	return predicate.GaiaSession(sql.FieldLT(FieldCompanyCode, v))
}

// CompanyCodeLTE applies the LTE predicate on the "company_code" field.
func CompanyCodeLTE(v string) predicate.GaiaSession {
	return predicate.GaiaSession(sql.FieldLTE(FieldCompanyCode, v))
}

// CompanyCodeContains applies the Contains predicate on the "company_code" field.
func CompanyCodeContains(v string) predicate.GaiaSession {
	return predicate.GaiaSession(sql.FieldContains(FieldCompanyCode, v))
}

// CompanyCodeHasPrefix applies the HasPrefix predicate on the "company_code" field.
func CompanyCodeHasPrefix(v string) predicate.GaiaSession {
	return predicate.GaiaSession(sql.FieldHasPrefix(FieldCompanyCode, v))
}

// CompanyCodeHasSuffix applies the HasSuffix predicate on the "company_code" field.
func CompanyCodeHasSuffix(v string) predicate.GaiaSession {
	return predicate.GaiaSession(sql.FieldHasSuffix(FieldCompanyCode, v))
}

// CompanyCodeEqualFold applies the EqualFold predicate on the "company_code" field.
func CompanyCodeEqualFold(v string) predicate.GaiaSession {
	return predicate.GaiaSession(sql.FieldEqualFold(FieldCompanyCode, v))
}

// CompanyCodeContainsFold applies the ContainsFold predicate on the "company_code" field.
func CompanyCodeContainsFold(v string) predicate.GaiaSession {
	return predicate.GaiaSession(sql.FieldContainsFold(FieldCompanyCode, v))
}

// EncryptedPayloadEQ applies the EQ predicate on the "encrypted_payload" field.
func EncryptedPayloadEQ(v string) predicate.GaiaSession {
	return predicate.GaiaSession(sql.FieldEQ(FieldEncryptedPayload, v))
}

// EncryptedPayloadNEQ applies the NEQ predicate on the "encrypted_payload" field.
func EncryptedPayloadNEQ(v string) predicate.GaiaSession {
	return predicate.GaiaSession(sql.FieldNEQ(FieldEncryptedPayload, v))
}

// EncryptedPayloadIn applies the In predicate on the "encrypted_payload" field.
func EncryptedPayloadIn(vs ...string) predicate.GaiaSession {
	return predicate.GaiaSession(sql.FieldIn(FieldEncryptedPayload, vs...))
}

// EncryptedPayloadNotIn applies the NotIn predicate on the "encrypted_payload" field.
func EncryptedPayloadNotIn(vs ...string) predicate.GaiaSession {
	return predicate.GaiaSession(sql.FieldNotIn(FieldEncryptedPayload, vs...))
}

// EncryptedPayloadGT applies the GT predicate on the "encrypted_payload" field.
func EncryptedPayloadGT(v string) predicate.GaiaSession {
	return predicate.GaiaSession(sql.FieldGT(FieldEncryptedPayload, v))
}

// EncryptedPayloadGTE applies the GTE predicate on the "encrypted_payload" field.
func EncryptedPayloadGTE(v string) predicate.GaiaSession {
	return predicate.GaiaSession(sql.FieldGTE(FieldEncryptedPayload, v))
}

// EncryptedPayloadLT applies the LT predicate on the "encrypted_payload" field.
func EncryptedPayloadLT(v string) predicate.GaiaSession {
	return predicate.GaiaSession(sql.FieldLT(FieldEncryptedPayload, v))
}

// EncryptedPayloadLTE applies the LTE predicate on the "encrypted_payload" field.
func EncryptedPayloadLTE(v string) predicate.GaiaSession {
	return predicate.GaiaSession(sql.FieldLTE(FieldEncryptedPayload, v))
}

// EncryptedPayloadContains applies the Contains predicate on the "encrypted_payload" field.
func EncryptedPayloadContains(v string) predicate.GaiaSession {
	return predicate.GaiaSession(sql.FieldContains(FieldEncryptedPayload, v))
}

// EncryptedPayloadHasPrefix applies the HasPrefix predicate on the "encrypted_payload" field.
func EncryptedPayloadHasPrefix(v string) predicate.GaiaSession {
	return predicate.GaiaSession(sql.FieldHasPrefix(FieldEncryptedPayload, v))
}

// EncryptedPayloadHasSuffix applies the HasSuffix predicate on the "encrypted_payload" field.
func EncryptedPayloadHasSuffix(v string) predicate.GaiaSession {
	return predicate.GaiaSession(sql.FieldHasSuffix(FieldEncryptedPayload, v))
}

// EncryptedPayloadEqualFold applies the EqualFold predicate on the "encrypted_payload" field.
func EncryptedPayloadEqualFold(v string) predicate.GaiaSession {
	return predicate.GaiaSession(sql.FieldEqualFold(FieldEncryptedPayload, v))
}

// EncryptedPayloadContainsFold applies the ContainsFold predicate on the "encrypted_payload" field.
func EncryptedPayloadContainsFold(v string) predicate.GaiaSession {
	return predicate.GaiaSession(sql.FieldContainsFold(FieldEncryptedPayload, v))
}

// ExpiresAtEQ applies the EQ predicate on the "expires_at" field.
func ExpiresAtEQ(v time.Time) predicate.GaiaSession {
	return predicate.GaiaSession(sql.FieldEQ(FieldExpiresAt, v))
}

// ExpiresAtNEQ applies the NEQ predicate on the "expires_at" field.
func ExpiresAtNEQ(v time.Time) predicate.GaiaSession {
	return predicate.GaiaSession(sql.FieldNEQ(FieldExpiresAt, v))
}

// ExpiresAtIn applies the In predicate on the "expires_at" field.
func ExpiresAtIn(vs ...time.Time) predicate.GaiaSession {
	return predicate.GaiaSession(sql.FieldIn(FieldExpiresAt, vs...))
}

// ExpiresAtNotIn applies the NotIn predicate on the "expires_at" field.
func ExpiresAtNotIn(vs ...time.Time) predicate.GaiaSession {
	return predicate.GaiaSession(sql.FieldNotIn(FieldExpiresAt, vs...))
}

// ExpiresAtGT applies the GT predicate on the "expires_at" field.
func ExpiresAtGT(v time.Time) predicate.GaiaSession {
	return predicate.GaiaSession(sql.FieldGT(FieldExpiresAt, v))
}

// ExpiresAtGTE applies the GTE predicate on the "expires_at" field.
func ExpiresAtGTE(v time.Time) predicate.GaiaSession {
	return predicate.GaiaSession(sql.FieldGTE(FieldExpiresAt, v))
}

// ExpiresAtLT applies the LT predicate on the "expires_at" field.
func ExpiresAtLT(v time.Time) predicate.GaiaSession {
	return predicate.GaiaSession(sql.FieldLT(FieldExpiresAt, v))
}

// ExpiresAtLTE applies the LTE predicate on the "expires_at" field.
func ExpiresAtLTE(v time.Time) predicate.GaiaSession {
	return predicate.GaiaSession(sql.FieldLTE(FieldExpiresAt, v))
}

// ExpiresAtIsNil applies the IsNil predicate on the "expires_at" field.
func ExpiresAtIsNil() predicate.GaiaSession {
	return predicate.GaiaSession(sql.FieldIsNull(FieldExpiresAt))
}

// ExpiresAtNotNil applies the NotNil predicate on the "expires_at" field.
func ExpiresAtNotNil() predicate.GaiaSession {
	return predicate.GaiaSession(sql.FieldNotNull(FieldExpiresAt))
}

// LastErrorEQ applies the EQ predicate on the "last_error" field.
func LastErrorEQ(v string) predicate.GaiaSession {
	return predicate.GaiaSession(sql.FieldEQ(FieldLastError, v))
}

// LastErrorNEQ applies the NEQ predicate on the "last_error" field.
func LastErrorNEQ(v string) predicate.GaiaSession {
	return predicate.GaiaSession(sql.FieldNEQ(FieldLastError, v))
}

// LastErrorIn applies the In predicate on the "last_error" field.
func LastErrorIn(vs ...string) predicate.GaiaSession {
	return predicate.GaiaSession(sql.FieldIn(FieldLastError, vs...))
}

// LastErrorNotIn applies the NotIn predicate on the "last_error" field.
func LastErrorNotIn(vs ...string) predicate.GaiaSession {
	return predicate.GaiaSession(sql.FieldNotIn(FieldLastError, vs...))
}

// LastErrorGT applies the GT predicate on the "last_error" field.
func LastErrorGT(v string) predicate.GaiaSession {
	return predicate.GaiaSession(sql.FieldGT(FieldLastError, v))
}

// LastErrorGTE applies the GTE predicate on the "last_error" field.
func LastErrorGTE(v string) predicate.GaiaSession {
	return predicate.GaiaSession(sql.FieldGTE(FieldLastError, v))
}

// LastErrorLT applies the LT predicate on the "last_error" field.
func LastErrorLT(v string) predicate.GaiaSession {
	return predicate.GaiaSession(sql.FieldLT(FieldLastError, v))
}

// LastErrorLTE applies the LTE predicate on the "last_error" field.
func LastErrorLTE(v string) predicate.GaiaSession {
	return predicate.GaiaSession(sql.FieldLTE(FieldLastError, v))
}

// LastErrorContains applies the Contains predicate on the "last_error" field.
func LastErrorContains(v string) predicate.GaiaSession {
	return predicate.GaiaSession(sql.FieldContains(FieldLastError, v))
}

// LastErrorHasPrefix applies the HasPrefix predicate on the "last_error" field.
func LastErrorHasPrefix(v string) predicate.GaiaSession {
	return predicate.GaiaSession(sql.FieldHasPrefix(FieldLastError, v))
}

// LastErrorHasSuffix applies the HasSuffix predicate on the "last_error" field.
func LastErrorHasSuffix(v string) predicate.GaiaSession {
	return predicate.GaiaSession(sql.FieldHasSuffix(FieldLastError, v))
}

// LastErrorIsNil applies the IsNil predicate on the "last_error" field.
func LastErrorIsNil() predicate.GaiaSession {
	return predicate.GaiaSession(sql.FieldIsNull(FieldLastError))
}

// LastErrorNotNil applies the NotNil predicate on the "last_error" field.
func LastErrorNotNil() predicate.GaiaSession {
	return predicate.GaiaSession(sql.FieldNotNull(FieldLastError))
}

// LastErrorEqualFold applies the EqualFold predicate on the "last_error" field.
func LastErrorEqualFold(v string) predicate.GaiaSession {
	return predicate.GaiaSession(sql.FieldEqualFold(FieldLastError, v))
}

// LastErrorContainsFold applies the ContainsFold predicate on the "last_error" field.
func LastErrorContainsFold(v string) predicate.GaiaSession {
	return predicate.GaiaSession(sql.FieldContainsFold(FieldLastError, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.GaiaSession {
	return predicate.GaiaSession(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.GaiaSession {
	return predicate.GaiaSession(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.GaiaSession {
	return predicate.GaiaSession(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.GaiaSession {
	return predicate.GaiaSession(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.GaiaSession {
	return predicate.GaiaSession(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.GaiaSession {
	return predicate.GaiaSession(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.GaiaSession {
	return predicate.GaiaSession(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.GaiaSession {
	return predicate.GaiaSession(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.GaiaSession {
	return predicate.GaiaSession(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.GaiaSession {
	return predicate.GaiaSession(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.GaiaSession {
	return predicate.GaiaSession(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.GaiaSession {
	return predicate.GaiaSession(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.GaiaSession {
	return predicate.GaiaSession(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.GaiaSession {
	return predicate.GaiaSession(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.GaiaSession {
	return predicate.GaiaSession(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.GaiaSession {
	return predicate.GaiaSession(sql.FieldLTE(FieldUpdatedAt, v))
}

// HasUser applies the HasEdge predicate on the "user" edge.
func HasUser() predicate.GaiaSession {
	return predicate.GaiaSession(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, UserTable, UserColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasUserWith applies the HasEdge predicate on the "user" edge with a given conditions (other predicates).
func HasUserWith(preds ...predicate.User) predicate.GaiaSession {
	return predicate.GaiaSession(func(s *sql.Selector) {
		step := newUserStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.GaiaSession) predicate.GaiaSession {
	return predicate.GaiaSession(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.GaiaSession) predicate.GaiaSession {
	return predicate.GaiaSession(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.GaiaSession) predicate.GaiaSession {
	return predicate.GaiaSession(sql.NotPredicates(p))
}
