// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"gaia-calendar/ent/calendarrequestlog"
	"gaia-calendar/ent/calendarsubscription"
	"gaia-calendar/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// CalendarRequestLogUpdate is the builder for updating CalendarRequestLog entities.
type CalendarRequestLogUpdate struct {
	config
	hooks    []Hook
	mutation *CalendarRequestLogMutation
}

// Where appends a list predicates to the CalendarRequestLogUpdate builder.
func (_u *CalendarRequestLogUpdate) Where(ps ...predicate.CalendarRequestLog) *CalendarRequestLogUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetRequestedAt sets the "requested_at" field.
func (_u *CalendarRequestLogUpdate) SetRequestedAt(v time.Time) *CalendarRequestLogUpdate {
	_u.mutation.SetRequestedAt(v)
	return _u
}

// SetNillableRequestedAt sets the "requested_at" field if the given value is not nil.
func (_u *CalendarRequestLogUpdate) SetNillableRequestedAt(v *time.Time) *CalendarRequestLogUpdate {
	if v != nil {
		_u.SetRequestedAt(*v)
	}
	return _u
}

// SetUserAgent sets the "user_agent" field.
func (_u *CalendarRequestLogUpdate) SetUserAgent(v string) *CalendarRequestLogUpdate {
	_u.mutation.SetUserAgent(v)
	return _u
}

// SetNillableUserAgent sets the "user_agent" field if the given value is not nil.
func (_u *CalendarRequestLogUpdate) SetNillableUserAgent(v *string) *CalendarRequestLogUpdate {
	if v != nil {
		_u.SetUserAgent(*v)
	}
	return _u
}

// SetRemoteAddr sets the "remote_addr" field.
func (_u *CalendarRequestLogUpdate) SetRemoteAddr(v string) *CalendarRequestLogUpdate {
	_u.mutation.SetRemoteAddr(v)
	return _u
}

// SetNillableRemoteAddr sets the "remote_addr" field if the given value is not nil.
func (_u *CalendarRequestLogUpdate) SetNillableRemoteAddr(v *string) *CalendarRequestLogUpdate {
	if v != nil {
		_u.SetRemoteAddr(*v)
	}
	return _u
}

// SetPath sets the "path" field.
func (_u *CalendarRequestLogUpdate) SetPath(v string) *CalendarRequestLogUpdate {
	_u.mutation.SetPath(v)
	return _u
}

// SetNillablePath sets the "path" field if the given value is not nil.
func (_u *CalendarRequestLogUpdate) SetNillablePath(v *string) *CalendarRequestLogUpdate {
	if v != nil {
		_u.SetPath(*v)
	}
	return _u
}

// SetSubscriptionID sets the "subscription" edge to the CalendarSubscription entity by ID.
func (_u *CalendarRequestLogUpdate) SetSubscriptionID(id int) *CalendarRequestLogUpdate {
	_u.mutation.SetSubscriptionID(id)
	return _u
}

// SetSubscription sets the "subscription" edge to the CalendarSubscription entity.
func (_u *CalendarRequestLogUpdate) SetSubscription(v *CalendarSubscription) *CalendarRequestLogUpdate {
	return _u.SetSubscriptionID(v.ID)
}

// Mutation returns the CalendarRequestLogMutation object of the builder.
func (_u *CalendarRequestLogUpdate) Mutation() *CalendarRequestLogMutation {
	return _u.mutation
}

// ClearSubscription clears the "subscription" edge to the CalendarSubscription entity.
func (_u *CalendarRequestLogUpdate) ClearSubscription() *CalendarRequestLogUpdate {
	_u.mutation.ClearSubscription()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *CalendarRequestLogUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *CalendarRequestLogUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *CalendarRequestLogUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *CalendarRequestLogUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *CalendarRequestLogUpdate) check() error {
	if _u.mutation.SubscriptionCleared() && len(_u.mutation.SubscriptionIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "CalendarRequestLog.subscription"`)
	}
	return nil
}

func (_u *CalendarRequestLogUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(calendarrequestlog.Table, calendarrequestlog.Columns, sqlgraph.NewFieldSpec(calendarrequestlog.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.RequestedAt(); ok {
		_spec.SetField(calendarrequestlog.FieldRequestedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.UserAgent(); ok {
		_spec.SetField(calendarrequestlog.FieldUserAgent, field.TypeString, value)
	}
	if value, ok := _u.mutation.RemoteAddr(); ok {
		_spec.SetField(calendarrequestlog.FieldRemoteAddr, field.TypeString, value)
	}
	if value, ok := _u.mutation.Path(); ok {
		_spec.SetField(calendarrequestlog.FieldPath, field.TypeString, value)
	}
	if _u.mutation.SubscriptionCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   calendarrequestlog.SubscriptionTable,
			Columns: []string{calendarrequestlog.SubscriptionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(calendarsubscription.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.SubscriptionIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   calendarrequestlog.SubscriptionTable,
			Columns: []string{calendarrequestlog.SubscriptionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(calendarsubscription.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{calendarrequestlog.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// CalendarRequestLogUpdateOne is the builder for updating a single CalendarRequestLog entity.
type CalendarRequestLogUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *CalendarRequestLogMutation
}

// SetRequestedAt sets the "requested_at" field.
func (_u *CalendarRequestLogUpdateOne) SetRequestedAt(v time.Time) *CalendarRequestLogUpdateOne {
	_u.mutation.SetRequestedAt(v)
	return _u
}

// SetNillableRequestedAt sets the "requested_at" field if the given value is not nil.
func (_u *CalendarRequestLogUpdateOne) SetNillableRequestedAt(v *time.Time) *CalendarRequestLogUpdateOne {
	if v != nil {
		_u.SetRequestedAt(*v)
	}
	return _u
}

// SetUserAgent sets the "user_agent" field.
func (_u *CalendarRequestLogUpdateOne) SetUserAgent(v string) *CalendarRequestLogUpdateOne {
	_u.mutation.SetUserAgent(v)
	return _u
}

// SetNillableUserAgent sets the "user_agent" field if the given value is not nil.
func (_u *CalendarRequestLogUpdateOne) SetNillableUserAgent(v *string) *CalendarRequestLogUpdateOne {
	if v != nil {
		_u.SetUserAgent(*v)
	}
	return _u
}

// SetRemoteAddr sets the "remote_addr" field.
func (_u *CalendarRequestLogUpdateOne) SetRemoteAddr(v string) *CalendarRequestLogUpdateOne {
	_u.mutation.SetRemoteAddr(v)
	return _u
}

// SetNillableRemoteAddr sets the "remote_addr" field if the given value is not nil.
func (_u *CalendarRequestLogUpdateOne) SetNillableRemoteAddr(v *string) *CalendarRequestLogUpdateOne {
	if v != nil {
		_u.SetRemoteAddr(*v)
	}
	return _u
}

// SetPath sets the "path" field.
func (_u *CalendarRequestLogUpdateOne) SetPath(v string) *CalendarRequestLogUpdateOne {
	_u.mutation.SetPath(v)
	return _u
}

// SetNillablePath sets the "path" field if the given value is not nil.
func (_u *CalendarRequestLogUpdateOne) SetNillablePath(v *string) *CalendarRequestLogUpdateOne {
	if v != nil {
		_u.SetPath(*v)
	}
	return _u
}

// SetSubscriptionID sets the "subscription" edge to the CalendarSubscription entity by ID.
func (_u *CalendarRequestLogUpdateOne) SetSubscriptionID(id int) *CalendarRequestLogUpdateOne {
	_u.mutation.SetSubscriptionID(id)
	return _u
}

// SetSubscription sets the "subscription" edge to the CalendarSubscription entity.
func (_u *CalendarRequestLogUpdateOne) SetSubscription(v *CalendarSubscription) *CalendarRequestLogUpdateOne {
	return _u.SetSubscriptionID(v.ID)
}

// Mutation returns the CalendarRequestLogMutation object of the builder.
func (_u *CalendarRequestLogUpdateOne) Mutation() *CalendarRequestLogMutation {
	return _u.mutation
}

// ClearSubscription clears the "subscription" edge to the CalendarSubscription entity.
func (_u *CalendarRequestLogUpdateOne) ClearSubscription() *CalendarRequestLogUpdateOne {
	_u.mutation.ClearSubscription()
	return _u
}

// Where appends a list predicates to the CalendarRequestLogUpdate builder.
func (_u *CalendarRequestLogUpdateOne) Where(ps ...predicate.CalendarRequestLog) *CalendarRequestLogUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *CalendarRequestLogUpdateOne) Select(field string, fields ...string) *CalendarRequestLogUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated CalendarRequestLog entity.
func (_u *CalendarRequestLogUpdateOne) Save(ctx context.Context) (*CalendarRequestLog, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *CalendarRequestLogUpdateOne) SaveX(ctx context.Context) *CalendarRequestLog {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *CalendarRequestLogUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *CalendarRequestLogUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *CalendarRequestLogUpdateOne) check() error {
	if _u.mutation.SubscriptionCleared() && len(_u.mutation.SubscriptionIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "CalendarRequestLog.subscription"`)
	}
	return nil
}

func (_u *CalendarRequestLogUpdateOne) sqlSave(ctx context.Context) (_node *CalendarRequestLog, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(calendarrequestlog.Table, calendarrequestlog.Columns, sqlgraph.NewFieldSpec(calendarrequestlog.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "CalendarRequestLog.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, calendarrequestlog.FieldID)
		for _, f := range fields {
			if !calendarrequestlog.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != calendarrequestlog.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.RequestedAt(); ok {
		_spec.SetField(calendarrequestlog.FieldRequestedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.UserAgent(); ok {
		_spec.SetField(calendarrequestlog.FieldUserAgent, field.TypeString, value)
	}
	if value, ok := _u.mutation.RemoteAddr(); ok {
		_spec.SetField(calendarrequestlog.FieldRemoteAddr, field.TypeString, value)
	}
	if value, ok := _u.mutation.Path(); ok {
		_spec.SetField(calendarrequestlog.FieldPath, field.TypeString, value)
	}
	if _u.mutation.SubscriptionCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   calendarrequestlog.SubscriptionTable,
			Columns: []string{calendarrequestlog.SubscriptionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(calendarsubscription.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.SubscriptionIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   calendarrequestlog.SubscriptionTable,
			Columns: []string{calendarrequestlog.SubscriptionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(calendarsubscription.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &CalendarRequestLog{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{calendarrequestlog.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
