// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"gaia-calendar/ent/calendarrequestlog"
	"gaia-calendar/ent/calendarsubscription"
	"gaia-calendar/ent/user"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// CalendarSubscriptionCreate is the builder for creating a CalendarSubscription entity.
type CalendarSubscriptionCreate struct {
	config
	mutation *CalendarSubscriptionMutation
	hooks    []Hook
}

// SetTokenHash sets the "token_hash" field.
func (_c *CalendarSubscriptionCreate) SetTokenHash(v string) *CalendarSubscriptionCreate {
	_c.mutation.SetTokenHash(v)
	return _c
}

// SetEncryptedToken sets the "encrypted_token" field.
func (_c *CalendarSubscriptionCreate) SetEncryptedToken(v string) *CalendarSubscriptionCreate {
	_c.mutation.SetEncryptedToken(v)
	return _c
}

// SetEnabled sets the "enabled" field.
func (_c *CalendarSubscriptionCreate) SetEnabled(v bool) *CalendarSubscriptionCreate {
	_c.mutation.SetEnabled(v)
	return _c
}

// SetNillableEnabled sets the "enabled" field if the given value is not nil.
func (_c *CalendarSubscriptionCreate) SetNillableEnabled(v *bool) *CalendarSubscriptionCreate {
	if v != nil {
		_c.SetEnabled(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *CalendarSubscriptionCreate) SetCreatedAt(v time.Time) *CalendarSubscriptionCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *CalendarSubscriptionCreate) SetNillableCreatedAt(v *time.Time) *CalendarSubscriptionCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *CalendarSubscriptionCreate) SetUpdatedAt(v time.Time) *CalendarSubscriptionCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *CalendarSubscriptionCreate) SetNillableUpdatedAt(v *time.Time) *CalendarSubscriptionCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetUserID sets the "user" edge to the User entity by ID.
func (_c *CalendarSubscriptionCreate) SetUserID(id int) *CalendarSubscriptionCreate {
	_c.mutation.SetUserID(id)
	return _c
}

// SetUser sets the "user" edge to the User entity.
func (_c *CalendarSubscriptionCreate) SetUser(v *User) *CalendarSubscriptionCreate {
	return _c.SetUserID(v.ID)
}

// AddRequestLogIDs adds the "request_logs" edge to the CalendarRequestLog entity by IDs.
func (_c *CalendarSubscriptionCreate) AddRequestLogIDs(ids ...int) *CalendarSubscriptionCreate {
	_c.mutation.AddRequestLogIDs(ids...)
	return _c
}

// AddRequestLogs adds the "request_logs" edges to the CalendarRequestLog entity.
func (_c *CalendarSubscriptionCreate) AddRequestLogs(v ...*CalendarRequestLog) *CalendarSubscriptionCreate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddRequestLogIDs(ids...)
}

// Mutation returns the CalendarSubscriptionMutation object of the builder.
func (_c *CalendarSubscriptionCreate) Mutation() *CalendarSubscriptionMutation {
	return _c.mutation
}

// Save creates the CalendarSubscription in the database.
func (_c *CalendarSubscriptionCreate) Save(ctx context.Context) (*CalendarSubscription, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *CalendarSubscriptionCreate) SaveX(ctx context.Context) *CalendarSubscription {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *CalendarSubscriptionCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *CalendarSubscriptionCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *CalendarSubscriptionCreate) defaults() {
	if _, ok := _c.mutation.Enabled(); !ok {
		v := calendarsubscription.DefaultEnabled
		_c.mutation.SetEnabled(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := calendarsubscription.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := calendarsubscription.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *CalendarSubscriptionCreate) check() error {
	if _, ok := _c.mutation.TokenHash(); !ok {
		return &ValidationError{Name: "token_hash", err: errors.New(`ent: missing required field "CalendarSubscription.token_hash"`)}
	}
	if _, ok := _c.mutation.EncryptedToken(); !ok {
		return &ValidationError{Name: "encrypted_token", err: errors.New(`ent: missing required field "CalendarSubscription.encrypted_token"`)}
	}
	if _, ok := _c.mutation.Enabled(); !ok {
		return &ValidationError{Name: "enabled", err: errors.New(`ent: missing required field "CalendarSubscription.enabled"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "CalendarSubscription.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "CalendarSubscription.updated_at"`)}
	}
	if len(_c.mutation.UserIDs()) == 0 {
		return &ValidationError{Name: "user", err: errors.New(`ent: missing required edge "CalendarSubscription.user"`)}
	}
	return nil
}

func (_c *CalendarSubscriptionCreate) sqlSave(ctx context.Context) (*CalendarSubscription, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *CalendarSubscriptionCreate) createSpec() (*CalendarSubscription, *sqlgraph.CreateSpec) {
	var (
		_node = &CalendarSubscription{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(calendarsubscription.Table, sqlgraph.NewFieldSpec(calendarsubscription.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.TokenHash(); ok {
		_spec.SetField(calendarsubscription.FieldTokenHash, field.TypeString, value)
		_node.TokenHash = value
	}
	if value, ok := _c.mutation.EncryptedToken(); ok {
		_spec.SetField(calendarsubscription.FieldEncryptedToken, field.TypeString, value)
		_node.EncryptedToken = value
	}
	if value, ok := _c.mutation.Enabled(); ok {
		_spec.SetField(calendarsubscription.FieldEnabled, field.TypeBool, value)
		_node.Enabled = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(calendarsubscription.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(calendarsubscription.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if nodes := _c.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   calendarsubscription.UserTable,
			Columns: []string{calendarsubscription.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.user_calendar_subscriptions = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.RequestLogsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   calendarsubscription.RequestLogsTable,
			Columns: []string{calendarsubscription.RequestLogsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(calendarrequestlog.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// CalendarSubscriptionCreateBulk is the builder for creating many CalendarSubscription entities in bulk.
type CalendarSubscriptionCreateBulk struct {
	config
	err      error
	builders []*CalendarSubscriptionCreate
}

// Save creates the CalendarSubscription entities in the database.
func (_c *CalendarSubscriptionCreateBulk) Save(ctx context.Context) ([]*CalendarSubscription, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*CalendarSubscription, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*CalendarSubscriptionMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *CalendarSubscriptionCreateBulk) SaveX(ctx context.Context) []*CalendarSubscription {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *CalendarSubscriptionCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *CalendarSubscriptionCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
