// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"gaia-calendar/ent/calendarsubscription"
	"gaia-calendar/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// CalendarSubscriptionDelete is the builder for deleting a CalendarSubscription entity.
type CalendarSubscriptionDelete struct {
	config
	hooks    []Hook
	mutation *CalendarSubscriptionMutation
}

// Where appends a list predicates to the CalendarSubscriptionDelete builder.
func (_d *CalendarSubscriptionDelete) Where(ps ...predicate.CalendarSubscription) *CalendarSubscriptionDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *CalendarSubscriptionDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *CalendarSubscriptionDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *CalendarSubscriptionDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(calendarsubscription.Table, sqlgraph.NewFieldSpec(calendarsubscription.FieldID, field.TypeInt))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// CalendarSubscriptionDeleteOne is the builder for deleting a single CalendarSubscription entity.
type CalendarSubscriptionDeleteOne struct {
	_d *CalendarSubscriptionDelete
}

// Where appends a list predicates to the CalendarSubscriptionDelete builder.
func (_d *CalendarSubscriptionDeleteOne) Where(ps ...predicate.CalendarSubscription) *CalendarSubscriptionDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *CalendarSubscriptionDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{calendarsubscription.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *CalendarSubscriptionDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
