// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"gaia-calendar/ent/calendarrequestlog"
	"gaia-calendar/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// CalendarRequestLogDelete is the builder for deleting a CalendarRequestLog entity.
type CalendarRequestLogDelete struct {
	config
	hooks    []Hook
	mutation *CalendarRequestLogMutation
}

// Where appends a list predicates to the CalendarRequestLogDelete builder.
func (_d *CalendarRequestLogDelete) Where(ps ...predicate.CalendarRequestLog) *CalendarRequestLogDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *CalendarRequestLogDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *CalendarRequestLogDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *CalendarRequestLogDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(calendarrequestlog.Table, sqlgraph.NewFieldSpec(calendarrequestlog.FieldID, field.TypeInt))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// CalendarRequestLogDeleteOne is the builder for deleting a single CalendarRequestLog entity.
type CalendarRequestLogDeleteOne struct {
	_d *CalendarRequestLogDelete
}

// Where appends a list predicates to the CalendarRequestLogDelete builder.
func (_d *CalendarRequestLogDeleteOne) Where(ps ...predicate.CalendarRequestLog) *CalendarRequestLogDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *CalendarRequestLogDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{calendarrequestlog.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *CalendarRequestLogDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
