// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"gaia-calendar/ent/calendarrequestlog"
	"gaia-calendar/ent/calendarsubscription"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// CalendarRequestLog is the model entity for the CalendarRequestLog schema.
type CalendarRequestLog struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// RequestedAt holds the value of the "requested_at" field.
	RequestedAt time.Time `json:"requested_at,omitempty"`
	// UserAgent holds the value of the "user_agent" field.
	UserAgent string `json:"user_agent,omitempty"`
	// RemoteAddr holds the value of the "remote_addr" field.
	RemoteAddr string `json:"remote_addr,omitempty"`
	// Path holds the value of the "path" field.
	Path string `json:"path,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the CalendarRequestLogQuery when eager-loading is set.
	Edges                              CalendarRequestLogEdges `json:"edges"`
	calendar_subscription_request_logs *int
	selectValues                       sql.SelectValues
}

// CalendarRequestLogEdges holds the relations/edges for other nodes in the graph.
type CalendarRequestLogEdges struct {
	// Subscription holds the value of the subscription edge.
	Subscription *CalendarSubscription `json:"subscription,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// SubscriptionOrErr returns the Subscription value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e CalendarRequestLogEdges) SubscriptionOrErr() (*CalendarSubscription, error) {
	if e.Subscription != nil {
		return e.Subscription, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: calendarsubscription.Label}
	}
	return nil, &NotLoadedError{edge: "subscription"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*CalendarRequestLog) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case calendarrequestlog.FieldID:
			values[i] = new(sql.NullInt64)
		case calendarrequestlog.FieldUserAgent, calendarrequestlog.FieldRemoteAddr, calendarrequestlog.FieldPath:
			values[i] = new(sql.NullString)
		case calendarrequestlog.FieldRequestedAt:
			values[i] = new(sql.NullTime)
		case calendarrequestlog.ForeignKeys[0]: // calendar_subscription_request_logs
			values[i] = new(sql.NullInt64)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the CalendarRequestLog fields.
func (_m *CalendarRequestLog) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case calendarrequestlog.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case calendarrequestlog.FieldRequestedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field requested_at", values[i])
			} else if value.Valid {
				_m.RequestedAt = value.Time
			}
		case calendarrequestlog.FieldUserAgent:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field user_agent", values[i])
			} else if value.Valid {
				_m.UserAgent = value.String
			}
		case calendarrequestlog.FieldRemoteAddr:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field remote_addr", values[i])
			} else if value.Valid {
				_m.RemoteAddr = value.String
			}
		case calendarrequestlog.FieldPath:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field path", values[i])
			} else if value.Valid {
				_m.Path = value.String
			}
		case calendarrequestlog.ForeignKeys[0]:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for edge-field calendar_subscription_request_logs", value)
			} else if value.Valid {
				_m.calendar_subscription_request_logs = new(int)
				*_m.calendar_subscription_request_logs = int(value.Int64)
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the CalendarRequestLog.
// This includes values selected through modifiers, order, etc.
func (_m *CalendarRequestLog) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QuerySubscription queries the "subscription" edge of the CalendarRequestLog entity.
func (_m *CalendarRequestLog) QuerySubscription() *CalendarSubscriptionQuery {
	return NewCalendarRequestLogClient(_m.config).QuerySubscription(_m)
}

// Update returns a builder for updating this CalendarRequestLog.
// Note that you need to call CalendarRequestLog.Unwrap() before calling this method if this CalendarRequestLog
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *CalendarRequestLog) Update() *CalendarRequestLogUpdateOne {
	return NewCalendarRequestLogClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the CalendarRequestLog entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *CalendarRequestLog) Unwrap() *CalendarRequestLog {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: CalendarRequestLog is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *CalendarRequestLog) String() string {
	var builder strings.Builder
	builder.WriteString("CalendarRequestLog(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("requested_at=")
	builder.WriteString(_m.RequestedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("user_agent=")
	builder.WriteString(_m.UserAgent)
	builder.WriteString(", ")
	builder.WriteString("remote_addr=")
	builder.WriteString(_m.RemoteAddr)
	builder.WriteString(", ")
	builder.WriteString("path=")
	builder.WriteString(_m.Path)
	builder.WriteByte(')')
	return builder.String()
}

// CalendarRequestLogs is a parsable slice of CalendarRequestLog.
type CalendarRequestLogs []*CalendarRequestLog
