// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"log"
	"reflect"

	"gaia-calendar/ent/migrate"

	"gaia-calendar/ent/appsession"
	"gaia-calendar/ent/calendarrequestlog"
	"gaia-calendar/ent/calendarsubscription"
	"gaia-calendar/ent/emailverificationcode"
	"gaia-calendar/ent/gaiacredential"
	"gaia-calendar/ent/gaiasession"
	"gaia-calendar/ent/passwordresettoken"
	"gaia-calendar/ent/scheduleentry"
	"gaia-calendar/ent/schedulesyncrun"
	"gaia-calendar/ent/user"

	"entgo.io/ent"
	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

// Client is the client that holds all ent builders.
type Client struct {
	config
	// Schema is the client for creating, migrating and dropping schema.
	Schema *migrate.Schema
	// AppSession is the client for interacting with the AppSession builders.
	AppSession *AppSessionClient
	// CalendarRequestLog is the client for interacting with the CalendarRequestLog builders.
	CalendarRequestLog *CalendarRequestLogClient
	// CalendarSubscription is the client for interacting with the CalendarSubscription builders.
	CalendarSubscription *CalendarSubscriptionClient
	// EmailVerificationCode is the client for interacting with the EmailVerificationCode builders.
	EmailVerificationCode *EmailVerificationCodeClient
	// GaiaCredential is the client for interacting with the GaiaCredential builders.
	GaiaCredential *GaiaCredentialClient
	// GaiaSession is the client for interacting with the GaiaSession builders.
	GaiaSession *GaiaSessionClient
	// PasswordResetToken is the client for interacting with the PasswordResetToken builders.
	PasswordResetToken *PasswordResetTokenClient
	// ScheduleEntry is the client for interacting with the ScheduleEntry builders.
	ScheduleEntry *ScheduleEntryClient
	// ScheduleSyncRun is the client for interacting with the ScheduleSyncRun builders.
	ScheduleSyncRun *ScheduleSyncRunClient
	// User is the client for interacting with the User builders.
	User *UserClient
}

// NewClient creates a new client configured with the given options.
func NewClient(opts ...Option) *Client {
	client := &Client{config: newConfig(opts...)}
	client.init()
	return client
}

func (c *Client) init() {
	c.Schema = migrate.NewSchema(c.driver)
	c.AppSession = NewAppSessionClient(c.config)
	c.CalendarRequestLog = NewCalendarRequestLogClient(c.config)
	c.CalendarSubscription = NewCalendarSubscriptionClient(c.config)
	c.EmailVerificationCode = NewEmailVerificationCodeClient(c.config)
	c.GaiaCredential = NewGaiaCredentialClient(c.config)
	c.GaiaSession = NewGaiaSessionClient(c.config)
	c.PasswordResetToken = NewPasswordResetTokenClient(c.config)
	c.ScheduleEntry = NewScheduleEntryClient(c.config)
	c.ScheduleSyncRun = NewScheduleSyncRunClient(c.config)
	c.User = NewUserClient(c.config)
}

type (
	// config is the configuration for the client and its builder.
	config struct {
		// driver used for executing database requests.
		driver dialect.Driver
		// debug enable a debug logging.
		debug bool
		// log used for logging on debug mode.
		log func(...any)
		// hooks to execute on mutations.
		hooks *hooks
		// interceptors to execute on queries.
		inters *inters
	}
	// Option function to configure the client.
	Option func(*config)
)

// newConfig creates a new config for the client.
func newConfig(opts ...Option) config {
	cfg := config{log: log.Println, hooks: &hooks{}, inters: &inters{}}
	cfg.options(opts...)
	return cfg
}

// options applies the options on the config object.
func (c *config) options(opts ...Option) {
	for _, opt := range opts {
		opt(c)
	}
	if c.debug {
		c.driver = dialect.Debug(c.driver, c.log)
	}
}

// Debug enables debug logging on the ent.Driver.
func Debug() Option {
	return func(c *config) {
		c.debug = true
	}
}

// Log sets the logging function for debug mode.
func Log(fn func(...any)) Option {
	return func(c *config) {
		c.log = fn
	}
}

// Driver configures the client driver.
func Driver(driver dialect.Driver) Option {
	return func(c *config) {
		c.driver = driver
	}
}

// Open opens a database/sql.DB specified by the driver name and
// the data source name, and returns a new client attached to it.
// Optional parameters can be added for configuring the client.
func Open(driverName, dataSourceName string, options ...Option) (*Client, error) {
	switch driverName {
	case dialect.MySQL, dialect.Postgres, dialect.SQLite:
		drv, err := sql.Open(driverName, dataSourceName)
		if err != nil {
			return nil, err
		}
		return NewClient(append(options, Driver(drv))...), nil
	default:
		return nil, fmt.Errorf("unsupported driver: %q", driverName)
	}
}

// ErrTxStarted is returned when trying to start a new transaction from a transactional client.
var ErrTxStarted = errors.New("ent: cannot start a transaction within a transaction")

// Tx returns a new transactional client. The provided context
// is used until the transaction is committed or rolled back.
func (c *Client) Tx(ctx context.Context) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, ErrTxStarted
	}
	tx, err := newTx(ctx, c.driver)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = tx
	return &Tx{
		ctx:                   ctx,
		config:                cfg,
		AppSession:            NewAppSessionClient(cfg),
		CalendarRequestLog:    NewCalendarRequestLogClient(cfg),
		CalendarSubscription:  NewCalendarSubscriptionClient(cfg),
		EmailVerificationCode: NewEmailVerificationCodeClient(cfg),
		GaiaCredential:        NewGaiaCredentialClient(cfg),
		GaiaSession:           NewGaiaSessionClient(cfg),
		PasswordResetToken:    NewPasswordResetTokenClient(cfg),
		ScheduleEntry:         NewScheduleEntryClient(cfg),
		ScheduleSyncRun:       NewScheduleSyncRunClient(cfg),
		User:                  NewUserClient(cfg),
	}, nil
}

// BeginTx returns a transactional client with specified options.
func (c *Client) BeginTx(ctx context.Context, opts *sql.TxOptions) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, errors.New("ent: cannot start a transaction within a transaction")
	}
	tx, err := c.driver.(interface {
		BeginTx(context.Context, *sql.TxOptions) (dialect.Tx, error)
	}).BeginTx(ctx, opts)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = &txDriver{tx: tx, drv: c.driver}
	return &Tx{
		ctx:                   ctx,
		config:                cfg,
		AppSession:            NewAppSessionClient(cfg),
		CalendarRequestLog:    NewCalendarRequestLogClient(cfg),
		CalendarSubscription:  NewCalendarSubscriptionClient(cfg),
		EmailVerificationCode: NewEmailVerificationCodeClient(cfg),
		GaiaCredential:        NewGaiaCredentialClient(cfg),
		GaiaSession:           NewGaiaSessionClient(cfg),
		PasswordResetToken:    NewPasswordResetTokenClient(cfg),
		ScheduleEntry:         NewScheduleEntryClient(cfg),
		ScheduleSyncRun:       NewScheduleSyncRunClient(cfg),
		User:                  NewUserClient(cfg),
	}, nil
}

// Debug returns a new debug-client. It's used to get verbose logging on specific operations.
//
//	client.Debug().
//		AppSession.
//		Query().
//		Count(ctx)
func (c *Client) Debug() *Client {
	if c.debug {
		return c
	}
	cfg := c.config
	cfg.driver = dialect.Debug(c.driver, c.log)
	client := &Client{config: cfg}
	client.init()
	return client
}

// Close closes the database connection and prevents new queries from starting.
func (c *Client) Close() error {
	return c.driver.Close()
}

// Use adds the mutation hooks to all the entity clients.
// In order to add hooks to a specific client, call: `client.Node.Use(...)`.
func (c *Client) Use(hooks ...Hook) {
	for _, n := range []interface{ Use(...Hook) }{
		c.AppSession, c.CalendarRequestLog, c.CalendarSubscription,
		c.EmailVerificationCode, c.GaiaCredential, c.GaiaSession, c.PasswordResetToken,
		c.ScheduleEntry, c.ScheduleSyncRun, c.User,
	} {
		n.Use(hooks...)
	}
}

// Intercept adds the query interceptors to all the entity clients.
// In order to add interceptors to a specific client, call: `client.Node.Intercept(...)`.
func (c *Client) Intercept(interceptors ...Interceptor) {
	for _, n := range []interface{ Intercept(...Interceptor) }{
		c.AppSession, c.CalendarRequestLog, c.CalendarSubscription,
		c.EmailVerificationCode, c.GaiaCredential, c.GaiaSession, c.PasswordResetToken,
		c.ScheduleEntry, c.ScheduleSyncRun, c.User,
	} {
		n.Intercept(interceptors...)
	}
}

// Mutate implements the ent.Mutator interface.
func (c *Client) Mutate(ctx context.Context, m Mutation) (Value, error) {
	switch m := m.(type) {
	case *AppSessionMutation:
		return c.AppSession.mutate(ctx, m)
	case *CalendarRequestLogMutation:
		return c.CalendarRequestLog.mutate(ctx, m)
	case *CalendarSubscriptionMutation:
		return c.CalendarSubscription.mutate(ctx, m)
	case *EmailVerificationCodeMutation:
		return c.EmailVerificationCode.mutate(ctx, m)
	case *GaiaCredentialMutation:
		return c.GaiaCredential.mutate(ctx, m)
	case *GaiaSessionMutation:
		return c.GaiaSession.mutate(ctx, m)
	case *PasswordResetTokenMutation:
		return c.PasswordResetToken.mutate(ctx, m)
	case *ScheduleEntryMutation:
		return c.ScheduleEntry.mutate(ctx, m)
	case *ScheduleSyncRunMutation:
		return c.ScheduleSyncRun.mutate(ctx, m)
	case *UserMutation:
		return c.User.mutate(ctx, m)
	default:
		return nil, fmt.Errorf("ent: unknown mutation type %T", m)
	}
}

// AppSessionClient is a client for the AppSession schema.
type AppSessionClient struct {
	config
}

// NewAppSessionClient returns a client for the AppSession from the given config.
func NewAppSessionClient(c config) *AppSessionClient {
	return &AppSessionClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `appsession.Hooks(f(g(h())))`.
func (c *AppSessionClient) Use(hooks ...Hook) {
	c.hooks.AppSession = append(c.hooks.AppSession, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `appsession.Intercept(f(g(h())))`.
func (c *AppSessionClient) Intercept(interceptors ...Interceptor) {
	c.inters.AppSession = append(c.inters.AppSession, interceptors...)
}

// Create returns a builder for creating a AppSession entity.
func (c *AppSessionClient) Create() *AppSessionCreate {
	mutation := newAppSessionMutation(c.config, OpCreate)
	return &AppSessionCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of AppSession entities.
func (c *AppSessionClient) CreateBulk(builders ...*AppSessionCreate) *AppSessionCreateBulk {
	return &AppSessionCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *AppSessionClient) MapCreateBulk(slice any, setFunc func(*AppSessionCreate, int)) *AppSessionCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &AppSessionCreateBulk{err: fmt.Errorf("calling to AppSessionClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*AppSessionCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &AppSessionCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for AppSession.
func (c *AppSessionClient) Update() *AppSessionUpdate {
	mutation := newAppSessionMutation(c.config, OpUpdate)
	return &AppSessionUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *AppSessionClient) UpdateOne(_m *AppSession) *AppSessionUpdateOne {
	mutation := newAppSessionMutation(c.config, OpUpdateOne, withAppSession(_m))
	return &AppSessionUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *AppSessionClient) UpdateOneID(id int) *AppSessionUpdateOne {
	mutation := newAppSessionMutation(c.config, OpUpdateOne, withAppSessionID(id))
	return &AppSessionUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for AppSession.
func (c *AppSessionClient) Delete() *AppSessionDelete {
	mutation := newAppSessionMutation(c.config, OpDelete)
	return &AppSessionDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *AppSessionClient) DeleteOne(_m *AppSession) *AppSessionDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *AppSessionClient) DeleteOneID(id int) *AppSessionDeleteOne {
	builder := c.Delete().Where(appsession.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &AppSessionDeleteOne{builder}
}

// Query returns a query builder for AppSession.
func (c *AppSessionClient) Query() *AppSessionQuery {
	return &AppSessionQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeAppSession},
		inters: c.Interceptors(),
	}
}

// Get returns a AppSession entity by its id.
func (c *AppSessionClient) Get(ctx context.Context, id int) (*AppSession, error) {
	return c.Query().Where(appsession.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *AppSessionClient) GetX(ctx context.Context, id int) *AppSession {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryUser queries the user edge of a AppSession.
func (c *AppSessionClient) QueryUser(_m *AppSession) *UserQuery {
	query := (&UserClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(appsession.Table, appsession.FieldID, id),
			sqlgraph.To(user.Table, user.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, appsession.UserTable, appsession.UserColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *AppSessionClient) Hooks() []Hook {
	return c.hooks.AppSession
}

// Interceptors returns the client interceptors.
func (c *AppSessionClient) Interceptors() []Interceptor {
	return c.inters.AppSession
}

func (c *AppSessionClient) mutate(ctx context.Context, m *AppSessionMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&AppSessionCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&AppSessionUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&AppSessionUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&AppSessionDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown AppSession mutation op: %q", m.Op())
	}
}

// CalendarRequestLogClient is a client for the CalendarRequestLog schema.
type CalendarRequestLogClient struct {
	config
}

// NewCalendarRequestLogClient returns a client for the CalendarRequestLog from the given config.
func NewCalendarRequestLogClient(c config) *CalendarRequestLogClient {
	return &CalendarRequestLogClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `calendarrequestlog.Hooks(f(g(h())))`.
func (c *CalendarRequestLogClient) Use(hooks ...Hook) {
	c.hooks.CalendarRequestLog = append(c.hooks.CalendarRequestLog, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `calendarrequestlog.Intercept(f(g(h())))`.
func (c *CalendarRequestLogClient) Intercept(interceptors ...Interceptor) {
	c.inters.CalendarRequestLog = append(c.inters.CalendarRequestLog, interceptors...)
}

// Create returns a builder for creating a CalendarRequestLog entity.
func (c *CalendarRequestLogClient) Create() *CalendarRequestLogCreate {
	mutation := newCalendarRequestLogMutation(c.config, OpCreate)
	return &CalendarRequestLogCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of CalendarRequestLog entities.
func (c *CalendarRequestLogClient) CreateBulk(builders ...*CalendarRequestLogCreate) *CalendarRequestLogCreateBulk {
	return &CalendarRequestLogCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *CalendarRequestLogClient) MapCreateBulk(slice any, setFunc func(*CalendarRequestLogCreate, int)) *CalendarRequestLogCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &CalendarRequestLogCreateBulk{err: fmt.Errorf("calling to CalendarRequestLogClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*CalendarRequestLogCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &CalendarRequestLogCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for CalendarRequestLog.
func (c *CalendarRequestLogClient) Update() *CalendarRequestLogUpdate {
	mutation := newCalendarRequestLogMutation(c.config, OpUpdate)
	return &CalendarRequestLogUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *CalendarRequestLogClient) UpdateOne(_m *CalendarRequestLog) *CalendarRequestLogUpdateOne {
	mutation := newCalendarRequestLogMutation(c.config, OpUpdateOne, withCalendarRequestLog(_m))
	return &CalendarRequestLogUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *CalendarRequestLogClient) UpdateOneID(id int) *CalendarRequestLogUpdateOne {
	mutation := newCalendarRequestLogMutation(c.config, OpUpdateOne, withCalendarRequestLogID(id))
	return &CalendarRequestLogUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for CalendarRequestLog.
func (c *CalendarRequestLogClient) Delete() *CalendarRequestLogDelete {
	mutation := newCalendarRequestLogMutation(c.config, OpDelete)
	return &CalendarRequestLogDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *CalendarRequestLogClient) DeleteOne(_m *CalendarRequestLog) *CalendarRequestLogDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *CalendarRequestLogClient) DeleteOneID(id int) *CalendarRequestLogDeleteOne {
	builder := c.Delete().Where(calendarrequestlog.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &CalendarRequestLogDeleteOne{builder}
}

// Query returns a query builder for CalendarRequestLog.
func (c *CalendarRequestLogClient) Query() *CalendarRequestLogQuery {
	return &CalendarRequestLogQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeCalendarRequestLog},
		inters: c.Interceptors(),
	}
}

// Get returns a CalendarRequestLog entity by its id.
func (c *CalendarRequestLogClient) Get(ctx context.Context, id int) (*CalendarRequestLog, error) {
	return c.Query().Where(calendarrequestlog.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *CalendarRequestLogClient) GetX(ctx context.Context, id int) *CalendarRequestLog {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QuerySubscription queries the subscription edge of a CalendarRequestLog.
func (c *CalendarRequestLogClient) QuerySubscription(_m *CalendarRequestLog) *CalendarSubscriptionQuery {
	query := (&CalendarSubscriptionClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(calendarrequestlog.Table, calendarrequestlog.FieldID, id),
			sqlgraph.To(calendarsubscription.Table, calendarsubscription.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, calendarrequestlog.SubscriptionTable, calendarrequestlog.SubscriptionColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *CalendarRequestLogClient) Hooks() []Hook {
	return c.hooks.CalendarRequestLog
}

// Interceptors returns the client interceptors.
func (c *CalendarRequestLogClient) Interceptors() []Interceptor {
	return c.inters.CalendarRequestLog
}

func (c *CalendarRequestLogClient) mutate(ctx context.Context, m *CalendarRequestLogMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&CalendarRequestLogCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&CalendarRequestLogUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&CalendarRequestLogUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&CalendarRequestLogDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown CalendarRequestLog mutation op: %q", m.Op())
	}
}

// CalendarSubscriptionClient is a client for the CalendarSubscription schema.
type CalendarSubscriptionClient struct {
	config
}

// NewCalendarSubscriptionClient returns a client for the CalendarSubscription from the given config.
func NewCalendarSubscriptionClient(c config) *CalendarSubscriptionClient {
	return &CalendarSubscriptionClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `calendarsubscription.Hooks(f(g(h())))`.
func (c *CalendarSubscriptionClient) Use(hooks ...Hook) {
	c.hooks.CalendarSubscription = append(c.hooks.CalendarSubscription, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `calendarsubscription.Intercept(f(g(h())))`.
func (c *CalendarSubscriptionClient) Intercept(interceptors ...Interceptor) {
	c.inters.CalendarSubscription = append(c.inters.CalendarSubscription, interceptors...)
}

// Create returns a builder for creating a CalendarSubscription entity.
func (c *CalendarSubscriptionClient) Create() *CalendarSubscriptionCreate {
	mutation := newCalendarSubscriptionMutation(c.config, OpCreate)
	return &CalendarSubscriptionCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of CalendarSubscription entities.
func (c *CalendarSubscriptionClient) CreateBulk(builders ...*CalendarSubscriptionCreate) *CalendarSubscriptionCreateBulk {
	return &CalendarSubscriptionCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *CalendarSubscriptionClient) MapCreateBulk(slice any, setFunc func(*CalendarSubscriptionCreate, int)) *CalendarSubscriptionCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &CalendarSubscriptionCreateBulk{err: fmt.Errorf("calling to CalendarSubscriptionClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*CalendarSubscriptionCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &CalendarSubscriptionCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for CalendarSubscription.
func (c *CalendarSubscriptionClient) Update() *CalendarSubscriptionUpdate {
	mutation := newCalendarSubscriptionMutation(c.config, OpUpdate)
	return &CalendarSubscriptionUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *CalendarSubscriptionClient) UpdateOne(_m *CalendarSubscription) *CalendarSubscriptionUpdateOne {
	mutation := newCalendarSubscriptionMutation(c.config, OpUpdateOne, withCalendarSubscription(_m))
	return &CalendarSubscriptionUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *CalendarSubscriptionClient) UpdateOneID(id int) *CalendarSubscriptionUpdateOne {
	mutation := newCalendarSubscriptionMutation(c.config, OpUpdateOne, withCalendarSubscriptionID(id))
	return &CalendarSubscriptionUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for CalendarSubscription.
func (c *CalendarSubscriptionClient) Delete() *CalendarSubscriptionDelete {
	mutation := newCalendarSubscriptionMutation(c.config, OpDelete)
	return &CalendarSubscriptionDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *CalendarSubscriptionClient) DeleteOne(_m *CalendarSubscription) *CalendarSubscriptionDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *CalendarSubscriptionClient) DeleteOneID(id int) *CalendarSubscriptionDeleteOne {
	builder := c.Delete().Where(calendarsubscription.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &CalendarSubscriptionDeleteOne{builder}
}

// Query returns a query builder for CalendarSubscription.
func (c *CalendarSubscriptionClient) Query() *CalendarSubscriptionQuery {
	return &CalendarSubscriptionQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeCalendarSubscription},
		inters: c.Interceptors(),
	}
}

// Get returns a CalendarSubscription entity by its id.
func (c *CalendarSubscriptionClient) Get(ctx context.Context, id int) (*CalendarSubscription, error) {
	return c.Query().Where(calendarsubscription.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *CalendarSubscriptionClient) GetX(ctx context.Context, id int) *CalendarSubscription {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryUser queries the user edge of a CalendarSubscription.
func (c *CalendarSubscriptionClient) QueryUser(_m *CalendarSubscription) *UserQuery {
	query := (&UserClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(calendarsubscription.Table, calendarsubscription.FieldID, id),
			sqlgraph.To(user.Table, user.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, calendarsubscription.UserTable, calendarsubscription.UserColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QueryRequestLogs queries the request_logs edge of a CalendarSubscription.
func (c *CalendarSubscriptionClient) QueryRequestLogs(_m *CalendarSubscription) *CalendarRequestLogQuery {
	query := (&CalendarRequestLogClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(calendarsubscription.Table, calendarsubscription.FieldID, id),
			sqlgraph.To(calendarrequestlog.Table, calendarrequestlog.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, calendarsubscription.RequestLogsTable, calendarsubscription.RequestLogsColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *CalendarSubscriptionClient) Hooks() []Hook {
	return c.hooks.CalendarSubscription
}

// Interceptors returns the client interceptors.
func (c *CalendarSubscriptionClient) Interceptors() []Interceptor {
	return c.inters.CalendarSubscription
}

func (c *CalendarSubscriptionClient) mutate(ctx context.Context, m *CalendarSubscriptionMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&CalendarSubscriptionCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&CalendarSubscriptionUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&CalendarSubscriptionUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&CalendarSubscriptionDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown CalendarSubscription mutation op: %q", m.Op())
	}
}

// EmailVerificationCodeClient is a client for the EmailVerificationCode schema.
type EmailVerificationCodeClient struct {
	config
}

// NewEmailVerificationCodeClient returns a client for the EmailVerificationCode from the given config.
func NewEmailVerificationCodeClient(c config) *EmailVerificationCodeClient {
	return &EmailVerificationCodeClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `emailverificationcode.Hooks(f(g(h())))`.
func (c *EmailVerificationCodeClient) Use(hooks ...Hook) {
	c.hooks.EmailVerificationCode = append(c.hooks.EmailVerificationCode, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `emailverificationcode.Intercept(f(g(h())))`.
func (c *EmailVerificationCodeClient) Intercept(interceptors ...Interceptor) {
	c.inters.EmailVerificationCode = append(c.inters.EmailVerificationCode, interceptors...)
}

// Create returns a builder for creating a EmailVerificationCode entity.
func (c *EmailVerificationCodeClient) Create() *EmailVerificationCodeCreate {
	mutation := newEmailVerificationCodeMutation(c.config, OpCreate)
	return &EmailVerificationCodeCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of EmailVerificationCode entities.
func (c *EmailVerificationCodeClient) CreateBulk(builders ...*EmailVerificationCodeCreate) *EmailVerificationCodeCreateBulk {
	return &EmailVerificationCodeCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *EmailVerificationCodeClient) MapCreateBulk(slice any, setFunc func(*EmailVerificationCodeCreate, int)) *EmailVerificationCodeCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &EmailVerificationCodeCreateBulk{err: fmt.Errorf("calling to EmailVerificationCodeClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*EmailVerificationCodeCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &EmailVerificationCodeCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for EmailVerificationCode.
func (c *EmailVerificationCodeClient) Update() *EmailVerificationCodeUpdate {
	mutation := newEmailVerificationCodeMutation(c.config, OpUpdate)
	return &EmailVerificationCodeUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *EmailVerificationCodeClient) UpdateOne(_m *EmailVerificationCode) *EmailVerificationCodeUpdateOne {
	mutation := newEmailVerificationCodeMutation(c.config, OpUpdateOne, withEmailVerificationCode(_m))
	return &EmailVerificationCodeUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *EmailVerificationCodeClient) UpdateOneID(id int) *EmailVerificationCodeUpdateOne {
	mutation := newEmailVerificationCodeMutation(c.config, OpUpdateOne, withEmailVerificationCodeID(id))
	return &EmailVerificationCodeUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for EmailVerificationCode.
func (c *EmailVerificationCodeClient) Delete() *EmailVerificationCodeDelete {
	mutation := newEmailVerificationCodeMutation(c.config, OpDelete)
	return &EmailVerificationCodeDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *EmailVerificationCodeClient) DeleteOne(_m *EmailVerificationCode) *EmailVerificationCodeDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *EmailVerificationCodeClient) DeleteOneID(id int) *EmailVerificationCodeDeleteOne {
	builder := c.Delete().Where(emailverificationcode.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &EmailVerificationCodeDeleteOne{builder}
}

// Query returns a query builder for EmailVerificationCode.
func (c *EmailVerificationCodeClient) Query() *EmailVerificationCodeQuery {
	return &EmailVerificationCodeQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeEmailVerificationCode},
		inters: c.Interceptors(),
	}
}

// Get returns a EmailVerificationCode entity by its id.
func (c *EmailVerificationCodeClient) Get(ctx context.Context, id int) (*EmailVerificationCode, error) {
	return c.Query().Where(emailverificationcode.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *EmailVerificationCodeClient) GetX(ctx context.Context, id int) *EmailVerificationCode {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryUser queries the user edge of a EmailVerificationCode.
func (c *EmailVerificationCodeClient) QueryUser(_m *EmailVerificationCode) *UserQuery {
	query := (&UserClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(emailverificationcode.Table, emailverificationcode.FieldID, id),
			sqlgraph.To(user.Table, user.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, emailverificationcode.UserTable, emailverificationcode.UserColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *EmailVerificationCodeClient) Hooks() []Hook {
	return c.hooks.EmailVerificationCode
}

// Interceptors returns the client interceptors.
func (c *EmailVerificationCodeClient) Interceptors() []Interceptor {
	return c.inters.EmailVerificationCode
}

func (c *EmailVerificationCodeClient) mutate(ctx context.Context, m *EmailVerificationCodeMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&EmailVerificationCodeCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&EmailVerificationCodeUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&EmailVerificationCodeUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&EmailVerificationCodeDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown EmailVerificationCode mutation op: %q", m.Op())
	}
}

// GaiaCredentialClient is a client for the GaiaCredential schema.
type GaiaCredentialClient struct {
	config
}

// NewGaiaCredentialClient returns a client for the GaiaCredential from the given config.
func NewGaiaCredentialClient(c config) *GaiaCredentialClient {
	return &GaiaCredentialClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `gaiacredential.Hooks(f(g(h())))`.
func (c *GaiaCredentialClient) Use(hooks ...Hook) {
	c.hooks.GaiaCredential = append(c.hooks.GaiaCredential, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `gaiacredential.Intercept(f(g(h())))`.
func (c *GaiaCredentialClient) Intercept(interceptors ...Interceptor) {
	c.inters.GaiaCredential = append(c.inters.GaiaCredential, interceptors...)
}

// Create returns a builder for creating a GaiaCredential entity.
func (c *GaiaCredentialClient) Create() *GaiaCredentialCreate {
	mutation := newGaiaCredentialMutation(c.config, OpCreate)
	return &GaiaCredentialCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of GaiaCredential entities.
func (c *GaiaCredentialClient) CreateBulk(builders ...*GaiaCredentialCreate) *GaiaCredentialCreateBulk {
	return &GaiaCredentialCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *GaiaCredentialClient) MapCreateBulk(slice any, setFunc func(*GaiaCredentialCreate, int)) *GaiaCredentialCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &GaiaCredentialCreateBulk{err: fmt.Errorf("calling to GaiaCredentialClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*GaiaCredentialCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &GaiaCredentialCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for GaiaCredential.
func (c *GaiaCredentialClient) Update() *GaiaCredentialUpdate {
	mutation := newGaiaCredentialMutation(c.config, OpUpdate)
	return &GaiaCredentialUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *GaiaCredentialClient) UpdateOne(_m *GaiaCredential) *GaiaCredentialUpdateOne {
	mutation := newGaiaCredentialMutation(c.config, OpUpdateOne, withGaiaCredential(_m))
	return &GaiaCredentialUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *GaiaCredentialClient) UpdateOneID(id int) *GaiaCredentialUpdateOne {
	mutation := newGaiaCredentialMutation(c.config, OpUpdateOne, withGaiaCredentialID(id))
	return &GaiaCredentialUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for GaiaCredential.
func (c *GaiaCredentialClient) Delete() *GaiaCredentialDelete {
	mutation := newGaiaCredentialMutation(c.config, OpDelete)
	return &GaiaCredentialDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *GaiaCredentialClient) DeleteOne(_m *GaiaCredential) *GaiaCredentialDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *GaiaCredentialClient) DeleteOneID(id int) *GaiaCredentialDeleteOne {
	builder := c.Delete().Where(gaiacredential.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &GaiaCredentialDeleteOne{builder}
}

// Query returns a query builder for GaiaCredential.
func (c *GaiaCredentialClient) Query() *GaiaCredentialQuery {
	return &GaiaCredentialQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeGaiaCredential},
		inters: c.Interceptors(),
	}
}

// Get returns a GaiaCredential entity by its id.
func (c *GaiaCredentialClient) Get(ctx context.Context, id int) (*GaiaCredential, error) {
	return c.Query().Where(gaiacredential.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *GaiaCredentialClient) GetX(ctx context.Context, id int) *GaiaCredential {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryUser queries the user edge of a GaiaCredential.
func (c *GaiaCredentialClient) QueryUser(_m *GaiaCredential) *UserQuery {
	query := (&UserClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(gaiacredential.Table, gaiacredential.FieldID, id),
			sqlgraph.To(user.Table, user.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, gaiacredential.UserTable, gaiacredential.UserColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *GaiaCredentialClient) Hooks() []Hook {
	return c.hooks.GaiaCredential
}

// Interceptors returns the client interceptors.
func (c *GaiaCredentialClient) Interceptors() []Interceptor {
	return c.inters.GaiaCredential
}

func (c *GaiaCredentialClient) mutate(ctx context.Context, m *GaiaCredentialMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&GaiaCredentialCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&GaiaCredentialUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&GaiaCredentialUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&GaiaCredentialDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown GaiaCredential mutation op: %q", m.Op())
	}
}

// GaiaSessionClient is a client for the GaiaSession schema.
type GaiaSessionClient struct {
	config
}

// NewGaiaSessionClient returns a client for the GaiaSession from the given config.
func NewGaiaSessionClient(c config) *GaiaSessionClient {
	return &GaiaSessionClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `gaiasession.Hooks(f(g(h())))`.
func (c *GaiaSessionClient) Use(hooks ...Hook) {
	c.hooks.GaiaSession = append(c.hooks.GaiaSession, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `gaiasession.Intercept(f(g(h())))`.
func (c *GaiaSessionClient) Intercept(interceptors ...Interceptor) {
	c.inters.GaiaSession = append(c.inters.GaiaSession, interceptors...)
}

// Create returns a builder for creating a GaiaSession entity.
func (c *GaiaSessionClient) Create() *GaiaSessionCreate {
	mutation := newGaiaSessionMutation(c.config, OpCreate)
	return &GaiaSessionCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of GaiaSession entities.
func (c *GaiaSessionClient) CreateBulk(builders ...*GaiaSessionCreate) *GaiaSessionCreateBulk {
	return &GaiaSessionCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *GaiaSessionClient) MapCreateBulk(slice any, setFunc func(*GaiaSessionCreate, int)) *GaiaSessionCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &GaiaSessionCreateBulk{err: fmt.Errorf("calling to GaiaSessionClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*GaiaSessionCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &GaiaSessionCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for GaiaSession.
func (c *GaiaSessionClient) Update() *GaiaSessionUpdate {
	mutation := newGaiaSessionMutation(c.config, OpUpdate)
	return &GaiaSessionUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *GaiaSessionClient) UpdateOne(_m *GaiaSession) *GaiaSessionUpdateOne {
	mutation := newGaiaSessionMutation(c.config, OpUpdateOne, withGaiaSession(_m))
	return &GaiaSessionUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *GaiaSessionClient) UpdateOneID(id int) *GaiaSessionUpdateOne {
	mutation := newGaiaSessionMutation(c.config, OpUpdateOne, withGaiaSessionID(id))
	return &GaiaSessionUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for GaiaSession.
func (c *GaiaSessionClient) Delete() *GaiaSessionDelete {
	mutation := newGaiaSessionMutation(c.config, OpDelete)
	return &GaiaSessionDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *GaiaSessionClient) DeleteOne(_m *GaiaSession) *GaiaSessionDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *GaiaSessionClient) DeleteOneID(id int) *GaiaSessionDeleteOne {
	builder := c.Delete().Where(gaiasession.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &GaiaSessionDeleteOne{builder}
}

// Query returns a query builder for GaiaSession.
func (c *GaiaSessionClient) Query() *GaiaSessionQuery {
	return &GaiaSessionQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeGaiaSession},
		inters: c.Interceptors(),
	}
}

// Get returns a GaiaSession entity by its id.
func (c *GaiaSessionClient) Get(ctx context.Context, id int) (*GaiaSession, error) {
	return c.Query().Where(gaiasession.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *GaiaSessionClient) GetX(ctx context.Context, id int) *GaiaSession {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryUser queries the user edge of a GaiaSession.
func (c *GaiaSessionClient) QueryUser(_m *GaiaSession) *UserQuery {
	query := (&UserClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(gaiasession.Table, gaiasession.FieldID, id),
			sqlgraph.To(user.Table, user.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, gaiasession.UserTable, gaiasession.UserColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *GaiaSessionClient) Hooks() []Hook {
	return c.hooks.GaiaSession
}

// Interceptors returns the client interceptors.
func (c *GaiaSessionClient) Interceptors() []Interceptor {
	return c.inters.GaiaSession
}

func (c *GaiaSessionClient) mutate(ctx context.Context, m *GaiaSessionMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&GaiaSessionCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&GaiaSessionUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&GaiaSessionUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&GaiaSessionDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown GaiaSession mutation op: %q", m.Op())
	}
}

// PasswordResetTokenClient is a client for the PasswordResetToken schema.
type PasswordResetTokenClient struct {
	config
}

// NewPasswordResetTokenClient returns a client for the PasswordResetToken from the given config.
func NewPasswordResetTokenClient(c config) *PasswordResetTokenClient {
	return &PasswordResetTokenClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `passwordresettoken.Hooks(f(g(h())))`.
func (c *PasswordResetTokenClient) Use(hooks ...Hook) {
	c.hooks.PasswordResetToken = append(c.hooks.PasswordResetToken, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `passwordresettoken.Intercept(f(g(h())))`.
func (c *PasswordResetTokenClient) Intercept(interceptors ...Interceptor) {
	c.inters.PasswordResetToken = append(c.inters.PasswordResetToken, interceptors...)
}

// Create returns a builder for creating a PasswordResetToken entity.
func (c *PasswordResetTokenClient) Create() *PasswordResetTokenCreate {
	mutation := newPasswordResetTokenMutation(c.config, OpCreate)
	return &PasswordResetTokenCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of PasswordResetToken entities.
func (c *PasswordResetTokenClient) CreateBulk(builders ...*PasswordResetTokenCreate) *PasswordResetTokenCreateBulk {
	return &PasswordResetTokenCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *PasswordResetTokenClient) MapCreateBulk(slice any, setFunc func(*PasswordResetTokenCreate, int)) *PasswordResetTokenCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &PasswordResetTokenCreateBulk{err: fmt.Errorf("calling to PasswordResetTokenClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*PasswordResetTokenCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &PasswordResetTokenCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for PasswordResetToken.
func (c *PasswordResetTokenClient) Update() *PasswordResetTokenUpdate {
	mutation := newPasswordResetTokenMutation(c.config, OpUpdate)
	return &PasswordResetTokenUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *PasswordResetTokenClient) UpdateOne(_m *PasswordResetToken) *PasswordResetTokenUpdateOne {
	mutation := newPasswordResetTokenMutation(c.config, OpUpdateOne, withPasswordResetToken(_m))
	return &PasswordResetTokenUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *PasswordResetTokenClient) UpdateOneID(id int) *PasswordResetTokenUpdateOne {
	mutation := newPasswordResetTokenMutation(c.config, OpUpdateOne, withPasswordResetTokenID(id))
	return &PasswordResetTokenUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for PasswordResetToken.
func (c *PasswordResetTokenClient) Delete() *PasswordResetTokenDelete {
	mutation := newPasswordResetTokenMutation(c.config, OpDelete)
	return &PasswordResetTokenDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *PasswordResetTokenClient) DeleteOne(_m *PasswordResetToken) *PasswordResetTokenDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *PasswordResetTokenClient) DeleteOneID(id int) *PasswordResetTokenDeleteOne {
	builder := c.Delete().Where(passwordresettoken.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &PasswordResetTokenDeleteOne{builder}
}

// Query returns a query builder for PasswordResetToken.
func (c *PasswordResetTokenClient) Query() *PasswordResetTokenQuery {
	return &PasswordResetTokenQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypePasswordResetToken},
		inters: c.Interceptors(),
	}
}

// Get returns a PasswordResetToken entity by its id.
func (c *PasswordResetTokenClient) Get(ctx context.Context, id int) (*PasswordResetToken, error) {
	return c.Query().Where(passwordresettoken.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *PasswordResetTokenClient) GetX(ctx context.Context, id int) *PasswordResetToken {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryUser queries the user edge of a PasswordResetToken.
func (c *PasswordResetTokenClient) QueryUser(_m *PasswordResetToken) *UserQuery {
	query := (&UserClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(passwordresettoken.Table, passwordresettoken.FieldID, id),
			sqlgraph.To(user.Table, user.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, passwordresettoken.UserTable, passwordresettoken.UserColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *PasswordResetTokenClient) Hooks() []Hook {
	return c.hooks.PasswordResetToken
}

// Interceptors returns the client interceptors.
func (c *PasswordResetTokenClient) Interceptors() []Interceptor {
	return c.inters.PasswordResetToken
}

func (c *PasswordResetTokenClient) mutate(ctx context.Context, m *PasswordResetTokenMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&PasswordResetTokenCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&PasswordResetTokenUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&PasswordResetTokenUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&PasswordResetTokenDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown PasswordResetToken mutation op: %q", m.Op())
	}
}

// ScheduleEntryClient is a client for the ScheduleEntry schema.
type ScheduleEntryClient struct {
	config
}

// NewScheduleEntryClient returns a client for the ScheduleEntry from the given config.
func NewScheduleEntryClient(c config) *ScheduleEntryClient {
	return &ScheduleEntryClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `scheduleentry.Hooks(f(g(h())))`.
func (c *ScheduleEntryClient) Use(hooks ...Hook) {
	c.hooks.ScheduleEntry = append(c.hooks.ScheduleEntry, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `scheduleentry.Intercept(f(g(h())))`.
func (c *ScheduleEntryClient) Intercept(interceptors ...Interceptor) {
	c.inters.ScheduleEntry = append(c.inters.ScheduleEntry, interceptors...)
}

// Create returns a builder for creating a ScheduleEntry entity.
func (c *ScheduleEntryClient) Create() *ScheduleEntryCreate {
	mutation := newScheduleEntryMutation(c.config, OpCreate)
	return &ScheduleEntryCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of ScheduleEntry entities.
func (c *ScheduleEntryClient) CreateBulk(builders ...*ScheduleEntryCreate) *ScheduleEntryCreateBulk {
	return &ScheduleEntryCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *ScheduleEntryClient) MapCreateBulk(slice any, setFunc func(*ScheduleEntryCreate, int)) *ScheduleEntryCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &ScheduleEntryCreateBulk{err: fmt.Errorf("calling to ScheduleEntryClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*ScheduleEntryCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &ScheduleEntryCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for ScheduleEntry.
func (c *ScheduleEntryClient) Update() *ScheduleEntryUpdate {
	mutation := newScheduleEntryMutation(c.config, OpUpdate)
	return &ScheduleEntryUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *ScheduleEntryClient) UpdateOne(_m *ScheduleEntry) *ScheduleEntryUpdateOne {
	mutation := newScheduleEntryMutation(c.config, OpUpdateOne, withScheduleEntry(_m))
	return &ScheduleEntryUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *ScheduleEntryClient) UpdateOneID(id int) *ScheduleEntryUpdateOne {
	mutation := newScheduleEntryMutation(c.config, OpUpdateOne, withScheduleEntryID(id))
	return &ScheduleEntryUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for ScheduleEntry.
func (c *ScheduleEntryClient) Delete() *ScheduleEntryDelete {
	mutation := newScheduleEntryMutation(c.config, OpDelete)
	return &ScheduleEntryDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *ScheduleEntryClient) DeleteOne(_m *ScheduleEntry) *ScheduleEntryDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *ScheduleEntryClient) DeleteOneID(id int) *ScheduleEntryDeleteOne {
	builder := c.Delete().Where(scheduleentry.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &ScheduleEntryDeleteOne{builder}
}

// Query returns a query builder for ScheduleEntry.
func (c *ScheduleEntryClient) Query() *ScheduleEntryQuery {
	return &ScheduleEntryQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeScheduleEntry},
		inters: c.Interceptors(),
	}
}

// Get returns a ScheduleEntry entity by its id.
func (c *ScheduleEntryClient) Get(ctx context.Context, id int) (*ScheduleEntry, error) {
	return c.Query().Where(scheduleentry.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *ScheduleEntryClient) GetX(ctx context.Context, id int) *ScheduleEntry {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryUser queries the user edge of a ScheduleEntry.
func (c *ScheduleEntryClient) QueryUser(_m *ScheduleEntry) *UserQuery {
	query := (&UserClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(scheduleentry.Table, scheduleentry.FieldID, id),
			sqlgraph.To(user.Table, user.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, scheduleentry.UserTable, scheduleentry.UserColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *ScheduleEntryClient) Hooks() []Hook {
	return c.hooks.ScheduleEntry
}

// Interceptors returns the client interceptors.
func (c *ScheduleEntryClient) Interceptors() []Interceptor {
	return c.inters.ScheduleEntry
}

func (c *ScheduleEntryClient) mutate(ctx context.Context, m *ScheduleEntryMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&ScheduleEntryCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&ScheduleEntryUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&ScheduleEntryUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&ScheduleEntryDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown ScheduleEntry mutation op: %q", m.Op())
	}
}

// ScheduleSyncRunClient is a client for the ScheduleSyncRun schema.
type ScheduleSyncRunClient struct {
	config
}

// NewScheduleSyncRunClient returns a client for the ScheduleSyncRun from the given config.
func NewScheduleSyncRunClient(c config) *ScheduleSyncRunClient {
	return &ScheduleSyncRunClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `schedulesyncrun.Hooks(f(g(h())))`.
func (c *ScheduleSyncRunClient) Use(hooks ...Hook) {
	c.hooks.ScheduleSyncRun = append(c.hooks.ScheduleSyncRun, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `schedulesyncrun.Intercept(f(g(h())))`.
func (c *ScheduleSyncRunClient) Intercept(interceptors ...Interceptor) {
	c.inters.ScheduleSyncRun = append(c.inters.ScheduleSyncRun, interceptors...)
}

// Create returns a builder for creating a ScheduleSyncRun entity.
func (c *ScheduleSyncRunClient) Create() *ScheduleSyncRunCreate {
	mutation := newScheduleSyncRunMutation(c.config, OpCreate)
	return &ScheduleSyncRunCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of ScheduleSyncRun entities.
func (c *ScheduleSyncRunClient) CreateBulk(builders ...*ScheduleSyncRunCreate) *ScheduleSyncRunCreateBulk {
	return &ScheduleSyncRunCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *ScheduleSyncRunClient) MapCreateBulk(slice any, setFunc func(*ScheduleSyncRunCreate, int)) *ScheduleSyncRunCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &ScheduleSyncRunCreateBulk{err: fmt.Errorf("calling to ScheduleSyncRunClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*ScheduleSyncRunCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &ScheduleSyncRunCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for ScheduleSyncRun.
func (c *ScheduleSyncRunClient) Update() *ScheduleSyncRunUpdate {
	mutation := newScheduleSyncRunMutation(c.config, OpUpdate)
	return &ScheduleSyncRunUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *ScheduleSyncRunClient) UpdateOne(_m *ScheduleSyncRun) *ScheduleSyncRunUpdateOne {
	mutation := newScheduleSyncRunMutation(c.config, OpUpdateOne, withScheduleSyncRun(_m))
	return &ScheduleSyncRunUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *ScheduleSyncRunClient) UpdateOneID(id int) *ScheduleSyncRunUpdateOne {
	mutation := newScheduleSyncRunMutation(c.config, OpUpdateOne, withScheduleSyncRunID(id))
	return &ScheduleSyncRunUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for ScheduleSyncRun.
func (c *ScheduleSyncRunClient) Delete() *ScheduleSyncRunDelete {
	mutation := newScheduleSyncRunMutation(c.config, OpDelete)
	return &ScheduleSyncRunDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *ScheduleSyncRunClient) DeleteOne(_m *ScheduleSyncRun) *ScheduleSyncRunDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *ScheduleSyncRunClient) DeleteOneID(id int) *ScheduleSyncRunDeleteOne {
	builder := c.Delete().Where(schedulesyncrun.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &ScheduleSyncRunDeleteOne{builder}
}

// Query returns a query builder for ScheduleSyncRun.
func (c *ScheduleSyncRunClient) Query() *ScheduleSyncRunQuery {
	return &ScheduleSyncRunQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeScheduleSyncRun},
		inters: c.Interceptors(),
	}
}

// Get returns a ScheduleSyncRun entity by its id.
func (c *ScheduleSyncRunClient) Get(ctx context.Context, id int) (*ScheduleSyncRun, error) {
	return c.Query().Where(schedulesyncrun.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *ScheduleSyncRunClient) GetX(ctx context.Context, id int) *ScheduleSyncRun {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryUser queries the user edge of a ScheduleSyncRun.
func (c *ScheduleSyncRunClient) QueryUser(_m *ScheduleSyncRun) *UserQuery {
	query := (&UserClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(schedulesyncrun.Table, schedulesyncrun.FieldID, id),
			sqlgraph.To(user.Table, user.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, schedulesyncrun.UserTable, schedulesyncrun.UserColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *ScheduleSyncRunClient) Hooks() []Hook {
	return c.hooks.ScheduleSyncRun
}

// Interceptors returns the client interceptors.
func (c *ScheduleSyncRunClient) Interceptors() []Interceptor {
	return c.inters.ScheduleSyncRun
}

func (c *ScheduleSyncRunClient) mutate(ctx context.Context, m *ScheduleSyncRunMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&ScheduleSyncRunCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&ScheduleSyncRunUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&ScheduleSyncRunUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&ScheduleSyncRunDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown ScheduleSyncRun mutation op: %q", m.Op())
	}
}

// UserClient is a client for the User schema.
type UserClient struct {
	config
}

// NewUserClient returns a client for the User from the given config.
func NewUserClient(c config) *UserClient {
	return &UserClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `user.Hooks(f(g(h())))`.
func (c *UserClient) Use(hooks ...Hook) {
	c.hooks.User = append(c.hooks.User, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `user.Intercept(f(g(h())))`.
func (c *UserClient) Intercept(interceptors ...Interceptor) {
	c.inters.User = append(c.inters.User, interceptors...)
}

// Create returns a builder for creating a User entity.
func (c *UserClient) Create() *UserCreate {
	mutation := newUserMutation(c.config, OpCreate)
	return &UserCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of User entities.
func (c *UserClient) CreateBulk(builders ...*UserCreate) *UserCreateBulk {
	return &UserCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *UserClient) MapCreateBulk(slice any, setFunc func(*UserCreate, int)) *UserCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &UserCreateBulk{err: fmt.Errorf("calling to UserClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*UserCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &UserCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for User.
func (c *UserClient) Update() *UserUpdate {
	mutation := newUserMutation(c.config, OpUpdate)
	return &UserUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *UserClient) UpdateOne(_m *User) *UserUpdateOne {
	mutation := newUserMutation(c.config, OpUpdateOne, withUser(_m))
	return &UserUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *UserClient) UpdateOneID(id int) *UserUpdateOne {
	mutation := newUserMutation(c.config, OpUpdateOne, withUserID(id))
	return &UserUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for User.
func (c *UserClient) Delete() *UserDelete {
	mutation := newUserMutation(c.config, OpDelete)
	return &UserDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *UserClient) DeleteOne(_m *User) *UserDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *UserClient) DeleteOneID(id int) *UserDeleteOne {
	builder := c.Delete().Where(user.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &UserDeleteOne{builder}
}

// Query returns a query builder for User.
func (c *UserClient) Query() *UserQuery {
	return &UserQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeUser},
		inters: c.Interceptors(),
	}
}

// Get returns a User entity by its id.
func (c *UserClient) Get(ctx context.Context, id int) (*User, error) {
	return c.Query().Where(user.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *UserClient) GetX(ctx context.Context, id int) *User {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryVerificationCodes queries the verification_codes edge of a User.
func (c *UserClient) QueryVerificationCodes(_m *User) *EmailVerificationCodeQuery {
	query := (&EmailVerificationCodeClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(user.Table, user.FieldID, id),
			sqlgraph.To(emailverificationcode.Table, emailverificationcode.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, user.VerificationCodesTable, user.VerificationCodesColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QueryPasswordResetTokens queries the password_reset_tokens edge of a User.
func (c *UserClient) QueryPasswordResetTokens(_m *User) *PasswordResetTokenQuery {
	query := (&PasswordResetTokenClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(user.Table, user.FieldID, id),
			sqlgraph.To(passwordresettoken.Table, passwordresettoken.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, user.PasswordResetTokensTable, user.PasswordResetTokensColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QuerySessions queries the sessions edge of a User.
func (c *UserClient) QuerySessions(_m *User) *AppSessionQuery {
	query := (&AppSessionClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(user.Table, user.FieldID, id),
			sqlgraph.To(appsession.Table, appsession.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, user.SessionsTable, user.SessionsColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QueryGaiaCredentials queries the gaia_credentials edge of a User.
func (c *UserClient) QueryGaiaCredentials(_m *User) *GaiaCredentialQuery {
	query := (&GaiaCredentialClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(user.Table, user.FieldID, id),
			sqlgraph.To(gaiacredential.Table, gaiacredential.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, user.GaiaCredentialsTable, user.GaiaCredentialsColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QueryGaiaSessions queries the gaia_sessions edge of a User.
func (c *UserClient) QueryGaiaSessions(_m *User) *GaiaSessionQuery {
	query := (&GaiaSessionClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(user.Table, user.FieldID, id),
			sqlgraph.To(gaiasession.Table, gaiasession.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, user.GaiaSessionsTable, user.GaiaSessionsColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QueryScheduleEntries queries the schedule_entries edge of a User.
func (c *UserClient) QueryScheduleEntries(_m *User) *ScheduleEntryQuery {
	query := (&ScheduleEntryClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(user.Table, user.FieldID, id),
			sqlgraph.To(scheduleentry.Table, scheduleentry.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, user.ScheduleEntriesTable, user.ScheduleEntriesColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QuerySyncRuns queries the sync_runs edge of a User.
func (c *UserClient) QuerySyncRuns(_m *User) *ScheduleSyncRunQuery {
	query := (&ScheduleSyncRunClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(user.Table, user.FieldID, id),
			sqlgraph.To(schedulesyncrun.Table, schedulesyncrun.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, user.SyncRunsTable, user.SyncRunsColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QueryCalendarSubscriptions queries the calendar_subscriptions edge of a User.
func (c *UserClient) QueryCalendarSubscriptions(_m *User) *CalendarSubscriptionQuery {
	query := (&CalendarSubscriptionClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(user.Table, user.FieldID, id),
			sqlgraph.To(calendarsubscription.Table, calendarsubscription.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, user.CalendarSubscriptionsTable, user.CalendarSubscriptionsColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *UserClient) Hooks() []Hook {
	return c.hooks.User
}

// Interceptors returns the client interceptors.
func (c *UserClient) Interceptors() []Interceptor {
	return c.inters.User
}

func (c *UserClient) mutate(ctx context.Context, m *UserMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&UserCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&UserUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&UserUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&UserDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown User mutation op: %q", m.Op())
	}
}

// hooks and interceptors per client, for fast access.
type (
	hooks struct {
		AppSession, CalendarRequestLog, CalendarSubscription, EmailVerificationCode,
		GaiaCredential, GaiaSession, PasswordResetToken, ScheduleEntry,
		ScheduleSyncRun, User []ent.Hook
	}
	inters struct {
		AppSession, CalendarRequestLog, CalendarSubscription, EmailVerificationCode,
		GaiaCredential, GaiaSession, PasswordResetToken, ScheduleEntry,
		ScheduleSyncRun, User []ent.Interceptor
	}
)
