// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"gaia-calendar/ent/emailverificationcode"
	"gaia-calendar/ent/user"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// EmailVerificationCode is the model entity for the EmailVerificationCode schema.
type EmailVerificationCode struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// Email holds the value of the "email" field.
	Email string `json:"email,omitempty"`
	// CodeHash holds the value of the "code_hash" field.
	CodeHash string `json:"-"`
	// ExpiresAt holds the value of the "expires_at" field.
	ExpiresAt time.Time `json:"expires_at,omitempty"`
	// ConsumedAt holds the value of the "consumed_at" field.
	ConsumedAt *time.Time `json:"consumed_at,omitempty"`
	// AttemptCount holds the value of the "attempt_count" field.
	AttemptCount int `json:"attempt_count,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the EmailVerificationCodeQuery when eager-loading is set.
	Edges                   EmailVerificationCodeEdges `json:"edges"`
	user_verification_codes *int
	selectValues            sql.SelectValues
}

// EmailVerificationCodeEdges holds the relations/edges for other nodes in the graph.
type EmailVerificationCodeEdges struct {
	// User holds the value of the user edge.
	User *User `json:"user,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// UserOrErr returns the User value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e EmailVerificationCodeEdges) UserOrErr() (*User, error) {
	if e.User != nil {
		return e.User, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: user.Label}
	}
	return nil, &NotLoadedError{edge: "user"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*EmailVerificationCode) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case emailverificationcode.FieldID, emailverificationcode.FieldAttemptCount:
			values[i] = new(sql.NullInt64)
		case emailverificationcode.FieldEmail, emailverificationcode.FieldCodeHash:
			values[i] = new(sql.NullString)
		case emailverificationcode.FieldExpiresAt, emailverificationcode.FieldConsumedAt, emailverificationcode.FieldCreatedAt:
			values[i] = new(sql.NullTime)
		case emailverificationcode.ForeignKeys[0]: // user_verification_codes
			values[i] = new(sql.NullInt64)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the EmailVerificationCode fields.
func (_m *EmailVerificationCode) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case emailverificationcode.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case emailverificationcode.FieldEmail:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field email", values[i])
			} else if value.Valid {
				_m.Email = value.String
			}
		case emailverificationcode.FieldCodeHash:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field code_hash", values[i])
			} else if value.Valid {
				_m.CodeHash = value.String
			}
		case emailverificationcode.FieldExpiresAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field expires_at", values[i])
			} else if value.Valid {
				_m.ExpiresAt = value.Time
			}
		case emailverificationcode.FieldConsumedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field consumed_at", values[i])
			} else if value.Valid {
				_m.ConsumedAt = new(time.Time)
				*_m.ConsumedAt = value.Time
			}
		case emailverificationcode.FieldAttemptCount:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field attempt_count", values[i])
			} else if value.Valid {
				_m.AttemptCount = int(value.Int64)
			}
		case emailverificationcode.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case emailverificationcode.ForeignKeys[0]:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for edge-field user_verification_codes", value)
			} else if value.Valid {
				_m.user_verification_codes = new(int)
				*_m.user_verification_codes = int(value.Int64)
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the EmailVerificationCode.
// This includes values selected through modifiers, order, etc.
func (_m *EmailVerificationCode) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryUser queries the "user" edge of the EmailVerificationCode entity.
func (_m *EmailVerificationCode) QueryUser() *UserQuery {
	return NewEmailVerificationCodeClient(_m.config).QueryUser(_m)
}

// Update returns a builder for updating this EmailVerificationCode.
// Note that you need to call EmailVerificationCode.Unwrap() before calling this method if this EmailVerificationCode
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *EmailVerificationCode) Update() *EmailVerificationCodeUpdateOne {
	return NewEmailVerificationCodeClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the EmailVerificationCode entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *EmailVerificationCode) Unwrap() *EmailVerificationCode {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: EmailVerificationCode is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *EmailVerificationCode) String() string {
	var builder strings.Builder
	builder.WriteString("EmailVerificationCode(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("email=")
	builder.WriteString(_m.Email)
	builder.WriteString(", ")
	builder.WriteString("code_hash=<sensitive>")
	builder.WriteString(", ")
	builder.WriteString("expires_at=")
	builder.WriteString(_m.ExpiresAt.Format(time.ANSIC))
	builder.WriteString(", ")
	if v := _m.ConsumedAt; v != nil {
		builder.WriteString("consumed_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("attempt_count=")
	builder.WriteString(fmt.Sprintf("%v", _m.AttemptCount))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// EmailVerificationCodes is a parsable slice of EmailVerificationCode.
type EmailVerificationCodes []*EmailVerificationCode
