// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"gaia-calendar/ent/emailverificationcode"
	"gaia-calendar/ent/user"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// EmailVerificationCodeCreate is the builder for creating a EmailVerificationCode entity.
type EmailVerificationCodeCreate struct {
	config
	mutation *EmailVerificationCodeMutation
	hooks    []Hook
}

// SetEmail sets the "email" field.
func (_c *EmailVerificationCodeCreate) SetEmail(v string) *EmailVerificationCodeCreate {
	_c.mutation.SetEmail(v)
	return _c
}

// SetCodeHash sets the "code_hash" field.
func (_c *EmailVerificationCodeCreate) SetCodeHash(v string) *EmailVerificationCodeCreate {
	_c.mutation.SetCodeHash(v)
	return _c
}

// SetExpiresAt sets the "expires_at" field.
func (_c *EmailVerificationCodeCreate) SetExpiresAt(v time.Time) *EmailVerificationCodeCreate {
	_c.mutation.SetExpiresAt(v)
	return _c
}

// SetConsumedAt sets the "consumed_at" field.
func (_c *EmailVerificationCodeCreate) SetConsumedAt(v time.Time) *EmailVerificationCodeCreate {
	_c.mutation.SetConsumedAt(v)
	return _c
}

// SetNillableConsumedAt sets the "consumed_at" field if the given value is not nil.
func (_c *EmailVerificationCodeCreate) SetNillableConsumedAt(v *time.Time) *EmailVerificationCodeCreate {
	if v != nil {
		_c.SetConsumedAt(*v)
	}
	return _c
}

// SetAttemptCount sets the "attempt_count" field.
func (_c *EmailVerificationCodeCreate) SetAttemptCount(v int) *EmailVerificationCodeCreate {
	_c.mutation.SetAttemptCount(v)
	return _c
}

// SetNillableAttemptCount sets the "attempt_count" field if the given value is not nil.
func (_c *EmailVerificationCodeCreate) SetNillableAttemptCount(v *int) *EmailVerificationCodeCreate {
	if v != nil {
		_c.SetAttemptCount(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *EmailVerificationCodeCreate) SetCreatedAt(v time.Time) *EmailVerificationCodeCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *EmailVerificationCodeCreate) SetNillableCreatedAt(v *time.Time) *EmailVerificationCodeCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUserID sets the "user" edge to the User entity by ID.
func (_c *EmailVerificationCodeCreate) SetUserID(id int) *EmailVerificationCodeCreate {
	_c.mutation.SetUserID(id)
	return _c
}

// SetNillableUserID sets the "user" edge to the User entity by ID if the given value is not nil.
func (_c *EmailVerificationCodeCreate) SetNillableUserID(id *int) *EmailVerificationCodeCreate {
	if id != nil {
		_c = _c.SetUserID(*id)
	}
	return _c
}

// SetUser sets the "user" edge to the User entity.
func (_c *EmailVerificationCodeCreate) SetUser(v *User) *EmailVerificationCodeCreate {
	return _c.SetUserID(v.ID)
}

// Mutation returns the EmailVerificationCodeMutation object of the builder.
func (_c *EmailVerificationCodeCreate) Mutation() *EmailVerificationCodeMutation {
	return _c.mutation
}

// Save creates the EmailVerificationCode in the database.
func (_c *EmailVerificationCodeCreate) Save(ctx context.Context) (*EmailVerificationCode, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *EmailVerificationCodeCreate) SaveX(ctx context.Context) *EmailVerificationCode {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *EmailVerificationCodeCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *EmailVerificationCodeCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *EmailVerificationCodeCreate) defaults() {
	if _, ok := _c.mutation.AttemptCount(); !ok {
		v := emailverificationcode.DefaultAttemptCount
		_c.mutation.SetAttemptCount(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := emailverificationcode.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *EmailVerificationCodeCreate) check() error {
	if _, ok := _c.mutation.Email(); !ok {
		return &ValidationError{Name: "email", err: errors.New(`ent: missing required field "EmailVerificationCode.email"`)}
	}
	if v, ok := _c.mutation.Email(); ok {
		if err := emailverificationcode.EmailValidator(v); err != nil {
			return &ValidationError{Name: "email", err: fmt.Errorf(`ent: validator failed for field "EmailVerificationCode.email": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CodeHash(); !ok {
		return &ValidationError{Name: "code_hash", err: errors.New(`ent: missing required field "EmailVerificationCode.code_hash"`)}
	}
	if _, ok := _c.mutation.ExpiresAt(); !ok {
		return &ValidationError{Name: "expires_at", err: errors.New(`ent: missing required field "EmailVerificationCode.expires_at"`)}
	}
	if _, ok := _c.mutation.AttemptCount(); !ok {
		return &ValidationError{Name: "attempt_count", err: errors.New(`ent: missing required field "EmailVerificationCode.attempt_count"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "EmailVerificationCode.created_at"`)}
	}
	return nil
}

func (_c *EmailVerificationCodeCreate) sqlSave(ctx context.Context) (*EmailVerificationCode, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *EmailVerificationCodeCreate) createSpec() (*EmailVerificationCode, *sqlgraph.CreateSpec) {
	var (
		_node = &EmailVerificationCode{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(emailverificationcode.Table, sqlgraph.NewFieldSpec(emailverificationcode.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.Email(); ok {
		_spec.SetField(emailverificationcode.FieldEmail, field.TypeString, value)
		_node.Email = value
	}
	if value, ok := _c.mutation.CodeHash(); ok {
		_spec.SetField(emailverificationcode.FieldCodeHash, field.TypeString, value)
		_node.CodeHash = value
	}
	if value, ok := _c.mutation.ExpiresAt(); ok {
		_spec.SetField(emailverificationcode.FieldExpiresAt, field.TypeTime, value)
		_node.ExpiresAt = value
	}
	if value, ok := _c.mutation.ConsumedAt(); ok {
		_spec.SetField(emailverificationcode.FieldConsumedAt, field.TypeTime, value)
		_node.ConsumedAt = &value
	}
	if value, ok := _c.mutation.AttemptCount(); ok {
		_spec.SetField(emailverificationcode.FieldAttemptCount, field.TypeInt, value)
		_node.AttemptCount = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(emailverificationcode.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if nodes := _c.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   emailverificationcode.UserTable,
			Columns: []string{emailverificationcode.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.user_verification_codes = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// EmailVerificationCodeCreateBulk is the builder for creating many EmailVerificationCode entities in bulk.
type EmailVerificationCodeCreateBulk struct {
	config
	err      error
	builders []*EmailVerificationCodeCreate
}

// Save creates the EmailVerificationCode entities in the database.
func (_c *EmailVerificationCodeCreateBulk) Save(ctx context.Context) ([]*EmailVerificationCode, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*EmailVerificationCode, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*EmailVerificationCodeMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *EmailVerificationCodeCreateBulk) SaveX(ctx context.Context) []*EmailVerificationCode {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *EmailVerificationCodeCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *EmailVerificationCodeCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
