// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"gaia-calendar/ent/gaiasession"
	"gaia-calendar/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// GaiaSessionDelete is the builder for deleting a GaiaSession entity.
type GaiaSessionDelete struct {
	config
	hooks    []Hook
	mutation *GaiaSessionMutation
}

// Where appends a list predicates to the GaiaSessionDelete builder.
func (_d *GaiaSessionDelete) Where(ps ...predicate.GaiaSession) *GaiaSessionDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *GaiaSessionDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *GaiaSessionDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *GaiaSessionDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(gaiasession.Table, sqlgraph.NewFieldSpec(gaiasession.FieldID, field.TypeInt))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// GaiaSessionDeleteOne is the builder for deleting a single GaiaSession entity.
type GaiaSessionDeleteOne struct {
	_d *GaiaSessionDelete
}

// Where appends a list predicates to the GaiaSessionDelete builder.
func (_d *GaiaSessionDeleteOne) Where(ps ...predicate.GaiaSession) *GaiaSessionDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *GaiaSessionDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{gaiasession.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *GaiaSessionDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
