// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"gaia-calendar/ent/gaiacredential"
	"gaia-calendar/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// GaiaCredentialDelete is the builder for deleting a GaiaCredential entity.
type GaiaCredentialDelete struct {
	config
	hooks    []Hook
	mutation *GaiaCredentialMutation
}

// Where appends a list predicates to the GaiaCredentialDelete builder.
func (_d *GaiaCredentialDelete) Where(ps ...predicate.GaiaCredential) *GaiaCredentialDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *GaiaCredentialDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *GaiaCredentialDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *GaiaCredentialDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(gaiacredential.Table, sqlgraph.NewFieldSpec(gaiacredential.FieldID, field.TypeInt))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// GaiaCredentialDeleteOne is the builder for deleting a single GaiaCredential entity.
type GaiaCredentialDeleteOne struct {
	_d *GaiaCredentialDelete
}

// Where appends a list predicates to the GaiaCredentialDelete builder.
func (_d *GaiaCredentialDeleteOne) Where(ps ...predicate.GaiaCredential) *GaiaCredentialDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *GaiaCredentialDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{gaiacredential.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *GaiaCredentialDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
