// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"gaia-calendar/ent/gaiasession"
	"gaia-calendar/ent/user"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// GaiaSession is the model entity for the GaiaSession schema.
type GaiaSession struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// CompanyCode holds the value of the "company_code" field.
	CompanyCode string `json:"company_code,omitempty"`
	// EncryptedPayload holds the value of the "encrypted_payload" field.
	EncryptedPayload string `json:"-"`
	// ExpiresAt holds the value of the "expires_at" field.
	ExpiresAt *time.Time `json:"expires_at,omitempty"`
	// LastError holds the value of the "last_error" field.
	LastError *string `json:"last_error,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the GaiaSessionQuery when eager-loading is set.
	Edges              GaiaSessionEdges `json:"edges"`
	user_gaia_sessions *int
	selectValues       sql.SelectValues
}

// GaiaSessionEdges holds the relations/edges for other nodes in the graph.
type GaiaSessionEdges struct {
	// User holds the value of the user edge.
	User *User `json:"user,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// UserOrErr returns the User value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e GaiaSessionEdges) UserOrErr() (*User, error) {
	if e.User != nil {
		return e.User, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: user.Label}
	}
	return nil, &NotLoadedError{edge: "user"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*GaiaSession) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case gaiasession.FieldID:
			values[i] = new(sql.NullInt64)
		case gaiasession.FieldCompanyCode, gaiasession.FieldEncryptedPayload, gaiasession.FieldLastError:
			values[i] = new(sql.NullString)
		case gaiasession.FieldExpiresAt, gaiasession.FieldCreatedAt, gaiasession.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		case gaiasession.ForeignKeys[0]: // user_gaia_sessions
			values[i] = new(sql.NullInt64)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the GaiaSession fields.
func (_m *GaiaSession) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case gaiasession.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case gaiasession.FieldCompanyCode:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field company_code", values[i])
			} else if value.Valid {
				_m.CompanyCode = value.String
			}
		case gaiasession.FieldEncryptedPayload:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field encrypted_payload", values[i])
			} else if value.Valid {
				_m.EncryptedPayload = value.String
			}
		case gaiasession.FieldExpiresAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field expires_at", values[i])
			} else if value.Valid {
				_m.ExpiresAt = new(time.Time)
				*_m.ExpiresAt = value.Time
			}
		case gaiasession.FieldLastError:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field last_error", values[i])
			} else if value.Valid {
				_m.LastError = new(string)
				*_m.LastError = value.String
			}
		case gaiasession.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case gaiasession.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case gaiasession.ForeignKeys[0]:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for edge-field user_gaia_sessions", value)
			} else if value.Valid {
				_m.user_gaia_sessions = new(int)
				*_m.user_gaia_sessions = int(value.Int64)
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the GaiaSession.
// This includes values selected through modifiers, order, etc.
func (_m *GaiaSession) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryUser queries the "user" edge of the GaiaSession entity.
func (_m *GaiaSession) QueryUser() *UserQuery {
	return NewGaiaSessionClient(_m.config).QueryUser(_m)
}

// Update returns a builder for updating this GaiaSession.
// Note that you need to call GaiaSession.Unwrap() before calling this method if this GaiaSession
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *GaiaSession) Update() *GaiaSessionUpdateOne {
	return NewGaiaSessionClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the GaiaSession entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *GaiaSession) Unwrap() *GaiaSession {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: GaiaSession is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *GaiaSession) String() string {
	var builder strings.Builder
	builder.WriteString("GaiaSession(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("company_code=")
	builder.WriteString(_m.CompanyCode)
	builder.WriteString(", ")
	builder.WriteString("encrypted_payload=<sensitive>")
	builder.WriteString(", ")
	if v := _m.ExpiresAt; v != nil {
		builder.WriteString("expires_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.LastError; v != nil {
		builder.WriteString("last_error=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// GaiaSessions is a parsable slice of GaiaSession.
type GaiaSessions []*GaiaSession
