// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"gaia-calendar/ent/gaiasession"
	"gaia-calendar/ent/predicate"
	"gaia-calendar/ent/user"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// GaiaSessionUpdate is the builder for updating GaiaSession entities.
type GaiaSessionUpdate struct {
	config
	hooks    []Hook
	mutation *GaiaSessionMutation
}

// Where appends a list predicates to the GaiaSessionUpdate builder.
func (_u *GaiaSessionUpdate) Where(ps ...predicate.GaiaSession) *GaiaSessionUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetCompanyCode sets the "company_code" field.
func (_u *GaiaSessionUpdate) SetCompanyCode(v string) *GaiaSessionUpdate {
	_u.mutation.SetCompanyCode(v)
	return _u
}

// SetNillableCompanyCode sets the "company_code" field if the given value is not nil.
func (_u *GaiaSessionUpdate) SetNillableCompanyCode(v *string) *GaiaSessionUpdate {
	if v != nil {
		_u.SetCompanyCode(*v)
	}
	return _u
}

// SetEncryptedPayload sets the "encrypted_payload" field.
func (_u *GaiaSessionUpdate) SetEncryptedPayload(v string) *GaiaSessionUpdate {
	_u.mutation.SetEncryptedPayload(v)
	return _u
}

// SetNillableEncryptedPayload sets the "encrypted_payload" field if the given value is not nil.
func (_u *GaiaSessionUpdate) SetNillableEncryptedPayload(v *string) *GaiaSessionUpdate {
	if v != nil {
		_u.SetEncryptedPayload(*v)
	}
	return _u
}

// SetExpiresAt sets the "expires_at" field.
func (_u *GaiaSessionUpdate) SetExpiresAt(v time.Time) *GaiaSessionUpdate {
	_u.mutation.SetExpiresAt(v)
	return _u
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (_u *GaiaSessionUpdate) SetNillableExpiresAt(v *time.Time) *GaiaSessionUpdate {
	if v != nil {
		_u.SetExpiresAt(*v)
	}
	return _u
}

// ClearExpiresAt clears the value of the "expires_at" field.
func (_u *GaiaSessionUpdate) ClearExpiresAt() *GaiaSessionUpdate {
	_u.mutation.ClearExpiresAt()
	return _u
}

// SetLastError sets the "last_error" field.
func (_u *GaiaSessionUpdate) SetLastError(v string) *GaiaSessionUpdate {
	_u.mutation.SetLastError(v)
	return _u
}

// SetNillableLastError sets the "last_error" field if the given value is not nil.
func (_u *GaiaSessionUpdate) SetNillableLastError(v *string) *GaiaSessionUpdate {
	if v != nil {
		_u.SetLastError(*v)
	}
	return _u
}

// ClearLastError clears the value of the "last_error" field.
func (_u *GaiaSessionUpdate) ClearLastError() *GaiaSessionUpdate {
	_u.mutation.ClearLastError()
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *GaiaSessionUpdate) SetCreatedAt(v time.Time) *GaiaSessionUpdate {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *GaiaSessionUpdate) SetNillableCreatedAt(v *time.Time) *GaiaSessionUpdate {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *GaiaSessionUpdate) SetUpdatedAt(v time.Time) *GaiaSessionUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetUserID sets the "user" edge to the User entity by ID.
func (_u *GaiaSessionUpdate) SetUserID(id int) *GaiaSessionUpdate {
	_u.mutation.SetUserID(id)
	return _u
}

// SetUser sets the "user" edge to the User entity.
func (_u *GaiaSessionUpdate) SetUser(v *User) *GaiaSessionUpdate {
	return _u.SetUserID(v.ID)
}

// Mutation returns the GaiaSessionMutation object of the builder.
func (_u *GaiaSessionUpdate) Mutation() *GaiaSessionMutation {
	return _u.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (_u *GaiaSessionUpdate) ClearUser() *GaiaSessionUpdate {
	_u.mutation.ClearUser()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *GaiaSessionUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *GaiaSessionUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *GaiaSessionUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *GaiaSessionUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *GaiaSessionUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := gaiasession.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *GaiaSessionUpdate) check() error {
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "GaiaSession.user"`)
	}
	return nil
}

func (_u *GaiaSessionUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(gaiasession.Table, gaiasession.Columns, sqlgraph.NewFieldSpec(gaiasession.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.CompanyCode(); ok {
		_spec.SetField(gaiasession.FieldCompanyCode, field.TypeString, value)
	}
	if value, ok := _u.mutation.EncryptedPayload(); ok {
		_spec.SetField(gaiasession.FieldEncryptedPayload, field.TypeString, value)
	}
	if value, ok := _u.mutation.ExpiresAt(); ok {
		_spec.SetField(gaiasession.FieldExpiresAt, field.TypeTime, value)
	}
	if _u.mutation.ExpiresAtCleared() {
		_spec.ClearField(gaiasession.FieldExpiresAt, field.TypeTime)
	}
	if value, ok := _u.mutation.LastError(); ok {
		_spec.SetField(gaiasession.FieldLastError, field.TypeString, value)
	}
	if _u.mutation.LastErrorCleared() {
		_spec.ClearField(gaiasession.FieldLastError, field.TypeString)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(gaiasession.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(gaiasession.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   gaiasession.UserTable,
			Columns: []string{gaiasession.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   gaiasession.UserTable,
			Columns: []string{gaiasession.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{gaiasession.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// GaiaSessionUpdateOne is the builder for updating a single GaiaSession entity.
type GaiaSessionUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *GaiaSessionMutation
}

// SetCompanyCode sets the "company_code" field.
func (_u *GaiaSessionUpdateOne) SetCompanyCode(v string) *GaiaSessionUpdateOne {
	_u.mutation.SetCompanyCode(v)
	return _u
}

// SetNillableCompanyCode sets the "company_code" field if the given value is not nil.
func (_u *GaiaSessionUpdateOne) SetNillableCompanyCode(v *string) *GaiaSessionUpdateOne {
	if v != nil {
		_u.SetCompanyCode(*v)
	}
	return _u
}

// SetEncryptedPayload sets the "encrypted_payload" field.
func (_u *GaiaSessionUpdateOne) SetEncryptedPayload(v string) *GaiaSessionUpdateOne {
	_u.mutation.SetEncryptedPayload(v)
	return _u
}

// SetNillableEncryptedPayload sets the "encrypted_payload" field if the given value is not nil.
func (_u *GaiaSessionUpdateOne) SetNillableEncryptedPayload(v *string) *GaiaSessionUpdateOne {
	if v != nil {
		_u.SetEncryptedPayload(*v)
	}
	return _u
}

// SetExpiresAt sets the "expires_at" field.
func (_u *GaiaSessionUpdateOne) SetExpiresAt(v time.Time) *GaiaSessionUpdateOne {
	_u.mutation.SetExpiresAt(v)
	return _u
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (_u *GaiaSessionUpdateOne) SetNillableExpiresAt(v *time.Time) *GaiaSessionUpdateOne {
	if v != nil {
		_u.SetExpiresAt(*v)
	}
	return _u
}

// ClearExpiresAt clears the value of the "expires_at" field.
func (_u *GaiaSessionUpdateOne) ClearExpiresAt() *GaiaSessionUpdateOne {
	_u.mutation.ClearExpiresAt()
	return _u
}

// SetLastError sets the "last_error" field.
func (_u *GaiaSessionUpdateOne) SetLastError(v string) *GaiaSessionUpdateOne {
	_u.mutation.SetLastError(v)
	return _u
}

// SetNillableLastError sets the "last_error" field if the given value is not nil.
func (_u *GaiaSessionUpdateOne) SetNillableLastError(v *string) *GaiaSessionUpdateOne {
	if v != nil {
		_u.SetLastError(*v)
	}
	return _u
}

// ClearLastError clears the value of the "last_error" field.
func (_u *GaiaSessionUpdateOne) ClearLastError() *GaiaSessionUpdateOne {
	_u.mutation.ClearLastError()
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *GaiaSessionUpdateOne) SetCreatedAt(v time.Time) *GaiaSessionUpdateOne {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *GaiaSessionUpdateOne) SetNillableCreatedAt(v *time.Time) *GaiaSessionUpdateOne {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *GaiaSessionUpdateOne) SetUpdatedAt(v time.Time) *GaiaSessionUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetUserID sets the "user" edge to the User entity by ID.
func (_u *GaiaSessionUpdateOne) SetUserID(id int) *GaiaSessionUpdateOne {
	_u.mutation.SetUserID(id)
	return _u
}

// SetUser sets the "user" edge to the User entity.
func (_u *GaiaSessionUpdateOne) SetUser(v *User) *GaiaSessionUpdateOne {
	return _u.SetUserID(v.ID)
}

// Mutation returns the GaiaSessionMutation object of the builder.
func (_u *GaiaSessionUpdateOne) Mutation() *GaiaSessionMutation {
	return _u.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (_u *GaiaSessionUpdateOne) ClearUser() *GaiaSessionUpdateOne {
	_u.mutation.ClearUser()
	return _u
}

// Where appends a list predicates to the GaiaSessionUpdate builder.
func (_u *GaiaSessionUpdateOne) Where(ps ...predicate.GaiaSession) *GaiaSessionUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *GaiaSessionUpdateOne) Select(field string, fields ...string) *GaiaSessionUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated GaiaSession entity.
func (_u *GaiaSessionUpdateOne) Save(ctx context.Context) (*GaiaSession, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *GaiaSessionUpdateOne) SaveX(ctx context.Context) *GaiaSession {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *GaiaSessionUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *GaiaSessionUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *GaiaSessionUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := gaiasession.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *GaiaSessionUpdateOne) check() error {
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "GaiaSession.user"`)
	}
	return nil
}

func (_u *GaiaSessionUpdateOne) sqlSave(ctx context.Context) (_node *GaiaSession, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(gaiasession.Table, gaiasession.Columns, sqlgraph.NewFieldSpec(gaiasession.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "GaiaSession.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, gaiasession.FieldID)
		for _, f := range fields {
			if !gaiasession.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != gaiasession.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.CompanyCode(); ok {
		_spec.SetField(gaiasession.FieldCompanyCode, field.TypeString, value)
	}
	if value, ok := _u.mutation.EncryptedPayload(); ok {
		_spec.SetField(gaiasession.FieldEncryptedPayload, field.TypeString, value)
	}
	if value, ok := _u.mutation.ExpiresAt(); ok {
		_spec.SetField(gaiasession.FieldExpiresAt, field.TypeTime, value)
	}
	if _u.mutation.ExpiresAtCleared() {
		_spec.ClearField(gaiasession.FieldExpiresAt, field.TypeTime)
	}
	if value, ok := _u.mutation.LastError(); ok {
		_spec.SetField(gaiasession.FieldLastError, field.TypeString, value)
	}
	if _u.mutation.LastErrorCleared() {
		_spec.ClearField(gaiasession.FieldLastError, field.TypeString)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(gaiasession.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(gaiasession.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   gaiasession.UserTable,
			Columns: []string{gaiasession.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   gaiasession.UserTable,
			Columns: []string{gaiasession.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &GaiaSession{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{gaiasession.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
