// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"gaia-calendar/ent/gaiacredential"
	"gaia-calendar/ent/predicate"
	"gaia-calendar/ent/user"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// GaiaCredentialUpdate is the builder for updating GaiaCredential entities.
type GaiaCredentialUpdate struct {
	config
	hooks    []Hook
	mutation *GaiaCredentialMutation
}

// Where appends a list predicates to the GaiaCredentialUpdate builder.
func (_u *GaiaCredentialUpdate) Where(ps ...predicate.GaiaCredential) *GaiaCredentialUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetCompanyCode sets the "company_code" field.
func (_u *GaiaCredentialUpdate) SetCompanyCode(v string) *GaiaCredentialUpdate {
	_u.mutation.SetCompanyCode(v)
	return _u
}

// SetNillableCompanyCode sets the "company_code" field if the given value is not nil.
func (_u *GaiaCredentialUpdate) SetNillableCompanyCode(v *string) *GaiaCredentialUpdate {
	if v != nil {
		_u.SetCompanyCode(*v)
	}
	return _u
}

// SetEmployeeAccount sets the "employee_account" field.
func (_u *GaiaCredentialUpdate) SetEmployeeAccount(v string) *GaiaCredentialUpdate {
	_u.mutation.SetEmployeeAccount(v)
	return _u
}

// SetNillableEmployeeAccount sets the "employee_account" field if the given value is not nil.
func (_u *GaiaCredentialUpdate) SetNillableEmployeeAccount(v *string) *GaiaCredentialUpdate {
	if v != nil {
		_u.SetEmployeeAccount(*v)
	}
	return _u
}

// SetEncryptedPassword sets the "encrypted_password" field.
func (_u *GaiaCredentialUpdate) SetEncryptedPassword(v string) *GaiaCredentialUpdate {
	_u.mutation.SetEncryptedPassword(v)
	return _u
}

// SetNillableEncryptedPassword sets the "encrypted_password" field if the given value is not nil.
func (_u *GaiaCredentialUpdate) SetNillableEncryptedPassword(v *string) *GaiaCredentialUpdate {
	if v != nil {
		_u.SetEncryptedPassword(*v)
	}
	return _u
}

// SetCredentialStatus sets the "credential_status" field.
func (_u *GaiaCredentialUpdate) SetCredentialStatus(v string) *GaiaCredentialUpdate {
	_u.mutation.SetCredentialStatus(v)
	return _u
}

// SetNillableCredentialStatus sets the "credential_status" field if the given value is not nil.
func (_u *GaiaCredentialUpdate) SetNillableCredentialStatus(v *string) *GaiaCredentialUpdate {
	if v != nil {
		_u.SetCredentialStatus(*v)
	}
	return _u
}

// SetLastLoginAt sets the "last_login_at" field.
func (_u *GaiaCredentialUpdate) SetLastLoginAt(v time.Time) *GaiaCredentialUpdate {
	_u.mutation.SetLastLoginAt(v)
	return _u
}

// SetNillableLastLoginAt sets the "last_login_at" field if the given value is not nil.
func (_u *GaiaCredentialUpdate) SetNillableLastLoginAt(v *time.Time) *GaiaCredentialUpdate {
	if v != nil {
		_u.SetLastLoginAt(*v)
	}
	return _u
}

// ClearLastLoginAt clears the value of the "last_login_at" field.
func (_u *GaiaCredentialUpdate) ClearLastLoginAt() *GaiaCredentialUpdate {
	_u.mutation.ClearLastLoginAt()
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *GaiaCredentialUpdate) SetCreatedAt(v time.Time) *GaiaCredentialUpdate {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *GaiaCredentialUpdate) SetNillableCreatedAt(v *time.Time) *GaiaCredentialUpdate {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *GaiaCredentialUpdate) SetUpdatedAt(v time.Time) *GaiaCredentialUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetUserID sets the "user" edge to the User entity by ID.
func (_u *GaiaCredentialUpdate) SetUserID(id int) *GaiaCredentialUpdate {
	_u.mutation.SetUserID(id)
	return _u
}

// SetUser sets the "user" edge to the User entity.
func (_u *GaiaCredentialUpdate) SetUser(v *User) *GaiaCredentialUpdate {
	return _u.SetUserID(v.ID)
}

// Mutation returns the GaiaCredentialMutation object of the builder.
func (_u *GaiaCredentialUpdate) Mutation() *GaiaCredentialMutation {
	return _u.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (_u *GaiaCredentialUpdate) ClearUser() *GaiaCredentialUpdate {
	_u.mutation.ClearUser()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *GaiaCredentialUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *GaiaCredentialUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *GaiaCredentialUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *GaiaCredentialUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *GaiaCredentialUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := gaiacredential.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *GaiaCredentialUpdate) check() error {
	if v, ok := _u.mutation.EmployeeAccount(); ok {
		if err := gaiacredential.EmployeeAccountValidator(v); err != nil {
			return &ValidationError{Name: "employee_account", err: fmt.Errorf(`ent: validator failed for field "GaiaCredential.employee_account": %w`, err)}
		}
	}
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "GaiaCredential.user"`)
	}
	return nil
}

func (_u *GaiaCredentialUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(gaiacredential.Table, gaiacredential.Columns, sqlgraph.NewFieldSpec(gaiacredential.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.CompanyCode(); ok {
		_spec.SetField(gaiacredential.FieldCompanyCode, field.TypeString, value)
	}
	if value, ok := _u.mutation.EmployeeAccount(); ok {
		_spec.SetField(gaiacredential.FieldEmployeeAccount, field.TypeString, value)
	}
	if value, ok := _u.mutation.EncryptedPassword(); ok {
		_spec.SetField(gaiacredential.FieldEncryptedPassword, field.TypeString, value)
	}
	if value, ok := _u.mutation.CredentialStatus(); ok {
		_spec.SetField(gaiacredential.FieldCredentialStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.LastLoginAt(); ok {
		_spec.SetField(gaiacredential.FieldLastLoginAt, field.TypeTime, value)
	}
	if _u.mutation.LastLoginAtCleared() {
		_spec.ClearField(gaiacredential.FieldLastLoginAt, field.TypeTime)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(gaiacredential.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(gaiacredential.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   gaiacredential.UserTable,
			Columns: []string{gaiacredential.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   gaiacredential.UserTable,
			Columns: []string{gaiacredential.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{gaiacredential.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// GaiaCredentialUpdateOne is the builder for updating a single GaiaCredential entity.
type GaiaCredentialUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *GaiaCredentialMutation
}

// SetCompanyCode sets the "company_code" field.
func (_u *GaiaCredentialUpdateOne) SetCompanyCode(v string) *GaiaCredentialUpdateOne {
	_u.mutation.SetCompanyCode(v)
	return _u
}

// SetNillableCompanyCode sets the "company_code" field if the given value is not nil.
func (_u *GaiaCredentialUpdateOne) SetNillableCompanyCode(v *string) *GaiaCredentialUpdateOne {
	if v != nil {
		_u.SetCompanyCode(*v)
	}
	return _u
}

// SetEmployeeAccount sets the "employee_account" field.
func (_u *GaiaCredentialUpdateOne) SetEmployeeAccount(v string) *GaiaCredentialUpdateOne {
	_u.mutation.SetEmployeeAccount(v)
	return _u
}

// SetNillableEmployeeAccount sets the "employee_account" field if the given value is not nil.
func (_u *GaiaCredentialUpdateOne) SetNillableEmployeeAccount(v *string) *GaiaCredentialUpdateOne {
	if v != nil {
		_u.SetEmployeeAccount(*v)
	}
	return _u
}

// SetEncryptedPassword sets the "encrypted_password" field.
func (_u *GaiaCredentialUpdateOne) SetEncryptedPassword(v string) *GaiaCredentialUpdateOne {
	_u.mutation.SetEncryptedPassword(v)
	return _u
}

// SetNillableEncryptedPassword sets the "encrypted_password" field if the given value is not nil.
func (_u *GaiaCredentialUpdateOne) SetNillableEncryptedPassword(v *string) *GaiaCredentialUpdateOne {
	if v != nil {
		_u.SetEncryptedPassword(*v)
	}
	return _u
}

// SetCredentialStatus sets the "credential_status" field.
func (_u *GaiaCredentialUpdateOne) SetCredentialStatus(v string) *GaiaCredentialUpdateOne {
	_u.mutation.SetCredentialStatus(v)
	return _u
}

// SetNillableCredentialStatus sets the "credential_status" field if the given value is not nil.
func (_u *GaiaCredentialUpdateOne) SetNillableCredentialStatus(v *string) *GaiaCredentialUpdateOne {
	if v != nil {
		_u.SetCredentialStatus(*v)
	}
	return _u
}

// SetLastLoginAt sets the "last_login_at" field.
func (_u *GaiaCredentialUpdateOne) SetLastLoginAt(v time.Time) *GaiaCredentialUpdateOne {
	_u.mutation.SetLastLoginAt(v)
	return _u
}

// SetNillableLastLoginAt sets the "last_login_at" field if the given value is not nil.
func (_u *GaiaCredentialUpdateOne) SetNillableLastLoginAt(v *time.Time) *GaiaCredentialUpdateOne {
	if v != nil {
		_u.SetLastLoginAt(*v)
	}
	return _u
}

// ClearLastLoginAt clears the value of the "last_login_at" field.
func (_u *GaiaCredentialUpdateOne) ClearLastLoginAt() *GaiaCredentialUpdateOne {
	_u.mutation.ClearLastLoginAt()
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *GaiaCredentialUpdateOne) SetCreatedAt(v time.Time) *GaiaCredentialUpdateOne {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *GaiaCredentialUpdateOne) SetNillableCreatedAt(v *time.Time) *GaiaCredentialUpdateOne {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *GaiaCredentialUpdateOne) SetUpdatedAt(v time.Time) *GaiaCredentialUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetUserID sets the "user" edge to the User entity by ID.
func (_u *GaiaCredentialUpdateOne) SetUserID(id int) *GaiaCredentialUpdateOne {
	_u.mutation.SetUserID(id)
	return _u
}

// SetUser sets the "user" edge to the User entity.
func (_u *GaiaCredentialUpdateOne) SetUser(v *User) *GaiaCredentialUpdateOne {
	return _u.SetUserID(v.ID)
}

// Mutation returns the GaiaCredentialMutation object of the builder.
func (_u *GaiaCredentialUpdateOne) Mutation() *GaiaCredentialMutation {
	return _u.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (_u *GaiaCredentialUpdateOne) ClearUser() *GaiaCredentialUpdateOne {
	_u.mutation.ClearUser()
	return _u
}

// Where appends a list predicates to the GaiaCredentialUpdate builder.
func (_u *GaiaCredentialUpdateOne) Where(ps ...predicate.GaiaCredential) *GaiaCredentialUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *GaiaCredentialUpdateOne) Select(field string, fields ...string) *GaiaCredentialUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated GaiaCredential entity.
func (_u *GaiaCredentialUpdateOne) Save(ctx context.Context) (*GaiaCredential, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *GaiaCredentialUpdateOne) SaveX(ctx context.Context) *GaiaCredential {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *GaiaCredentialUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *GaiaCredentialUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *GaiaCredentialUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := gaiacredential.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *GaiaCredentialUpdateOne) check() error {
	if v, ok := _u.mutation.EmployeeAccount(); ok {
		if err := gaiacredential.EmployeeAccountValidator(v); err != nil {
			return &ValidationError{Name: "employee_account", err: fmt.Errorf(`ent: validator failed for field "GaiaCredential.employee_account": %w`, err)}
		}
	}
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "GaiaCredential.user"`)
	}
	return nil
}

func (_u *GaiaCredentialUpdateOne) sqlSave(ctx context.Context) (_node *GaiaCredential, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(gaiacredential.Table, gaiacredential.Columns, sqlgraph.NewFieldSpec(gaiacredential.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "GaiaCredential.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, gaiacredential.FieldID)
		for _, f := range fields {
			if !gaiacredential.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != gaiacredential.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.CompanyCode(); ok {
		_spec.SetField(gaiacredential.FieldCompanyCode, field.TypeString, value)
	}
	if value, ok := _u.mutation.EmployeeAccount(); ok {
		_spec.SetField(gaiacredential.FieldEmployeeAccount, field.TypeString, value)
	}
	if value, ok := _u.mutation.EncryptedPassword(); ok {
		_spec.SetField(gaiacredential.FieldEncryptedPassword, field.TypeString, value)
	}
	if value, ok := _u.mutation.CredentialStatus(); ok {
		_spec.SetField(gaiacredential.FieldCredentialStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.LastLoginAt(); ok {
		_spec.SetField(gaiacredential.FieldLastLoginAt, field.TypeTime, value)
	}
	if _u.mutation.LastLoginAtCleared() {
		_spec.ClearField(gaiacredential.FieldLastLoginAt, field.TypeTime)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(gaiacredential.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(gaiacredential.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   gaiacredential.UserTable,
			Columns: []string{gaiacredential.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   gaiacredential.UserTable,
			Columns: []string{gaiacredential.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &GaiaCredential{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{gaiacredential.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
