// Code generated by ent, DO NOT EDIT.

package ent

import (
	"gaia-calendar/ent/appsession"
	"gaia-calendar/ent/calendarrequestlog"
	"gaia-calendar/ent/calendarsubscription"
	"gaia-calendar/ent/emailverificationcode"
	"gaia-calendar/ent/gaiacredential"
	"gaia-calendar/ent/gaiasession"
	"gaia-calendar/ent/passwordresettoken"
	"gaia-calendar/ent/scheduleentry"
	"gaia-calendar/ent/schedulesyncrun"
	"gaia-calendar/ent/schema"
	"gaia-calendar/ent/user"
	"time"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	appsessionFields := schema.AppSession{}.Fields()
	_ = appsessionFields
	// appsessionDescCreatedAt is the schema descriptor for created_at field.
	appsessionDescCreatedAt := appsessionFields[2].Descriptor()
	// appsession.DefaultCreatedAt holds the default value on creation for the created_at field.
	appsession.DefaultCreatedAt = appsessionDescCreatedAt.Default.(func() time.Time)
	calendarrequestlogFields := schema.CalendarRequestLog{}.Fields()
	_ = calendarrequestlogFields
	// calendarrequestlogDescRequestedAt is the schema descriptor for requested_at field.
	calendarrequestlogDescRequestedAt := calendarrequestlogFields[0].Descriptor()
	// calendarrequestlog.DefaultRequestedAt holds the default value on creation for the requested_at field.
	calendarrequestlog.DefaultRequestedAt = calendarrequestlogDescRequestedAt.Default.(func() time.Time)
	// calendarrequestlogDescUserAgent is the schema descriptor for user_agent field.
	calendarrequestlogDescUserAgent := calendarrequestlogFields[1].Descriptor()
	// calendarrequestlog.DefaultUserAgent holds the default value on creation for the user_agent field.
	calendarrequestlog.DefaultUserAgent = calendarrequestlogDescUserAgent.Default.(string)
	// calendarrequestlogDescRemoteAddr is the schema descriptor for remote_addr field.
	calendarrequestlogDescRemoteAddr := calendarrequestlogFields[2].Descriptor()
	// calendarrequestlog.DefaultRemoteAddr holds the default value on creation for the remote_addr field.
	calendarrequestlog.DefaultRemoteAddr = calendarrequestlogDescRemoteAddr.Default.(string)
	// calendarrequestlogDescPath is the schema descriptor for path field.
	calendarrequestlogDescPath := calendarrequestlogFields[3].Descriptor()
	// calendarrequestlog.DefaultPath holds the default value on creation for the path field.
	calendarrequestlog.DefaultPath = calendarrequestlogDescPath.Default.(string)
	calendarsubscriptionFields := schema.CalendarSubscription{}.Fields()
	_ = calendarsubscriptionFields
	// calendarsubscriptionDescEnabled is the schema descriptor for enabled field.
	calendarsubscriptionDescEnabled := calendarsubscriptionFields[2].Descriptor()
	// calendarsubscription.DefaultEnabled holds the default value on creation for the enabled field.
	calendarsubscription.DefaultEnabled = calendarsubscriptionDescEnabled.Default.(bool)
	// calendarsubscriptionDescCreatedAt is the schema descriptor for created_at field.
	calendarsubscriptionDescCreatedAt := calendarsubscriptionFields[3].Descriptor()
	// calendarsubscription.DefaultCreatedAt holds the default value on creation for the created_at field.
	calendarsubscription.DefaultCreatedAt = calendarsubscriptionDescCreatedAt.Default.(func() time.Time)
	// calendarsubscriptionDescUpdatedAt is the schema descriptor for updated_at field.
	calendarsubscriptionDescUpdatedAt := calendarsubscriptionFields[4].Descriptor()
	// calendarsubscription.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	calendarsubscription.DefaultUpdatedAt = calendarsubscriptionDescUpdatedAt.Default.(func() time.Time)
	// calendarsubscription.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	calendarsubscription.UpdateDefaultUpdatedAt = calendarsubscriptionDescUpdatedAt.UpdateDefault.(func() time.Time)
	emailverificationcodeFields := schema.EmailVerificationCode{}.Fields()
	_ = emailverificationcodeFields
	// emailverificationcodeDescEmail is the schema descriptor for email field.
	emailverificationcodeDescEmail := emailverificationcodeFields[0].Descriptor()
	// emailverificationcode.EmailValidator is a validator for the "email" field. It is called by the builders before save.
	emailverificationcode.EmailValidator = emailverificationcodeDescEmail.Validators[0].(func(string) error)
	// emailverificationcodeDescAttemptCount is the schema descriptor for attempt_count field.
	emailverificationcodeDescAttemptCount := emailverificationcodeFields[4].Descriptor()
	// emailverificationcode.DefaultAttemptCount holds the default value on creation for the attempt_count field.
	emailverificationcode.DefaultAttemptCount = emailverificationcodeDescAttemptCount.Default.(int)
	// emailverificationcodeDescCreatedAt is the schema descriptor for created_at field.
	emailverificationcodeDescCreatedAt := emailverificationcodeFields[5].Descriptor()
	// emailverificationcode.DefaultCreatedAt holds the default value on creation for the created_at field.
	emailverificationcode.DefaultCreatedAt = emailverificationcodeDescCreatedAt.Default.(func() time.Time)
	gaiacredentialFields := schema.GaiaCredential{}.Fields()
	_ = gaiacredentialFields
	// gaiacredentialDescCompanyCode is the schema descriptor for company_code field.
	gaiacredentialDescCompanyCode := gaiacredentialFields[0].Descriptor()
	// gaiacredential.DefaultCompanyCode holds the default value on creation for the company_code field.
	gaiacredential.DefaultCompanyCode = gaiacredentialDescCompanyCode.Default.(string)
	// gaiacredentialDescEmployeeAccount is the schema descriptor for employee_account field.
	gaiacredentialDescEmployeeAccount := gaiacredentialFields[1].Descriptor()
	// gaiacredential.EmployeeAccountValidator is a validator for the "employee_account" field. It is called by the builders before save.
	gaiacredential.EmployeeAccountValidator = gaiacredentialDescEmployeeAccount.Validators[0].(func(string) error)
	// gaiacredentialDescCredentialStatus is the schema descriptor for credential_status field.
	gaiacredentialDescCredentialStatus := gaiacredentialFields[3].Descriptor()
	// gaiacredential.DefaultCredentialStatus holds the default value on creation for the credential_status field.
	gaiacredential.DefaultCredentialStatus = gaiacredentialDescCredentialStatus.Default.(string)
	// gaiacredentialDescCreatedAt is the schema descriptor for created_at field.
	gaiacredentialDescCreatedAt := gaiacredentialFields[5].Descriptor()
	// gaiacredential.DefaultCreatedAt holds the default value on creation for the created_at field.
	gaiacredential.DefaultCreatedAt = gaiacredentialDescCreatedAt.Default.(func() time.Time)
	// gaiacredentialDescUpdatedAt is the schema descriptor for updated_at field.
	gaiacredentialDescUpdatedAt := gaiacredentialFields[6].Descriptor()
	// gaiacredential.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	gaiacredential.DefaultUpdatedAt = gaiacredentialDescUpdatedAt.Default.(func() time.Time)
	// gaiacredential.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	gaiacredential.UpdateDefaultUpdatedAt = gaiacredentialDescUpdatedAt.UpdateDefault.(func() time.Time)
	gaiasessionFields := schema.GaiaSession{}.Fields()
	_ = gaiasessionFields
	// gaiasessionDescCompanyCode is the schema descriptor for company_code field.
	gaiasessionDescCompanyCode := gaiasessionFields[0].Descriptor()
	// gaiasession.DefaultCompanyCode holds the default value on creation for the company_code field.
	gaiasession.DefaultCompanyCode = gaiasessionDescCompanyCode.Default.(string)
	// gaiasessionDescCreatedAt is the schema descriptor for created_at field.
	gaiasessionDescCreatedAt := gaiasessionFields[4].Descriptor()
	// gaiasession.DefaultCreatedAt holds the default value on creation for the created_at field.
	gaiasession.DefaultCreatedAt = gaiasessionDescCreatedAt.Default.(func() time.Time)
	// gaiasessionDescUpdatedAt is the schema descriptor for updated_at field.
	gaiasessionDescUpdatedAt := gaiasessionFields[5].Descriptor()
	// gaiasession.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	gaiasession.DefaultUpdatedAt = gaiasessionDescUpdatedAt.Default.(func() time.Time)
	// gaiasession.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	gaiasession.UpdateDefaultUpdatedAt = gaiasessionDescUpdatedAt.UpdateDefault.(func() time.Time)
	passwordresettokenFields := schema.PasswordResetToken{}.Fields()
	_ = passwordresettokenFields
	// passwordresettokenDescEmail is the schema descriptor for email field.
	passwordresettokenDescEmail := passwordresettokenFields[0].Descriptor()
	// passwordresettoken.EmailValidator is a validator for the "email" field. It is called by the builders before save.
	passwordresettoken.EmailValidator = passwordresettokenDescEmail.Validators[0].(func(string) error)
	// passwordresettokenDescCreatedAt is the schema descriptor for created_at field.
	passwordresettokenDescCreatedAt := passwordresettokenFields[4].Descriptor()
	// passwordresettoken.DefaultCreatedAt holds the default value on creation for the created_at field.
	passwordresettoken.DefaultCreatedAt = passwordresettokenDescCreatedAt.Default.(func() time.Time)
	scheduleentryFields := schema.ScheduleEntry{}.Fields()
	_ = scheduleentryFields
	// scheduleentryDescSyncedAt is the schema descriptor for synced_at field.
	scheduleentryDescSyncedAt := scheduleentryFields[7].Descriptor()
	// scheduleentry.DefaultSyncedAt holds the default value on creation for the synced_at field.
	scheduleentry.DefaultSyncedAt = scheduleentryDescSyncedAt.Default.(func() time.Time)
	// scheduleentryDescCreatedAt is the schema descriptor for created_at field.
	scheduleentryDescCreatedAt := scheduleentryFields[8].Descriptor()
	// scheduleentry.DefaultCreatedAt holds the default value on creation for the created_at field.
	scheduleentry.DefaultCreatedAt = scheduleentryDescCreatedAt.Default.(func() time.Time)
	// scheduleentryDescUpdatedAt is the schema descriptor for updated_at field.
	scheduleentryDescUpdatedAt := scheduleentryFields[9].Descriptor()
	// scheduleentry.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	scheduleentry.DefaultUpdatedAt = scheduleentryDescUpdatedAt.Default.(func() time.Time)
	// scheduleentry.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	scheduleentry.UpdateDefaultUpdatedAt = scheduleentryDescUpdatedAt.UpdateDefault.(func() time.Time)
	schedulesyncrunFields := schema.ScheduleSyncRun{}.Fields()
	_ = schedulesyncrunFields
	// schedulesyncrunDescStartedAt is the schema descriptor for started_at field.
	schedulesyncrunDescStartedAt := schedulesyncrunFields[0].Descriptor()
	// schedulesyncrun.DefaultStartedAt holds the default value on creation for the started_at field.
	schedulesyncrun.DefaultStartedAt = schedulesyncrunDescStartedAt.Default.(func() time.Time)
	// schedulesyncrunDescStatus is the schema descriptor for status field.
	schedulesyncrunDescStatus := schedulesyncrunFields[2].Descriptor()
	// schedulesyncrun.DefaultStatus holds the default value on creation for the status field.
	schedulesyncrun.DefaultStatus = schedulesyncrunDescStatus.Default.(string)
	// schedulesyncrunDescEntryCount is the schema descriptor for entry_count field.
	schedulesyncrunDescEntryCount := schedulesyncrunFields[6].Descriptor()
	// schedulesyncrun.DefaultEntryCount holds the default value on creation for the entry_count field.
	schedulesyncrun.DefaultEntryCount = schedulesyncrunDescEntryCount.Default.(int)
	userFields := schema.User{}.Fields()
	_ = userFields
	// userDescEmail is the schema descriptor for email field.
	userDescEmail := userFields[0].Descriptor()
	// user.EmailValidator is a validator for the "email" field. It is called by the builders before save.
	user.EmailValidator = userDescEmail.Validators[0].(func(string) error)
	// userDescEmailVerified is the schema descriptor for email_verified field.
	userDescEmailVerified := userFields[3].Descriptor()
	// user.DefaultEmailVerified holds the default value on creation for the email_verified field.
	user.DefaultEmailVerified = userDescEmailVerified.Default.(bool)
	// userDescRole is the schema descriptor for role field.
	userDescRole := userFields[4].Descriptor()
	// user.DefaultRole holds the default value on creation for the role field.
	user.DefaultRole = userDescRole.Default.(string)
	// userDescCreatedAt is the schema descriptor for created_at field.
	userDescCreatedAt := userFields[5].Descriptor()
	// user.DefaultCreatedAt holds the default value on creation for the created_at field.
	user.DefaultCreatedAt = userDescCreatedAt.Default.(func() time.Time)
	// userDescUpdatedAt is the schema descriptor for updated_at field.
	userDescUpdatedAt := userFields[6].Descriptor()
	// user.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	user.DefaultUpdatedAt = userDescUpdatedAt.Default.(func() time.Time)
	// user.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	user.UpdateDefaultUpdatedAt = userDescUpdatedAt.UpdateDefault.(func() time.Time)
}
