// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"gaia-calendar/ent/predicate"
	"gaia-calendar/ent/schedulesyncrun"
	"gaia-calendar/ent/user"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// ScheduleSyncRunUpdate is the builder for updating ScheduleSyncRun entities.
type ScheduleSyncRunUpdate struct {
	config
	hooks    []Hook
	mutation *ScheduleSyncRunMutation
}

// Where appends a list predicates to the ScheduleSyncRunUpdate builder.
func (_u *ScheduleSyncRunUpdate) Where(ps ...predicate.ScheduleSyncRun) *ScheduleSyncRunUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetStartedAt sets the "started_at" field.
func (_u *ScheduleSyncRunUpdate) SetStartedAt(v time.Time) *ScheduleSyncRunUpdate {
	_u.mutation.SetStartedAt(v)
	return _u
}

// SetNillableStartedAt sets the "started_at" field if the given value is not nil.
func (_u *ScheduleSyncRunUpdate) SetNillableStartedAt(v *time.Time) *ScheduleSyncRunUpdate {
	if v != nil {
		_u.SetStartedAt(*v)
	}
	return _u
}

// SetFinishedAt sets the "finished_at" field.
func (_u *ScheduleSyncRunUpdate) SetFinishedAt(v time.Time) *ScheduleSyncRunUpdate {
	_u.mutation.SetFinishedAt(v)
	return _u
}

// SetNillableFinishedAt sets the "finished_at" field if the given value is not nil.
func (_u *ScheduleSyncRunUpdate) SetNillableFinishedAt(v *time.Time) *ScheduleSyncRunUpdate {
	if v != nil {
		_u.SetFinishedAt(*v)
	}
	return _u
}

// ClearFinishedAt clears the value of the "finished_at" field.
func (_u *ScheduleSyncRunUpdate) ClearFinishedAt() *ScheduleSyncRunUpdate {
	_u.mutation.ClearFinishedAt()
	return _u
}

// SetStatus sets the "status" field.
func (_u *ScheduleSyncRunUpdate) SetStatus(v string) *ScheduleSyncRunUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *ScheduleSyncRunUpdate) SetNillableStatus(v *string) *ScheduleSyncRunUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetErrorMessage sets the "error_message" field.
func (_u *ScheduleSyncRunUpdate) SetErrorMessage(v string) *ScheduleSyncRunUpdate {
	_u.mutation.SetErrorMessage(v)
	return _u
}

// SetNillableErrorMessage sets the "error_message" field if the given value is not nil.
func (_u *ScheduleSyncRunUpdate) SetNillableErrorMessage(v *string) *ScheduleSyncRunUpdate {
	if v != nil {
		_u.SetErrorMessage(*v)
	}
	return _u
}

// ClearErrorMessage clears the value of the "error_message" field.
func (_u *ScheduleSyncRunUpdate) ClearErrorMessage() *ScheduleSyncRunUpdate {
	_u.mutation.ClearErrorMessage()
	return _u
}

// SetRangeStart sets the "range_start" field.
func (_u *ScheduleSyncRunUpdate) SetRangeStart(v time.Time) *ScheduleSyncRunUpdate {
	_u.mutation.SetRangeStart(v)
	return _u
}

// SetNillableRangeStart sets the "range_start" field if the given value is not nil.
func (_u *ScheduleSyncRunUpdate) SetNillableRangeStart(v *time.Time) *ScheduleSyncRunUpdate {
	if v != nil {
		_u.SetRangeStart(*v)
	}
	return _u
}

// SetRangeEnd sets the "range_end" field.
func (_u *ScheduleSyncRunUpdate) SetRangeEnd(v time.Time) *ScheduleSyncRunUpdate {
	_u.mutation.SetRangeEnd(v)
	return _u
}

// SetNillableRangeEnd sets the "range_end" field if the given value is not nil.
func (_u *ScheduleSyncRunUpdate) SetNillableRangeEnd(v *time.Time) *ScheduleSyncRunUpdate {
	if v != nil {
		_u.SetRangeEnd(*v)
	}
	return _u
}

// SetEntryCount sets the "entry_count" field.
func (_u *ScheduleSyncRunUpdate) SetEntryCount(v int) *ScheduleSyncRunUpdate {
	_u.mutation.ResetEntryCount()
	_u.mutation.SetEntryCount(v)
	return _u
}

// SetNillableEntryCount sets the "entry_count" field if the given value is not nil.
func (_u *ScheduleSyncRunUpdate) SetNillableEntryCount(v *int) *ScheduleSyncRunUpdate {
	if v != nil {
		_u.SetEntryCount(*v)
	}
	return _u
}

// AddEntryCount adds value to the "entry_count" field.
func (_u *ScheduleSyncRunUpdate) AddEntryCount(v int) *ScheduleSyncRunUpdate {
	_u.mutation.AddEntryCount(v)
	return _u
}

// SetMarkedAt sets the "marked_at" field.
func (_u *ScheduleSyncRunUpdate) SetMarkedAt(v time.Time) *ScheduleSyncRunUpdate {
	_u.mutation.SetMarkedAt(v)
	return _u
}

// SetNillableMarkedAt sets the "marked_at" field if the given value is not nil.
func (_u *ScheduleSyncRunUpdate) SetNillableMarkedAt(v *time.Time) *ScheduleSyncRunUpdate {
	if v != nil {
		_u.SetMarkedAt(*v)
	}
	return _u
}

// ClearMarkedAt clears the value of the "marked_at" field.
func (_u *ScheduleSyncRunUpdate) ClearMarkedAt() *ScheduleSyncRunUpdate {
	_u.mutation.ClearMarkedAt()
	return _u
}

// SetUserID sets the "user" edge to the User entity by ID.
func (_u *ScheduleSyncRunUpdate) SetUserID(id int) *ScheduleSyncRunUpdate {
	_u.mutation.SetUserID(id)
	return _u
}

// SetUser sets the "user" edge to the User entity.
func (_u *ScheduleSyncRunUpdate) SetUser(v *User) *ScheduleSyncRunUpdate {
	return _u.SetUserID(v.ID)
}

// Mutation returns the ScheduleSyncRunMutation object of the builder.
func (_u *ScheduleSyncRunUpdate) Mutation() *ScheduleSyncRunMutation {
	return _u.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (_u *ScheduleSyncRunUpdate) ClearUser() *ScheduleSyncRunUpdate {
	_u.mutation.ClearUser()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *ScheduleSyncRunUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ScheduleSyncRunUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *ScheduleSyncRunUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ScheduleSyncRunUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ScheduleSyncRunUpdate) check() error {
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "ScheduleSyncRun.user"`)
	}
	return nil
}

func (_u *ScheduleSyncRunUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(schedulesyncrun.Table, schedulesyncrun.Columns, sqlgraph.NewFieldSpec(schedulesyncrun.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.StartedAt(); ok {
		_spec.SetField(schedulesyncrun.FieldStartedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.FinishedAt(); ok {
		_spec.SetField(schedulesyncrun.FieldFinishedAt, field.TypeTime, value)
	}
	if _u.mutation.FinishedAtCleared() {
		_spec.ClearField(schedulesyncrun.FieldFinishedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(schedulesyncrun.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.ErrorMessage(); ok {
		_spec.SetField(schedulesyncrun.FieldErrorMessage, field.TypeString, value)
	}
	if _u.mutation.ErrorMessageCleared() {
		_spec.ClearField(schedulesyncrun.FieldErrorMessage, field.TypeString)
	}
	if value, ok := _u.mutation.RangeStart(); ok {
		_spec.SetField(schedulesyncrun.FieldRangeStart, field.TypeTime, value)
	}
	if value, ok := _u.mutation.RangeEnd(); ok {
		_spec.SetField(schedulesyncrun.FieldRangeEnd, field.TypeTime, value)
	}
	if value, ok := _u.mutation.EntryCount(); ok {
		_spec.SetField(schedulesyncrun.FieldEntryCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedEntryCount(); ok {
		_spec.AddField(schedulesyncrun.FieldEntryCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.MarkedAt(); ok {
		_spec.SetField(schedulesyncrun.FieldMarkedAt, field.TypeTime, value)
	}
	if _u.mutation.MarkedAtCleared() {
		_spec.ClearField(schedulesyncrun.FieldMarkedAt, field.TypeTime)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   schedulesyncrun.UserTable,
			Columns: []string{schedulesyncrun.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   schedulesyncrun.UserTable,
			Columns: []string{schedulesyncrun.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{schedulesyncrun.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// ScheduleSyncRunUpdateOne is the builder for updating a single ScheduleSyncRun entity.
type ScheduleSyncRunUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ScheduleSyncRunMutation
}

// SetStartedAt sets the "started_at" field.
func (_u *ScheduleSyncRunUpdateOne) SetStartedAt(v time.Time) *ScheduleSyncRunUpdateOne {
	_u.mutation.SetStartedAt(v)
	return _u
}

// SetNillableStartedAt sets the "started_at" field if the given value is not nil.
func (_u *ScheduleSyncRunUpdateOne) SetNillableStartedAt(v *time.Time) *ScheduleSyncRunUpdateOne {
	if v != nil {
		_u.SetStartedAt(*v)
	}
	return _u
}

// SetFinishedAt sets the "finished_at" field.
func (_u *ScheduleSyncRunUpdateOne) SetFinishedAt(v time.Time) *ScheduleSyncRunUpdateOne {
	_u.mutation.SetFinishedAt(v)
	return _u
}

// SetNillableFinishedAt sets the "finished_at" field if the given value is not nil.
func (_u *ScheduleSyncRunUpdateOne) SetNillableFinishedAt(v *time.Time) *ScheduleSyncRunUpdateOne {
	if v != nil {
		_u.SetFinishedAt(*v)
	}
	return _u
}

// ClearFinishedAt clears the value of the "finished_at" field.
func (_u *ScheduleSyncRunUpdateOne) ClearFinishedAt() *ScheduleSyncRunUpdateOne {
	_u.mutation.ClearFinishedAt()
	return _u
}

// SetStatus sets the "status" field.
func (_u *ScheduleSyncRunUpdateOne) SetStatus(v string) *ScheduleSyncRunUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *ScheduleSyncRunUpdateOne) SetNillableStatus(v *string) *ScheduleSyncRunUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetErrorMessage sets the "error_message" field.
func (_u *ScheduleSyncRunUpdateOne) SetErrorMessage(v string) *ScheduleSyncRunUpdateOne {
	_u.mutation.SetErrorMessage(v)
	return _u
}

// SetNillableErrorMessage sets the "error_message" field if the given value is not nil.
func (_u *ScheduleSyncRunUpdateOne) SetNillableErrorMessage(v *string) *ScheduleSyncRunUpdateOne {
	if v != nil {
		_u.SetErrorMessage(*v)
	}
	return _u
}

// ClearErrorMessage clears the value of the "error_message" field.
func (_u *ScheduleSyncRunUpdateOne) ClearErrorMessage() *ScheduleSyncRunUpdateOne {
	_u.mutation.ClearErrorMessage()
	return _u
}

// SetRangeStart sets the "range_start" field.
func (_u *ScheduleSyncRunUpdateOne) SetRangeStart(v time.Time) *ScheduleSyncRunUpdateOne {
	_u.mutation.SetRangeStart(v)
	return _u
}

// SetNillableRangeStart sets the "range_start" field if the given value is not nil.
func (_u *ScheduleSyncRunUpdateOne) SetNillableRangeStart(v *time.Time) *ScheduleSyncRunUpdateOne {
	if v != nil {
		_u.SetRangeStart(*v)
	}
	return _u
}

// SetRangeEnd sets the "range_end" field.
func (_u *ScheduleSyncRunUpdateOne) SetRangeEnd(v time.Time) *ScheduleSyncRunUpdateOne {
	_u.mutation.SetRangeEnd(v)
	return _u
}

// SetNillableRangeEnd sets the "range_end" field if the given value is not nil.
func (_u *ScheduleSyncRunUpdateOne) SetNillableRangeEnd(v *time.Time) *ScheduleSyncRunUpdateOne {
	if v != nil {
		_u.SetRangeEnd(*v)
	}
	return _u
}

// SetEntryCount sets the "entry_count" field.
func (_u *ScheduleSyncRunUpdateOne) SetEntryCount(v int) *ScheduleSyncRunUpdateOne {
	_u.mutation.ResetEntryCount()
	_u.mutation.SetEntryCount(v)
	return _u
}

// SetNillableEntryCount sets the "entry_count" field if the given value is not nil.
func (_u *ScheduleSyncRunUpdateOne) SetNillableEntryCount(v *int) *ScheduleSyncRunUpdateOne {
	if v != nil {
		_u.SetEntryCount(*v)
	}
	return _u
}

// AddEntryCount adds value to the "entry_count" field.
func (_u *ScheduleSyncRunUpdateOne) AddEntryCount(v int) *ScheduleSyncRunUpdateOne {
	_u.mutation.AddEntryCount(v)
	return _u
}

// SetMarkedAt sets the "marked_at" field.
func (_u *ScheduleSyncRunUpdateOne) SetMarkedAt(v time.Time) *ScheduleSyncRunUpdateOne {
	_u.mutation.SetMarkedAt(v)
	return _u
}

// SetNillableMarkedAt sets the "marked_at" field if the given value is not nil.
func (_u *ScheduleSyncRunUpdateOne) SetNillableMarkedAt(v *time.Time) *ScheduleSyncRunUpdateOne {
	if v != nil {
		_u.SetMarkedAt(*v)
	}
	return _u
}

// ClearMarkedAt clears the value of the "marked_at" field.
func (_u *ScheduleSyncRunUpdateOne) ClearMarkedAt() *ScheduleSyncRunUpdateOne {
	_u.mutation.ClearMarkedAt()
	return _u
}

// SetUserID sets the "user" edge to the User entity by ID.
func (_u *ScheduleSyncRunUpdateOne) SetUserID(id int) *ScheduleSyncRunUpdateOne {
	_u.mutation.SetUserID(id)
	return _u
}

// SetUser sets the "user" edge to the User entity.
func (_u *ScheduleSyncRunUpdateOne) SetUser(v *User) *ScheduleSyncRunUpdateOne {
	return _u.SetUserID(v.ID)
}

// Mutation returns the ScheduleSyncRunMutation object of the builder.
func (_u *ScheduleSyncRunUpdateOne) Mutation() *ScheduleSyncRunMutation {
	return _u.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (_u *ScheduleSyncRunUpdateOne) ClearUser() *ScheduleSyncRunUpdateOne {
	_u.mutation.ClearUser()
	return _u
}

// Where appends a list predicates to the ScheduleSyncRunUpdate builder.
func (_u *ScheduleSyncRunUpdateOne) Where(ps ...predicate.ScheduleSyncRun) *ScheduleSyncRunUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *ScheduleSyncRunUpdateOne) Select(field string, fields ...string) *ScheduleSyncRunUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated ScheduleSyncRun entity.
func (_u *ScheduleSyncRunUpdateOne) Save(ctx context.Context) (*ScheduleSyncRun, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ScheduleSyncRunUpdateOne) SaveX(ctx context.Context) *ScheduleSyncRun {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *ScheduleSyncRunUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ScheduleSyncRunUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ScheduleSyncRunUpdateOne) check() error {
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "ScheduleSyncRun.user"`)
	}
	return nil
}

func (_u *ScheduleSyncRunUpdateOne) sqlSave(ctx context.Context) (_node *ScheduleSyncRun, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(schedulesyncrun.Table, schedulesyncrun.Columns, sqlgraph.NewFieldSpec(schedulesyncrun.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "ScheduleSyncRun.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, schedulesyncrun.FieldID)
		for _, f := range fields {
			if !schedulesyncrun.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != schedulesyncrun.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.StartedAt(); ok {
		_spec.SetField(schedulesyncrun.FieldStartedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.FinishedAt(); ok {
		_spec.SetField(schedulesyncrun.FieldFinishedAt, field.TypeTime, value)
	}
	if _u.mutation.FinishedAtCleared() {
		_spec.ClearField(schedulesyncrun.FieldFinishedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(schedulesyncrun.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.ErrorMessage(); ok {
		_spec.SetField(schedulesyncrun.FieldErrorMessage, field.TypeString, value)
	}
	if _u.mutation.ErrorMessageCleared() {
		_spec.ClearField(schedulesyncrun.FieldErrorMessage, field.TypeString)
	}
	if value, ok := _u.mutation.RangeStart(); ok {
		_spec.SetField(schedulesyncrun.FieldRangeStart, field.TypeTime, value)
	}
	if value, ok := _u.mutation.RangeEnd(); ok {
		_spec.SetField(schedulesyncrun.FieldRangeEnd, field.TypeTime, value)
	}
	if value, ok := _u.mutation.EntryCount(); ok {
		_spec.SetField(schedulesyncrun.FieldEntryCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedEntryCount(); ok {
		_spec.AddField(schedulesyncrun.FieldEntryCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.MarkedAt(); ok {
		_spec.SetField(schedulesyncrun.FieldMarkedAt, field.TypeTime, value)
	}
	if _u.mutation.MarkedAtCleared() {
		_spec.ClearField(schedulesyncrun.FieldMarkedAt, field.TypeTime)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   schedulesyncrun.UserTable,
			Columns: []string{schedulesyncrun.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   schedulesyncrun.UserTable,
			Columns: []string{schedulesyncrun.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &ScheduleSyncRun{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{schedulesyncrun.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
