// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"gaia-calendar/ent/schedulesyncrun"
	"gaia-calendar/ent/user"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// ScheduleSyncRun is the model entity for the ScheduleSyncRun schema.
type ScheduleSyncRun struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// StartedAt holds the value of the "started_at" field.
	StartedAt time.Time `json:"started_at,omitempty"`
	// FinishedAt holds the value of the "finished_at" field.
	FinishedAt *time.Time `json:"finished_at,omitempty"`
	// Status holds the value of the "status" field.
	Status string `json:"status,omitempty"`
	// ErrorMessage holds the value of the "error_message" field.
	ErrorMessage *string `json:"error_message,omitempty"`
	// RangeStart holds the value of the "range_start" field.
	RangeStart time.Time `json:"range_start,omitempty"`
	// RangeEnd holds the value of the "range_end" field.
	RangeEnd time.Time `json:"range_end,omitempty"`
	// EntryCount holds the value of the "entry_count" field.
	EntryCount int `json:"entry_count,omitempty"`
	// MarkedAt holds the value of the "marked_at" field.
	MarkedAt *time.Time `json:"marked_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the ScheduleSyncRunQuery when eager-loading is set.
	Edges          ScheduleSyncRunEdges `json:"edges"`
	user_sync_runs *int
	selectValues   sql.SelectValues
}

// ScheduleSyncRunEdges holds the relations/edges for other nodes in the graph.
type ScheduleSyncRunEdges struct {
	// User holds the value of the user edge.
	User *User `json:"user,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// UserOrErr returns the User value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e ScheduleSyncRunEdges) UserOrErr() (*User, error) {
	if e.User != nil {
		return e.User, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: user.Label}
	}
	return nil, &NotLoadedError{edge: "user"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*ScheduleSyncRun) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case schedulesyncrun.FieldID, schedulesyncrun.FieldEntryCount:
			values[i] = new(sql.NullInt64)
		case schedulesyncrun.FieldStatus, schedulesyncrun.FieldErrorMessage:
			values[i] = new(sql.NullString)
		case schedulesyncrun.FieldStartedAt, schedulesyncrun.FieldFinishedAt, schedulesyncrun.FieldRangeStart, schedulesyncrun.FieldRangeEnd, schedulesyncrun.FieldMarkedAt:
			values[i] = new(sql.NullTime)
		case schedulesyncrun.ForeignKeys[0]: // user_sync_runs
			values[i] = new(sql.NullInt64)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the ScheduleSyncRun fields.
func (_m *ScheduleSyncRun) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case schedulesyncrun.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case schedulesyncrun.FieldStartedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field started_at", values[i])
			} else if value.Valid {
				_m.StartedAt = value.Time
			}
		case schedulesyncrun.FieldFinishedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field finished_at", values[i])
			} else if value.Valid {
				_m.FinishedAt = new(time.Time)
				*_m.FinishedAt = value.Time
			}
		case schedulesyncrun.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = value.String
			}
		case schedulesyncrun.FieldErrorMessage:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field error_message", values[i])
			} else if value.Valid {
				_m.ErrorMessage = new(string)
				*_m.ErrorMessage = value.String
			}
		case schedulesyncrun.FieldRangeStart:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field range_start", values[i])
			} else if value.Valid {
				_m.RangeStart = value.Time
			}
		case schedulesyncrun.FieldRangeEnd:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field range_end", values[i])
			} else if value.Valid {
				_m.RangeEnd = value.Time
			}
		case schedulesyncrun.FieldEntryCount:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field entry_count", values[i])
			} else if value.Valid {
				_m.EntryCount = int(value.Int64)
			}
		case schedulesyncrun.FieldMarkedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field marked_at", values[i])
			} else if value.Valid {
				_m.MarkedAt = new(time.Time)
				*_m.MarkedAt = value.Time
			}
		case schedulesyncrun.ForeignKeys[0]:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for edge-field user_sync_runs", value)
			} else if value.Valid {
				_m.user_sync_runs = new(int)
				*_m.user_sync_runs = int(value.Int64)
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the ScheduleSyncRun.
// This includes values selected through modifiers, order, etc.
func (_m *ScheduleSyncRun) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryUser queries the "user" edge of the ScheduleSyncRun entity.
func (_m *ScheduleSyncRun) QueryUser() *UserQuery {
	return NewScheduleSyncRunClient(_m.config).QueryUser(_m)
}

// Update returns a builder for updating this ScheduleSyncRun.
// Note that you need to call ScheduleSyncRun.Unwrap() before calling this method if this ScheduleSyncRun
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *ScheduleSyncRun) Update() *ScheduleSyncRunUpdateOne {
	return NewScheduleSyncRunClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the ScheduleSyncRun entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *ScheduleSyncRun) Unwrap() *ScheduleSyncRun {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: ScheduleSyncRun is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *ScheduleSyncRun) String() string {
	var builder strings.Builder
	builder.WriteString("ScheduleSyncRun(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("started_at=")
	builder.WriteString(_m.StartedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	if v := _m.FinishedAt; v != nil {
		builder.WriteString("finished_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(_m.Status)
	builder.WriteString(", ")
	if v := _m.ErrorMessage; v != nil {
		builder.WriteString("error_message=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("range_start=")
	builder.WriteString(_m.RangeStart.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("range_end=")
	builder.WriteString(_m.RangeEnd.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("entry_count=")
	builder.WriteString(fmt.Sprintf("%v", _m.EntryCount))
	builder.WriteString(", ")
	if v := _m.MarkedAt; v != nil {
		builder.WriteString("marked_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteByte(')')
	return builder.String()
}

// ScheduleSyncRuns is a parsable slice of ScheduleSyncRun.
type ScheduleSyncRuns []*ScheduleSyncRun
