// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"gaia-calendar/ent/schedulesyncrun"
	"gaia-calendar/ent/user"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// ScheduleSyncRunCreate is the builder for creating a ScheduleSyncRun entity.
type ScheduleSyncRunCreate struct {
	config
	mutation *ScheduleSyncRunMutation
	hooks    []Hook
}

// SetStartedAt sets the "started_at" field.
func (_c *ScheduleSyncRunCreate) SetStartedAt(v time.Time) *ScheduleSyncRunCreate {
	_c.mutation.SetStartedAt(v)
	return _c
}

// SetNillableStartedAt sets the "started_at" field if the given value is not nil.
func (_c *ScheduleSyncRunCreate) SetNillableStartedAt(v *time.Time) *ScheduleSyncRunCreate {
	if v != nil {
		_c.SetStartedAt(*v)
	}
	return _c
}

// SetFinishedAt sets the "finished_at" field.
func (_c *ScheduleSyncRunCreate) SetFinishedAt(v time.Time) *ScheduleSyncRunCreate {
	_c.mutation.SetFinishedAt(v)
	return _c
}

// SetNillableFinishedAt sets the "finished_at" field if the given value is not nil.
func (_c *ScheduleSyncRunCreate) SetNillableFinishedAt(v *time.Time) *ScheduleSyncRunCreate {
	if v != nil {
		_c.SetFinishedAt(*v)
	}
	return _c
}

// SetStatus sets the "status" field.
func (_c *ScheduleSyncRunCreate) SetStatus(v string) *ScheduleSyncRunCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *ScheduleSyncRunCreate) SetNillableStatus(v *string) *ScheduleSyncRunCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetErrorMessage sets the "error_message" field.
func (_c *ScheduleSyncRunCreate) SetErrorMessage(v string) *ScheduleSyncRunCreate {
	_c.mutation.SetErrorMessage(v)
	return _c
}

// SetNillableErrorMessage sets the "error_message" field if the given value is not nil.
func (_c *ScheduleSyncRunCreate) SetNillableErrorMessage(v *string) *ScheduleSyncRunCreate {
	if v != nil {
		_c.SetErrorMessage(*v)
	}
	return _c
}

// SetRangeStart sets the "range_start" field.
func (_c *ScheduleSyncRunCreate) SetRangeStart(v time.Time) *ScheduleSyncRunCreate {
	_c.mutation.SetRangeStart(v)
	return _c
}

// SetRangeEnd sets the "range_end" field.
func (_c *ScheduleSyncRunCreate) SetRangeEnd(v time.Time) *ScheduleSyncRunCreate {
	_c.mutation.SetRangeEnd(v)
	return _c
}

// SetEntryCount sets the "entry_count" field.
func (_c *ScheduleSyncRunCreate) SetEntryCount(v int) *ScheduleSyncRunCreate {
	_c.mutation.SetEntryCount(v)
	return _c
}

// SetNillableEntryCount sets the "entry_count" field if the given value is not nil.
func (_c *ScheduleSyncRunCreate) SetNillableEntryCount(v *int) *ScheduleSyncRunCreate {
	if v != nil {
		_c.SetEntryCount(*v)
	}
	return _c
}

// SetMarkedAt sets the "marked_at" field.
func (_c *ScheduleSyncRunCreate) SetMarkedAt(v time.Time) *ScheduleSyncRunCreate {
	_c.mutation.SetMarkedAt(v)
	return _c
}

// SetNillableMarkedAt sets the "marked_at" field if the given value is not nil.
func (_c *ScheduleSyncRunCreate) SetNillableMarkedAt(v *time.Time) *ScheduleSyncRunCreate {
	if v != nil {
		_c.SetMarkedAt(*v)
	}
	return _c
}

// SetUserID sets the "user" edge to the User entity by ID.
func (_c *ScheduleSyncRunCreate) SetUserID(id int) *ScheduleSyncRunCreate {
	_c.mutation.SetUserID(id)
	return _c
}

// SetUser sets the "user" edge to the User entity.
func (_c *ScheduleSyncRunCreate) SetUser(v *User) *ScheduleSyncRunCreate {
	return _c.SetUserID(v.ID)
}

// Mutation returns the ScheduleSyncRunMutation object of the builder.
func (_c *ScheduleSyncRunCreate) Mutation() *ScheduleSyncRunMutation {
	return _c.mutation
}

// Save creates the ScheduleSyncRun in the database.
func (_c *ScheduleSyncRunCreate) Save(ctx context.Context) (*ScheduleSyncRun, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *ScheduleSyncRunCreate) SaveX(ctx context.Context) *ScheduleSyncRun {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ScheduleSyncRunCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ScheduleSyncRunCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *ScheduleSyncRunCreate) defaults() {
	if _, ok := _c.mutation.StartedAt(); !ok {
		v := schedulesyncrun.DefaultStartedAt()
		_c.mutation.SetStartedAt(v)
	}
	if _, ok := _c.mutation.Status(); !ok {
		v := schedulesyncrun.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	if _, ok := _c.mutation.EntryCount(); !ok {
		v := schedulesyncrun.DefaultEntryCount
		_c.mutation.SetEntryCount(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *ScheduleSyncRunCreate) check() error {
	if _, ok := _c.mutation.StartedAt(); !ok {
		return &ValidationError{Name: "started_at", err: errors.New(`ent: missing required field "ScheduleSyncRun.started_at"`)}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "ScheduleSyncRun.status"`)}
	}
	if _, ok := _c.mutation.RangeStart(); !ok {
		return &ValidationError{Name: "range_start", err: errors.New(`ent: missing required field "ScheduleSyncRun.range_start"`)}
	}
	if _, ok := _c.mutation.RangeEnd(); !ok {
		return &ValidationError{Name: "range_end", err: errors.New(`ent: missing required field "ScheduleSyncRun.range_end"`)}
	}
	if _, ok := _c.mutation.EntryCount(); !ok {
		return &ValidationError{Name: "entry_count", err: errors.New(`ent: missing required field "ScheduleSyncRun.entry_count"`)}
	}
	if len(_c.mutation.UserIDs()) == 0 {
		return &ValidationError{Name: "user", err: errors.New(`ent: missing required edge "ScheduleSyncRun.user"`)}
	}
	return nil
}

func (_c *ScheduleSyncRunCreate) sqlSave(ctx context.Context) (*ScheduleSyncRun, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *ScheduleSyncRunCreate) createSpec() (*ScheduleSyncRun, *sqlgraph.CreateSpec) {
	var (
		_node = &ScheduleSyncRun{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(schedulesyncrun.Table, sqlgraph.NewFieldSpec(schedulesyncrun.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.StartedAt(); ok {
		_spec.SetField(schedulesyncrun.FieldStartedAt, field.TypeTime, value)
		_node.StartedAt = value
	}
	if value, ok := _c.mutation.FinishedAt(); ok {
		_spec.SetField(schedulesyncrun.FieldFinishedAt, field.TypeTime, value)
		_node.FinishedAt = &value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(schedulesyncrun.FieldStatus, field.TypeString, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.ErrorMessage(); ok {
		_spec.SetField(schedulesyncrun.FieldErrorMessage, field.TypeString, value)
		_node.ErrorMessage = &value
	}
	if value, ok := _c.mutation.RangeStart(); ok {
		_spec.SetField(schedulesyncrun.FieldRangeStart, field.TypeTime, value)
		_node.RangeStart = value
	}
	if value, ok := _c.mutation.RangeEnd(); ok {
		_spec.SetField(schedulesyncrun.FieldRangeEnd, field.TypeTime, value)
		_node.RangeEnd = value
	}
	if value, ok := _c.mutation.EntryCount(); ok {
		_spec.SetField(schedulesyncrun.FieldEntryCount, field.TypeInt, value)
		_node.EntryCount = value
	}
	if value, ok := _c.mutation.MarkedAt(); ok {
		_spec.SetField(schedulesyncrun.FieldMarkedAt, field.TypeTime, value)
		_node.MarkedAt = &value
	}
	if nodes := _c.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   schedulesyncrun.UserTable,
			Columns: []string{schedulesyncrun.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.user_sync_runs = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// ScheduleSyncRunCreateBulk is the builder for creating many ScheduleSyncRun entities in bulk.
type ScheduleSyncRunCreateBulk struct {
	config
	err      error
	builders []*ScheduleSyncRunCreate
}

// Save creates the ScheduleSyncRun entities in the database.
func (_c *ScheduleSyncRunCreateBulk) Save(ctx context.Context) ([]*ScheduleSyncRun, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*ScheduleSyncRun, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ScheduleSyncRunMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *ScheduleSyncRunCreateBulk) SaveX(ctx context.Context) []*ScheduleSyncRun {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ScheduleSyncRunCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ScheduleSyncRunCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
