// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"gaia-calendar/ent/predicate"
	"gaia-calendar/ent/scheduleentry"
	"gaia-calendar/ent/user"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// ScheduleEntryUpdate is the builder for updating ScheduleEntry entities.
type ScheduleEntryUpdate struct {
	config
	hooks    []Hook
	mutation *ScheduleEntryMutation
}

// Where appends a list predicates to the ScheduleEntryUpdate builder.
func (_u *ScheduleEntryUpdate) Where(ps ...predicate.ScheduleEntry) *ScheduleEntryUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetShiftDate sets the "shift_date" field.
func (_u *ScheduleEntryUpdate) SetShiftDate(v time.Time) *ScheduleEntryUpdate {
	_u.mutation.SetShiftDate(v)
	return _u
}

// SetNillableShiftDate sets the "shift_date" field if the given value is not nil.
func (_u *ScheduleEntryUpdate) SetNillableShiftDate(v *time.Time) *ScheduleEntryUpdate {
	if v != nil {
		_u.SetShiftDate(*v)
	}
	return _u
}

// SetShiftName sets the "shift_name" field.
func (_u *ScheduleEntryUpdate) SetShiftName(v string) *ScheduleEntryUpdate {
	_u.mutation.SetShiftName(v)
	return _u
}

// SetNillableShiftName sets the "shift_name" field if the given value is not nil.
func (_u *ScheduleEntryUpdate) SetNillableShiftName(v *string) *ScheduleEntryUpdate {
	if v != nil {
		_u.SetShiftName(*v)
	}
	return _u
}

// ClearShiftName clears the value of the "shift_name" field.
func (_u *ScheduleEntryUpdate) ClearShiftName() *ScheduleEntryUpdate {
	_u.mutation.ClearShiftName()
	return _u
}

// SetStartTime sets the "start_time" field.
func (_u *ScheduleEntryUpdate) SetStartTime(v time.Time) *ScheduleEntryUpdate {
	_u.mutation.SetStartTime(v)
	return _u
}

// SetNillableStartTime sets the "start_time" field if the given value is not nil.
func (_u *ScheduleEntryUpdate) SetNillableStartTime(v *time.Time) *ScheduleEntryUpdate {
	if v != nil {
		_u.SetStartTime(*v)
	}
	return _u
}

// ClearStartTime clears the value of the "start_time" field.
func (_u *ScheduleEntryUpdate) ClearStartTime() *ScheduleEntryUpdate {
	_u.mutation.ClearStartTime()
	return _u
}

// SetEndTime sets the "end_time" field.
func (_u *ScheduleEntryUpdate) SetEndTime(v time.Time) *ScheduleEntryUpdate {
	_u.mutation.SetEndTime(v)
	return _u
}

// SetNillableEndTime sets the "end_time" field if the given value is not nil.
func (_u *ScheduleEntryUpdate) SetNillableEndTime(v *time.Time) *ScheduleEntryUpdate {
	if v != nil {
		_u.SetEndTime(*v)
	}
	return _u
}

// ClearEndTime clears the value of the "end_time" field.
func (_u *ScheduleEntryUpdate) ClearEndTime() *ScheduleEntryUpdate {
	_u.mutation.ClearEndTime()
	return _u
}

// SetHours sets the "hours" field.
func (_u *ScheduleEntryUpdate) SetHours(v float64) *ScheduleEntryUpdate {
	_u.mutation.ResetHours()
	_u.mutation.SetHours(v)
	return _u
}

// SetNillableHours sets the "hours" field if the given value is not nil.
func (_u *ScheduleEntryUpdate) SetNillableHours(v *float64) *ScheduleEntryUpdate {
	if v != nil {
		_u.SetHours(*v)
	}
	return _u
}

// AddHours adds value to the "hours" field.
func (_u *ScheduleEntryUpdate) AddHours(v float64) *ScheduleEntryUpdate {
	_u.mutation.AddHours(v)
	return _u
}

// ClearHours clears the value of the "hours" field.
func (_u *ScheduleEntryUpdate) ClearHours() *ScheduleEntryUpdate {
	_u.mutation.ClearHours()
	return _u
}

// SetClassCode sets the "class_code" field.
func (_u *ScheduleEntryUpdate) SetClassCode(v string) *ScheduleEntryUpdate {
	_u.mutation.SetClassCode(v)
	return _u
}

// SetNillableClassCode sets the "class_code" field if the given value is not nil.
func (_u *ScheduleEntryUpdate) SetNillableClassCode(v *string) *ScheduleEntryUpdate {
	if v != nil {
		_u.SetClassCode(*v)
	}
	return _u
}

// ClearClassCode clears the value of the "class_code" field.
func (_u *ScheduleEntryUpdate) ClearClassCode() *ScheduleEntryUpdate {
	_u.mutation.ClearClassCode()
	return _u
}

// SetRawJSON sets the "raw_json" field.
func (_u *ScheduleEntryUpdate) SetRawJSON(v string) *ScheduleEntryUpdate {
	_u.mutation.SetRawJSON(v)
	return _u
}

// SetNillableRawJSON sets the "raw_json" field if the given value is not nil.
func (_u *ScheduleEntryUpdate) SetNillableRawJSON(v *string) *ScheduleEntryUpdate {
	if v != nil {
		_u.SetRawJSON(*v)
	}
	return _u
}

// ClearRawJSON clears the value of the "raw_json" field.
func (_u *ScheduleEntryUpdate) ClearRawJSON() *ScheduleEntryUpdate {
	_u.mutation.ClearRawJSON()
	return _u
}

// SetSyncedAt sets the "synced_at" field.
func (_u *ScheduleEntryUpdate) SetSyncedAt(v time.Time) *ScheduleEntryUpdate {
	_u.mutation.SetSyncedAt(v)
	return _u
}

// SetNillableSyncedAt sets the "synced_at" field if the given value is not nil.
func (_u *ScheduleEntryUpdate) SetNillableSyncedAt(v *time.Time) *ScheduleEntryUpdate {
	if v != nil {
		_u.SetSyncedAt(*v)
	}
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *ScheduleEntryUpdate) SetCreatedAt(v time.Time) *ScheduleEntryUpdate {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *ScheduleEntryUpdate) SetNillableCreatedAt(v *time.Time) *ScheduleEntryUpdate {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *ScheduleEntryUpdate) SetUpdatedAt(v time.Time) *ScheduleEntryUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetUserID sets the "user" edge to the User entity by ID.
func (_u *ScheduleEntryUpdate) SetUserID(id int) *ScheduleEntryUpdate {
	_u.mutation.SetUserID(id)
	return _u
}

// SetUser sets the "user" edge to the User entity.
func (_u *ScheduleEntryUpdate) SetUser(v *User) *ScheduleEntryUpdate {
	return _u.SetUserID(v.ID)
}

// Mutation returns the ScheduleEntryMutation object of the builder.
func (_u *ScheduleEntryUpdate) Mutation() *ScheduleEntryMutation {
	return _u.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (_u *ScheduleEntryUpdate) ClearUser() *ScheduleEntryUpdate {
	_u.mutation.ClearUser()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *ScheduleEntryUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ScheduleEntryUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *ScheduleEntryUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ScheduleEntryUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *ScheduleEntryUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := scheduleentry.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ScheduleEntryUpdate) check() error {
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "ScheduleEntry.user"`)
	}
	return nil
}

func (_u *ScheduleEntryUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(scheduleentry.Table, scheduleentry.Columns, sqlgraph.NewFieldSpec(scheduleentry.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.ShiftDate(); ok {
		_spec.SetField(scheduleentry.FieldShiftDate, field.TypeTime, value)
	}
	if value, ok := _u.mutation.ShiftName(); ok {
		_spec.SetField(scheduleentry.FieldShiftName, field.TypeString, value)
	}
	if _u.mutation.ShiftNameCleared() {
		_spec.ClearField(scheduleentry.FieldShiftName, field.TypeString)
	}
	if value, ok := _u.mutation.StartTime(); ok {
		_spec.SetField(scheduleentry.FieldStartTime, field.TypeTime, value)
	}
	if _u.mutation.StartTimeCleared() {
		_spec.ClearField(scheduleentry.FieldStartTime, field.TypeTime)
	}
	if value, ok := _u.mutation.EndTime(); ok {
		_spec.SetField(scheduleentry.FieldEndTime, field.TypeTime, value)
	}
	if _u.mutation.EndTimeCleared() {
		_spec.ClearField(scheduleentry.FieldEndTime, field.TypeTime)
	}
	if value, ok := _u.mutation.Hours(); ok {
		_spec.SetField(scheduleentry.FieldHours, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedHours(); ok {
		_spec.AddField(scheduleentry.FieldHours, field.TypeFloat64, value)
	}
	if _u.mutation.HoursCleared() {
		_spec.ClearField(scheduleentry.FieldHours, field.TypeFloat64)
	}
	if value, ok := _u.mutation.ClassCode(); ok {
		_spec.SetField(scheduleentry.FieldClassCode, field.TypeString, value)
	}
	if _u.mutation.ClassCodeCleared() {
		_spec.ClearField(scheduleentry.FieldClassCode, field.TypeString)
	}
	if value, ok := _u.mutation.RawJSON(); ok {
		_spec.SetField(scheduleentry.FieldRawJSON, field.TypeString, value)
	}
	if _u.mutation.RawJSONCleared() {
		_spec.ClearField(scheduleentry.FieldRawJSON, field.TypeString)
	}
	if value, ok := _u.mutation.SyncedAt(); ok {
		_spec.SetField(scheduleentry.FieldSyncedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(scheduleentry.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(scheduleentry.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   scheduleentry.UserTable,
			Columns: []string{scheduleentry.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   scheduleentry.UserTable,
			Columns: []string{scheduleentry.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{scheduleentry.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// ScheduleEntryUpdateOne is the builder for updating a single ScheduleEntry entity.
type ScheduleEntryUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ScheduleEntryMutation
}

// SetShiftDate sets the "shift_date" field.
func (_u *ScheduleEntryUpdateOne) SetShiftDate(v time.Time) *ScheduleEntryUpdateOne {
	_u.mutation.SetShiftDate(v)
	return _u
}

// SetNillableShiftDate sets the "shift_date" field if the given value is not nil.
func (_u *ScheduleEntryUpdateOne) SetNillableShiftDate(v *time.Time) *ScheduleEntryUpdateOne {
	if v != nil {
		_u.SetShiftDate(*v)
	}
	return _u
}

// SetShiftName sets the "shift_name" field.
func (_u *ScheduleEntryUpdateOne) SetShiftName(v string) *ScheduleEntryUpdateOne {
	_u.mutation.SetShiftName(v)
	return _u
}

// SetNillableShiftName sets the "shift_name" field if the given value is not nil.
func (_u *ScheduleEntryUpdateOne) SetNillableShiftName(v *string) *ScheduleEntryUpdateOne {
	if v != nil {
		_u.SetShiftName(*v)
	}
	return _u
}

// ClearShiftName clears the value of the "shift_name" field.
func (_u *ScheduleEntryUpdateOne) ClearShiftName() *ScheduleEntryUpdateOne {
	_u.mutation.ClearShiftName()
	return _u
}

// SetStartTime sets the "start_time" field.
func (_u *ScheduleEntryUpdateOne) SetStartTime(v time.Time) *ScheduleEntryUpdateOne {
	_u.mutation.SetStartTime(v)
	return _u
}

// SetNillableStartTime sets the "start_time" field if the given value is not nil.
func (_u *ScheduleEntryUpdateOne) SetNillableStartTime(v *time.Time) *ScheduleEntryUpdateOne {
	if v != nil {
		_u.SetStartTime(*v)
	}
	return _u
}

// ClearStartTime clears the value of the "start_time" field.
func (_u *ScheduleEntryUpdateOne) ClearStartTime() *ScheduleEntryUpdateOne {
	_u.mutation.ClearStartTime()
	return _u
}

// SetEndTime sets the "end_time" field.
func (_u *ScheduleEntryUpdateOne) SetEndTime(v time.Time) *ScheduleEntryUpdateOne {
	_u.mutation.SetEndTime(v)
	return _u
}

// SetNillableEndTime sets the "end_time" field if the given value is not nil.
func (_u *ScheduleEntryUpdateOne) SetNillableEndTime(v *time.Time) *ScheduleEntryUpdateOne {
	if v != nil {
		_u.SetEndTime(*v)
	}
	return _u
}

// ClearEndTime clears the value of the "end_time" field.
func (_u *ScheduleEntryUpdateOne) ClearEndTime() *ScheduleEntryUpdateOne {
	_u.mutation.ClearEndTime()
	return _u
}

// SetHours sets the "hours" field.
func (_u *ScheduleEntryUpdateOne) SetHours(v float64) *ScheduleEntryUpdateOne {
	_u.mutation.ResetHours()
	_u.mutation.SetHours(v)
	return _u
}

// SetNillableHours sets the "hours" field if the given value is not nil.
func (_u *ScheduleEntryUpdateOne) SetNillableHours(v *float64) *ScheduleEntryUpdateOne {
	if v != nil {
		_u.SetHours(*v)
	}
	return _u
}

// AddHours adds value to the "hours" field.
func (_u *ScheduleEntryUpdateOne) AddHours(v float64) *ScheduleEntryUpdateOne {
	_u.mutation.AddHours(v)
	return _u
}

// ClearHours clears the value of the "hours" field.
func (_u *ScheduleEntryUpdateOne) ClearHours() *ScheduleEntryUpdateOne {
	_u.mutation.ClearHours()
	return _u
}

// SetClassCode sets the "class_code" field.
func (_u *ScheduleEntryUpdateOne) SetClassCode(v string) *ScheduleEntryUpdateOne {
	_u.mutation.SetClassCode(v)
	return _u
}

// SetNillableClassCode sets the "class_code" field if the given value is not nil.
func (_u *ScheduleEntryUpdateOne) SetNillableClassCode(v *string) *ScheduleEntryUpdateOne {
	if v != nil {
		_u.SetClassCode(*v)
	}
	return _u
}

// ClearClassCode clears the value of the "class_code" field.
func (_u *ScheduleEntryUpdateOne) ClearClassCode() *ScheduleEntryUpdateOne {
	_u.mutation.ClearClassCode()
	return _u
}

// SetRawJSON sets the "raw_json" field.
func (_u *ScheduleEntryUpdateOne) SetRawJSON(v string) *ScheduleEntryUpdateOne {
	_u.mutation.SetRawJSON(v)
	return _u
}

// SetNillableRawJSON sets the "raw_json" field if the given value is not nil.
func (_u *ScheduleEntryUpdateOne) SetNillableRawJSON(v *string) *ScheduleEntryUpdateOne {
	if v != nil {
		_u.SetRawJSON(*v)
	}
	return _u
}

// ClearRawJSON clears the value of the "raw_json" field.
func (_u *ScheduleEntryUpdateOne) ClearRawJSON() *ScheduleEntryUpdateOne {
	_u.mutation.ClearRawJSON()
	return _u
}

// SetSyncedAt sets the "synced_at" field.
func (_u *ScheduleEntryUpdateOne) SetSyncedAt(v time.Time) *ScheduleEntryUpdateOne {
	_u.mutation.SetSyncedAt(v)
	return _u
}

// SetNillableSyncedAt sets the "synced_at" field if the given value is not nil.
func (_u *ScheduleEntryUpdateOne) SetNillableSyncedAt(v *time.Time) *ScheduleEntryUpdateOne {
	if v != nil {
		_u.SetSyncedAt(*v)
	}
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *ScheduleEntryUpdateOne) SetCreatedAt(v time.Time) *ScheduleEntryUpdateOne {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *ScheduleEntryUpdateOne) SetNillableCreatedAt(v *time.Time) *ScheduleEntryUpdateOne {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *ScheduleEntryUpdateOne) SetUpdatedAt(v time.Time) *ScheduleEntryUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetUserID sets the "user" edge to the User entity by ID.
func (_u *ScheduleEntryUpdateOne) SetUserID(id int) *ScheduleEntryUpdateOne {
	_u.mutation.SetUserID(id)
	return _u
}

// SetUser sets the "user" edge to the User entity.
func (_u *ScheduleEntryUpdateOne) SetUser(v *User) *ScheduleEntryUpdateOne {
	return _u.SetUserID(v.ID)
}

// Mutation returns the ScheduleEntryMutation object of the builder.
func (_u *ScheduleEntryUpdateOne) Mutation() *ScheduleEntryMutation {
	return _u.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (_u *ScheduleEntryUpdateOne) ClearUser() *ScheduleEntryUpdateOne {
	_u.mutation.ClearUser()
	return _u
}

// Where appends a list predicates to the ScheduleEntryUpdate builder.
func (_u *ScheduleEntryUpdateOne) Where(ps ...predicate.ScheduleEntry) *ScheduleEntryUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *ScheduleEntryUpdateOne) Select(field string, fields ...string) *ScheduleEntryUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated ScheduleEntry entity.
func (_u *ScheduleEntryUpdateOne) Save(ctx context.Context) (*ScheduleEntry, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ScheduleEntryUpdateOne) SaveX(ctx context.Context) *ScheduleEntry {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *ScheduleEntryUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ScheduleEntryUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *ScheduleEntryUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := scheduleentry.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ScheduleEntryUpdateOne) check() error {
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "ScheduleEntry.user"`)
	}
	return nil
}

func (_u *ScheduleEntryUpdateOne) sqlSave(ctx context.Context) (_node *ScheduleEntry, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(scheduleentry.Table, scheduleentry.Columns, sqlgraph.NewFieldSpec(scheduleentry.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "ScheduleEntry.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, scheduleentry.FieldID)
		for _, f := range fields {
			if !scheduleentry.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != scheduleentry.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.ShiftDate(); ok {
		_spec.SetField(scheduleentry.FieldShiftDate, field.TypeTime, value)
	}
	if value, ok := _u.mutation.ShiftName(); ok {
		_spec.SetField(scheduleentry.FieldShiftName, field.TypeString, value)
	}
	if _u.mutation.ShiftNameCleared() {
		_spec.ClearField(scheduleentry.FieldShiftName, field.TypeString)
	}
	if value, ok := _u.mutation.StartTime(); ok {
		_spec.SetField(scheduleentry.FieldStartTime, field.TypeTime, value)
	}
	if _u.mutation.StartTimeCleared() {
		_spec.ClearField(scheduleentry.FieldStartTime, field.TypeTime)
	}
	if value, ok := _u.mutation.EndTime(); ok {
		_spec.SetField(scheduleentry.FieldEndTime, field.TypeTime, value)
	}
	if _u.mutation.EndTimeCleared() {
		_spec.ClearField(scheduleentry.FieldEndTime, field.TypeTime)
	}
	if value, ok := _u.mutation.Hours(); ok {
		_spec.SetField(scheduleentry.FieldHours, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedHours(); ok {
		_spec.AddField(scheduleentry.FieldHours, field.TypeFloat64, value)
	}
	if _u.mutation.HoursCleared() {
		_spec.ClearField(scheduleentry.FieldHours, field.TypeFloat64)
	}
	if value, ok := _u.mutation.ClassCode(); ok {
		_spec.SetField(scheduleentry.FieldClassCode, field.TypeString, value)
	}
	if _u.mutation.ClassCodeCleared() {
		_spec.ClearField(scheduleentry.FieldClassCode, field.TypeString)
	}
	if value, ok := _u.mutation.RawJSON(); ok {
		_spec.SetField(scheduleentry.FieldRawJSON, field.TypeString, value)
	}
	if _u.mutation.RawJSONCleared() {
		_spec.ClearField(scheduleentry.FieldRawJSON, field.TypeString)
	}
	if value, ok := _u.mutation.SyncedAt(); ok {
		_spec.SetField(scheduleentry.FieldSyncedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(scheduleentry.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(scheduleentry.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   scheduleentry.UserTable,
			Columns: []string{scheduleentry.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   scheduleentry.UserTable,
			Columns: []string{scheduleentry.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &ScheduleEntry{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{scheduleentry.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
