// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"gaia-calendar/ent/scheduleentry"
	"gaia-calendar/ent/user"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// ScheduleEntryCreate is the builder for creating a ScheduleEntry entity.
type ScheduleEntryCreate struct {
	config
	mutation *ScheduleEntryMutation
	hooks    []Hook
}

// SetShiftDate sets the "shift_date" field.
func (_c *ScheduleEntryCreate) SetShiftDate(v time.Time) *ScheduleEntryCreate {
	_c.mutation.SetShiftDate(v)
	return _c
}

// SetShiftName sets the "shift_name" field.
func (_c *ScheduleEntryCreate) SetShiftName(v string) *ScheduleEntryCreate {
	_c.mutation.SetShiftName(v)
	return _c
}

// SetNillableShiftName sets the "shift_name" field if the given value is not nil.
func (_c *ScheduleEntryCreate) SetNillableShiftName(v *string) *ScheduleEntryCreate {
	if v != nil {
		_c.SetShiftName(*v)
	}
	return _c
}

// SetStartTime sets the "start_time" field.
func (_c *ScheduleEntryCreate) SetStartTime(v time.Time) *ScheduleEntryCreate {
	_c.mutation.SetStartTime(v)
	return _c
}

// SetNillableStartTime sets the "start_time" field if the given value is not nil.
func (_c *ScheduleEntryCreate) SetNillableStartTime(v *time.Time) *ScheduleEntryCreate {
	if v != nil {
		_c.SetStartTime(*v)
	}
	return _c
}

// SetEndTime sets the "end_time" field.
func (_c *ScheduleEntryCreate) SetEndTime(v time.Time) *ScheduleEntryCreate {
	_c.mutation.SetEndTime(v)
	return _c
}

// SetNillableEndTime sets the "end_time" field if the given value is not nil.
func (_c *ScheduleEntryCreate) SetNillableEndTime(v *time.Time) *ScheduleEntryCreate {
	if v != nil {
		_c.SetEndTime(*v)
	}
	return _c
}

// SetHours sets the "hours" field.
func (_c *ScheduleEntryCreate) SetHours(v float64) *ScheduleEntryCreate {
	_c.mutation.SetHours(v)
	return _c
}

// SetNillableHours sets the "hours" field if the given value is not nil.
func (_c *ScheduleEntryCreate) SetNillableHours(v *float64) *ScheduleEntryCreate {
	if v != nil {
		_c.SetHours(*v)
	}
	return _c
}

// SetClassCode sets the "class_code" field.
func (_c *ScheduleEntryCreate) SetClassCode(v string) *ScheduleEntryCreate {
	_c.mutation.SetClassCode(v)
	return _c
}

// SetNillableClassCode sets the "class_code" field if the given value is not nil.
func (_c *ScheduleEntryCreate) SetNillableClassCode(v *string) *ScheduleEntryCreate {
	if v != nil {
		_c.SetClassCode(*v)
	}
	return _c
}

// SetRawJSON sets the "raw_json" field.
func (_c *ScheduleEntryCreate) SetRawJSON(v string) *ScheduleEntryCreate {
	_c.mutation.SetRawJSON(v)
	return _c
}

// SetNillableRawJSON sets the "raw_json" field if the given value is not nil.
func (_c *ScheduleEntryCreate) SetNillableRawJSON(v *string) *ScheduleEntryCreate {
	if v != nil {
		_c.SetRawJSON(*v)
	}
	return _c
}

// SetSyncedAt sets the "synced_at" field.
func (_c *ScheduleEntryCreate) SetSyncedAt(v time.Time) *ScheduleEntryCreate {
	_c.mutation.SetSyncedAt(v)
	return _c
}

// SetNillableSyncedAt sets the "synced_at" field if the given value is not nil.
func (_c *ScheduleEntryCreate) SetNillableSyncedAt(v *time.Time) *ScheduleEntryCreate {
	if v != nil {
		_c.SetSyncedAt(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *ScheduleEntryCreate) SetCreatedAt(v time.Time) *ScheduleEntryCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *ScheduleEntryCreate) SetNillableCreatedAt(v *time.Time) *ScheduleEntryCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *ScheduleEntryCreate) SetUpdatedAt(v time.Time) *ScheduleEntryCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *ScheduleEntryCreate) SetNillableUpdatedAt(v *time.Time) *ScheduleEntryCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetUserID sets the "user" edge to the User entity by ID.
func (_c *ScheduleEntryCreate) SetUserID(id int) *ScheduleEntryCreate {
	_c.mutation.SetUserID(id)
	return _c
}

// SetUser sets the "user" edge to the User entity.
func (_c *ScheduleEntryCreate) SetUser(v *User) *ScheduleEntryCreate {
	return _c.SetUserID(v.ID)
}

// Mutation returns the ScheduleEntryMutation object of the builder.
func (_c *ScheduleEntryCreate) Mutation() *ScheduleEntryMutation {
	return _c.mutation
}

// Save creates the ScheduleEntry in the database.
func (_c *ScheduleEntryCreate) Save(ctx context.Context) (*ScheduleEntry, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *ScheduleEntryCreate) SaveX(ctx context.Context) *ScheduleEntry {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ScheduleEntryCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ScheduleEntryCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *ScheduleEntryCreate) defaults() {
	if _, ok := _c.mutation.SyncedAt(); !ok {
		v := scheduleentry.DefaultSyncedAt()
		_c.mutation.SetSyncedAt(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := scheduleentry.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := scheduleentry.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *ScheduleEntryCreate) check() error {
	if _, ok := _c.mutation.ShiftDate(); !ok {
		return &ValidationError{Name: "shift_date", err: errors.New(`ent: missing required field "ScheduleEntry.shift_date"`)}
	}
	if _, ok := _c.mutation.SyncedAt(); !ok {
		return &ValidationError{Name: "synced_at", err: errors.New(`ent: missing required field "ScheduleEntry.synced_at"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "ScheduleEntry.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "ScheduleEntry.updated_at"`)}
	}
	if len(_c.mutation.UserIDs()) == 0 {
		return &ValidationError{Name: "user", err: errors.New(`ent: missing required edge "ScheduleEntry.user"`)}
	}
	return nil
}

func (_c *ScheduleEntryCreate) sqlSave(ctx context.Context) (*ScheduleEntry, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *ScheduleEntryCreate) createSpec() (*ScheduleEntry, *sqlgraph.CreateSpec) {
	var (
		_node = &ScheduleEntry{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(scheduleentry.Table, sqlgraph.NewFieldSpec(scheduleentry.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.ShiftDate(); ok {
		_spec.SetField(scheduleentry.FieldShiftDate, field.TypeTime, value)
		_node.ShiftDate = value
	}
	if value, ok := _c.mutation.ShiftName(); ok {
		_spec.SetField(scheduleentry.FieldShiftName, field.TypeString, value)
		_node.ShiftName = &value
	}
	if value, ok := _c.mutation.StartTime(); ok {
		_spec.SetField(scheduleentry.FieldStartTime, field.TypeTime, value)
		_node.StartTime = &value
	}
	if value, ok := _c.mutation.EndTime(); ok {
		_spec.SetField(scheduleentry.FieldEndTime, field.TypeTime, value)
		_node.EndTime = &value
	}
	if value, ok := _c.mutation.Hours(); ok {
		_spec.SetField(scheduleentry.FieldHours, field.TypeFloat64, value)
		_node.Hours = &value
	}
	if value, ok := _c.mutation.ClassCode(); ok {
		_spec.SetField(scheduleentry.FieldClassCode, field.TypeString, value)
		_node.ClassCode = &value
	}
	if value, ok := _c.mutation.RawJSON(); ok {
		_spec.SetField(scheduleentry.FieldRawJSON, field.TypeString, value)
		_node.RawJSON = value
	}
	if value, ok := _c.mutation.SyncedAt(); ok {
		_spec.SetField(scheduleentry.FieldSyncedAt, field.TypeTime, value)
		_node.SyncedAt = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(scheduleentry.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(scheduleentry.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if nodes := _c.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   scheduleentry.UserTable,
			Columns: []string{scheduleentry.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.user_schedule_entries = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// ScheduleEntryCreateBulk is the builder for creating many ScheduleEntry entities in bulk.
type ScheduleEntryCreateBulk struct {
	config
	err      error
	builders []*ScheduleEntryCreate
}

// Save creates the ScheduleEntry entities in the database.
func (_c *ScheduleEntryCreateBulk) Save(ctx context.Context) ([]*ScheduleEntry, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*ScheduleEntry, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ScheduleEntryMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *ScheduleEntryCreateBulk) SaveX(ctx context.Context) []*ScheduleEntry {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ScheduleEntryCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ScheduleEntryCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
