// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"gaia-calendar/ent/scheduleentry"
	"gaia-calendar/ent/user"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// ScheduleEntry is the model entity for the ScheduleEntry schema.
type ScheduleEntry struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// ShiftDate holds the value of the "shift_date" field.
	ShiftDate time.Time `json:"shift_date,omitempty"`
	// ShiftName holds the value of the "shift_name" field.
	ShiftName *string `json:"shift_name,omitempty"`
	// StartTime holds the value of the "start_time" field.
	StartTime *time.Time `json:"start_time,omitempty"`
	// EndTime holds the value of the "end_time" field.
	EndTime *time.Time `json:"end_time,omitempty"`
	// Hours holds the value of the "hours" field.
	Hours *float64 `json:"hours,omitempty"`
	// ClassCode holds the value of the "class_code" field.
	ClassCode *string `json:"class_code,omitempty"`
	// RawJSON holds the value of the "raw_json" field.
	RawJSON string `json:"-"`
	// SyncedAt holds the value of the "synced_at" field.
	SyncedAt time.Time `json:"synced_at,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the ScheduleEntryQuery when eager-loading is set.
	Edges                 ScheduleEntryEdges `json:"edges"`
	user_schedule_entries *int
	selectValues          sql.SelectValues
}

// ScheduleEntryEdges holds the relations/edges for other nodes in the graph.
type ScheduleEntryEdges struct {
	// User holds the value of the user edge.
	User *User `json:"user,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// UserOrErr returns the User value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e ScheduleEntryEdges) UserOrErr() (*User, error) {
	if e.User != nil {
		return e.User, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: user.Label}
	}
	return nil, &NotLoadedError{edge: "user"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*ScheduleEntry) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case scheduleentry.FieldHours:
			values[i] = new(sql.NullFloat64)
		case scheduleentry.FieldID:
			values[i] = new(sql.NullInt64)
		case scheduleentry.FieldShiftName, scheduleentry.FieldClassCode, scheduleentry.FieldRawJSON:
			values[i] = new(sql.NullString)
		case scheduleentry.FieldShiftDate, scheduleentry.FieldStartTime, scheduleentry.FieldEndTime, scheduleentry.FieldSyncedAt, scheduleentry.FieldCreatedAt, scheduleentry.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		case scheduleentry.ForeignKeys[0]: // user_schedule_entries
			values[i] = new(sql.NullInt64)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the ScheduleEntry fields.
func (_m *ScheduleEntry) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case scheduleentry.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case scheduleentry.FieldShiftDate:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field shift_date", values[i])
			} else if value.Valid {
				_m.ShiftDate = value.Time
			}
		case scheduleentry.FieldShiftName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field shift_name", values[i])
			} else if value.Valid {
				_m.ShiftName = new(string)
				*_m.ShiftName = value.String
			}
		case scheduleentry.FieldStartTime:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field start_time", values[i])
			} else if value.Valid {
				_m.StartTime = new(time.Time)
				*_m.StartTime = value.Time
			}
		case scheduleentry.FieldEndTime:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field end_time", values[i])
			} else if value.Valid {
				_m.EndTime = new(time.Time)
				*_m.EndTime = value.Time
			}
		case scheduleentry.FieldHours:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field hours", values[i])
			} else if value.Valid {
				_m.Hours = new(float64)
				*_m.Hours = value.Float64
			}
		case scheduleentry.FieldClassCode:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field class_code", values[i])
			} else if value.Valid {
				_m.ClassCode = new(string)
				*_m.ClassCode = value.String
			}
		case scheduleentry.FieldRawJSON:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field raw_json", values[i])
			} else if value.Valid {
				_m.RawJSON = value.String
			}
		case scheduleentry.FieldSyncedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field synced_at", values[i])
			} else if value.Valid {
				_m.SyncedAt = value.Time
			}
		case scheduleentry.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case scheduleentry.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case scheduleentry.ForeignKeys[0]:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for edge-field user_schedule_entries", value)
			} else if value.Valid {
				_m.user_schedule_entries = new(int)
				*_m.user_schedule_entries = int(value.Int64)
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the ScheduleEntry.
// This includes values selected through modifiers, order, etc.
func (_m *ScheduleEntry) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryUser queries the "user" edge of the ScheduleEntry entity.
func (_m *ScheduleEntry) QueryUser() *UserQuery {
	return NewScheduleEntryClient(_m.config).QueryUser(_m)
}

// Update returns a builder for updating this ScheduleEntry.
// Note that you need to call ScheduleEntry.Unwrap() before calling this method if this ScheduleEntry
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *ScheduleEntry) Update() *ScheduleEntryUpdateOne {
	return NewScheduleEntryClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the ScheduleEntry entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *ScheduleEntry) Unwrap() *ScheduleEntry {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: ScheduleEntry is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *ScheduleEntry) String() string {
	var builder strings.Builder
	builder.WriteString("ScheduleEntry(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("shift_date=")
	builder.WriteString(_m.ShiftDate.Format(time.ANSIC))
	builder.WriteString(", ")
	if v := _m.ShiftName; v != nil {
		builder.WriteString("shift_name=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.StartTime; v != nil {
		builder.WriteString("start_time=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.EndTime; v != nil {
		builder.WriteString("end_time=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.Hours; v != nil {
		builder.WriteString("hours=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.ClassCode; v != nil {
		builder.WriteString("class_code=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("raw_json=<sensitive>")
	builder.WriteString(", ")
	builder.WriteString("synced_at=")
	builder.WriteString(_m.SyncedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// ScheduleEntries is a parsable slice of ScheduleEntry.
type ScheduleEntries []*ScheduleEntry
