// Code generated by ent, DO NOT EDIT.

package schedulesyncrun

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the schedulesyncrun type in the database.
	Label = "schedule_sync_run"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldStartedAt holds the string denoting the started_at field in the database.
	FieldStartedAt = "started_at"
	// FieldFinishedAt holds the string denoting the finished_at field in the database.
	FieldFinishedAt = "finished_at"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// FieldErrorMessage holds the string denoting the error_message field in the database.
	FieldErrorMessage = "error_message"
	// FieldRangeStart holds the string denoting the range_start field in the database.
	FieldRangeStart = "range_start"
	// FieldRangeEnd holds the string denoting the range_end field in the database.
	FieldRangeEnd = "range_end"
	// FieldEntryCount holds the string denoting the entry_count field in the database.
	FieldEntryCount = "entry_count"
	// FieldMarkedAt holds the string denoting the marked_at field in the database.
	FieldMarkedAt = "marked_at"
	// EdgeUser holds the string denoting the user edge name in mutations.
	EdgeUser = "user"
	// Table holds the table name of the schedulesyncrun in the database.
	Table = "schedule_sync_runs"
	// UserTable is the table that holds the user relation/edge.
	UserTable = "schedule_sync_runs"
	// UserInverseTable is the table name for the User entity.
	// It exists in this package in order to avoid circular dependency with the "user" package.
	UserInverseTable = "users"
	// UserColumn is the table column denoting the user relation/edge.
	UserColumn = "user_sync_runs"
)

// Columns holds all SQL columns for schedulesyncrun fields.
var Columns = []string{
	FieldID,
	FieldStartedAt,
	FieldFinishedAt,
	FieldStatus,
	FieldErrorMessage,
	FieldRangeStart,
	FieldRangeEnd,
	FieldEntryCount,
	FieldMarkedAt,
}

// ForeignKeys holds the SQL foreign-keys that are owned by the "schedule_sync_runs"
// table and are not defined as standalone fields in the schema.
var ForeignKeys = []string{
	"user_sync_runs",
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	for i := range ForeignKeys {
		if column == ForeignKeys[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultStartedAt holds the default value on creation for the "started_at" field.
	DefaultStartedAt func() time.Time
	// DefaultStatus holds the default value on creation for the "status" field.
	DefaultStatus string
	// DefaultEntryCount holds the default value on creation for the "entry_count" field.
	DefaultEntryCount int
)

// OrderOption defines the ordering options for the ScheduleSyncRun queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByStartedAt orders the results by the started_at field.
func ByStartedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStartedAt, opts...).ToFunc()
}

// ByFinishedAt orders the results by the finished_at field.
func ByFinishedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldFinishedAt, opts...).ToFunc()
}

// ByStatus orders the results by the status field.
func ByStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatus, opts...).ToFunc()
}

// ByErrorMessage orders the results by the error_message field.
func ByErrorMessage(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldErrorMessage, opts...).ToFunc()
}

// ByRangeStart orders the results by the range_start field.
func ByRangeStart(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRangeStart, opts...).ToFunc()
}

// ByRangeEnd orders the results by the range_end field.
func ByRangeEnd(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRangeEnd, opts...).ToFunc()
}

// ByEntryCount orders the results by the entry_count field.
func ByEntryCount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEntryCount, opts...).ToFunc()
}

// ByMarkedAt orders the results by the marked_at field.
func ByMarkedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldMarkedAt, opts...).ToFunc()
}

// ByUserField orders the results by user field.
func ByUserField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newUserStep(), sql.OrderByField(field, opts...))
	}
}
func newUserStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(UserInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, UserTable, UserColumn),
	)
}
