// Code generated by ent, DO NOT EDIT.

package schedulesyncrun

import (
	"gaia-calendar/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.ScheduleSyncRun {
	return predicate.ScheduleSyncRun(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.ScheduleSyncRun {
	return predicate.ScheduleSyncRun(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.ScheduleSyncRun {
	return predicate.ScheduleSyncRun(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.ScheduleSyncRun {
	return predicate.ScheduleSyncRun(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.ScheduleSyncRun {
	return predicate.ScheduleSyncRun(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.ScheduleSyncRun {
	return predicate.ScheduleSyncRun(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.ScheduleSyncRun {
	return predicate.ScheduleSyncRun(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.ScheduleSyncRun {
	return predicate.ScheduleSyncRun(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.ScheduleSyncRun {
	return predicate.ScheduleSyncRun(sql.FieldLTE(FieldID, id))
}

// StartedAt applies equality check predicate on the "started_at" field. It's identical to StartedAtEQ.
func StartedAt(v time.Time) predicate.ScheduleSyncRun {
	return predicate.ScheduleSyncRun(sql.FieldEQ(FieldStartedAt, v))
}

// FinishedAt applies equality check predicate on the "finished_at" field. It's identical to FinishedAtEQ.
func FinishedAt(v time.Time) predicate.ScheduleSyncRun {
	return predicate.ScheduleSyncRun(sql.FieldEQ(FieldFinishedAt, v))
}

// Status applies equality check predicate on the "status" field. It's identical to StatusEQ.
func Status(v string) predicate.ScheduleSyncRun {
	return predicate.ScheduleSyncRun(sql.FieldEQ(FieldStatus, v))
}

// ErrorMessage applies equality check predicate on the "error_message" field. It's identical to ErrorMessageEQ.
func ErrorMessage(v string) predicate.ScheduleSyncRun {
	return predicate.ScheduleSyncRun(sql.FieldEQ(FieldErrorMessage, v))
}

// RangeStart applies equality check predicate on the "range_start" field. It's identical to RangeStartEQ.
func RangeStart(v time.Time) predicate.ScheduleSyncRun {
	return predicate.ScheduleSyncRun(sql.FieldEQ(FieldRangeStart, v))
}

// RangeEnd applies equality check predicate on the "range_end" field. It's identical to RangeEndEQ.
func RangeEnd(v time.Time) predicate.ScheduleSyncRun {
	return predicate.ScheduleSyncRun(sql.FieldEQ(FieldRangeEnd, v))
}

// EntryCount applies equality check predicate on the "entry_count" field. It's identical to EntryCountEQ.
func EntryCount(v int) predicate.ScheduleSyncRun {
	return predicate.ScheduleSyncRun(sql.FieldEQ(FieldEntryCount, v))
}

// MarkedAt applies equality check predicate on the "marked_at" field. It's identical to MarkedAtEQ.
func MarkedAt(v time.Time) predicate.ScheduleSyncRun {
	return predicate.ScheduleSyncRun(sql.FieldEQ(FieldMarkedAt, v))
}

// StartedAtEQ applies the EQ predicate on the "started_at" field.
func StartedAtEQ(v time.Time) predicate.ScheduleSyncRun {
	return predicate.ScheduleSyncRun(sql.FieldEQ(FieldStartedAt, v))
}

// StartedAtNEQ applies the NEQ predicate on the "started_at" field.
func StartedAtNEQ(v time.Time) predicate.ScheduleSyncRun {
	return predicate.ScheduleSyncRun(sql.FieldNEQ(FieldStartedAt, v))
}

// StartedAtIn applies the In predicate on the "started_at" field.
func StartedAtIn(vs ...time.Time) predicate.ScheduleSyncRun {
	return predicate.ScheduleSyncRun(sql.FieldIn(FieldStartedAt, vs...))
}

// StartedAtNotIn applies the NotIn predicate on the "started_at" field.
func StartedAtNotIn(vs ...time.Time) predicate.ScheduleSyncRun {
	return predicate.ScheduleSyncRun(sql.FieldNotIn(FieldStartedAt, vs...))
}

// StartedAtGT applies the GT predicate on the "started_at" field.
func StartedAtGT(v time.Time) predicate.ScheduleSyncRun {
	return predicate.ScheduleSyncRun(sql.FieldGT(FieldStartedAt, v))
}

// StartedAtGTE applies the GTE predicate on the "started_at" field.
func StartedAtGTE(v time.Time) predicate.ScheduleSyncRun {
	return predicate.ScheduleSyncRun(sql.FieldGTE(FieldStartedAt, v))
}

// StartedAtLT applies the LT predicate on the "started_at" field.
func StartedAtLT(v time.Time) predicate.ScheduleSyncRun {
	return predicate.ScheduleSyncRun(sql.FieldLT(FieldStartedAt, v))
}

// StartedAtLTE applies the LTE predicate on the "started_at" field.
func StartedAtLTE(v time.Time) predicate.ScheduleSyncRun {
	return predicate.ScheduleSyncRun(sql.FieldLTE(FieldStartedAt, v))
}

// FinishedAtEQ applies the EQ predicate on the "finished_at" field.
func FinishedAtEQ(v time.Time) predicate.ScheduleSyncRun {
	return predicate.ScheduleSyncRun(sql.FieldEQ(FieldFinishedAt, v))
}

// FinishedAtNEQ applies the NEQ predicate on the "finished_at" field.
func FinishedAtNEQ(v time.Time) predicate.ScheduleSyncRun {
	return predicate.ScheduleSyncRun(sql.FieldNEQ(FieldFinishedAt, v))
}

// FinishedAtIn applies the In predicate on the "finished_at" field.
func FinishedAtIn(vs ...time.Time) predicate.ScheduleSyncRun {
	return predicate.ScheduleSyncRun(sql.FieldIn(FieldFinishedAt, vs...))
}

// FinishedAtNotIn applies the NotIn predicate on the "finished_at" field.
func FinishedAtNotIn(vs ...time.Time) predicate.ScheduleSyncRun {
	return predicate.ScheduleSyncRun(sql.FieldNotIn(FieldFinishedAt, vs...))
}

// FinishedAtGT applies the GT predicate on the "finished_at" field.
func FinishedAtGT(v time.Time) predicate.ScheduleSyncRun {
	return predicate.ScheduleSyncRun(sql.FieldGT(FieldFinishedAt, v))
}

// FinishedAtGTE applies the GTE predicate on the "finished_at" field.
func FinishedAtGTE(v time.Time) predicate.ScheduleSyncRun {
	return predicate.ScheduleSyncRun(sql.FieldGTE(FieldFinishedAt, v))
}

// FinishedAtLT applies the LT predicate on the "finished_at" field.
func FinishedAtLT(v time.Time) predicate.ScheduleSyncRun {
	return predicate.ScheduleSyncRun(sql.FieldLT(FieldFinishedAt, v))
}

// FinishedAtLTE applies the LTE predicate on the "finished_at" field.
func FinishedAtLTE(v time.Time) predicate.ScheduleSyncRun {
	return predicate.ScheduleSyncRun(sql.FieldLTE(FieldFinishedAt, v))
}

// FinishedAtIsNil applies the IsNil predicate on the "finished_at" field.
func FinishedAtIsNil() predicate.ScheduleSyncRun {
	return predicate.ScheduleSyncRun(sql.FieldIsNull(FieldFinishedAt))
}

// FinishedAtNotNil applies the NotNil predicate on the "finished_at" field.
func FinishedAtNotNil() predicate.ScheduleSyncRun {
	return predicate.ScheduleSyncRun(sql.FieldNotNull(FieldFinishedAt))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v string) predicate.ScheduleSyncRun {
	return predicate.ScheduleSyncRun(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v string) predicate.ScheduleSyncRun {
	return predicate.ScheduleSyncRun(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...string) predicate.ScheduleSyncRun {
	return predicate.ScheduleSyncRun(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...string) predicate.ScheduleSyncRun {
	return predicate.ScheduleSyncRun(sql.FieldNotIn(FieldStatus, vs...))
}

// StatusGT applies the GT predicate on the "status" field.
func StatusGT(v string) predicate.ScheduleSyncRun {
	return predicate.ScheduleSyncRun(sql.FieldGT(FieldStatus, v))
}

// StatusGTE applies the GTE predicate on the "status" field.
func StatusGTE(v string) predicate.ScheduleSyncRun {
	return predicate.ScheduleSyncRun(sql.FieldGTE(FieldStatus, v))
}

// StatusLT applies the LT predicate on the "status" field.
func StatusLT(v string) predicate.ScheduleSyncRun {
	return predicate.ScheduleSyncRun(sql.FieldLT(FieldStatus, v))
}

// StatusLTE applies the LTE predicate on the "status" field.
func StatusLTE(v string) predicate.ScheduleSyncRun {
	return predicate.ScheduleSyncRun(sql.FieldLTE(FieldStatus, v))
}

// StatusContains applies the Contains predicate on the "status" field.
func StatusContains(v string) predicate.ScheduleSyncRun {
	return predicate.ScheduleSyncRun(sql.FieldContains(FieldStatus, v))
}

// StatusHasPrefix applies the HasPrefix predicate on the "status" field.
func StatusHasPrefix(v string) predicate.ScheduleSyncRun {
	return predicate.ScheduleSyncRun(sql.FieldHasPrefix(FieldStatus, v))
}

// StatusHasSuffix applies the HasSuffix predicate on the "status" field.
func StatusHasSuffix(v string) predicate.ScheduleSyncRun {
	return predicate.ScheduleSyncRun(sql.FieldHasSuffix(FieldStatus, v))
}

// StatusEqualFold applies the EqualFold predicate on the "status" field.
func StatusEqualFold(v string) predicate.ScheduleSyncRun {
	return predicate.ScheduleSyncRun(sql.FieldEqualFold(FieldStatus, v))
}

// StatusContainsFold applies the ContainsFold predicate on the "status" field.
func StatusContainsFold(v string) predicate.ScheduleSyncRun {
	return predicate.ScheduleSyncRun(sql.FieldContainsFold(FieldStatus, v))
}

// ErrorMessageEQ applies the EQ predicate on the "error_message" field.
func ErrorMessageEQ(v string) predicate.ScheduleSyncRun {
	return predicate.ScheduleSyncRun(sql.FieldEQ(FieldErrorMessage, v))
}

// ErrorMessageNEQ applies the NEQ predicate on the "error_message" field.
func ErrorMessageNEQ(v string) predicate.ScheduleSyncRun {
	return predicate.ScheduleSyncRun(sql.FieldNEQ(FieldErrorMessage, v))
}

// ErrorMessageIn applies the In predicate on the "error_message" field.
func ErrorMessageIn(vs ...string) predicate.ScheduleSyncRun {
	return predicate.ScheduleSyncRun(sql.FieldIn(FieldErrorMessage, vs...))
}

// ErrorMessageNotIn applies the NotIn predicate on the "error_message" field.
func ErrorMessageNotIn(vs ...string) predicate.ScheduleSyncRun {
	return predicate.ScheduleSyncRun(sql.FieldNotIn(FieldErrorMessage, vs...))
}

// ErrorMessageGT applies the GT predicate on the "error_message" field.
func ErrorMessageGT(v string) predicate.ScheduleSyncRun {
	return predicate.ScheduleSyncRun(sql.FieldGT(FieldErrorMessage, v))
}

// ErrorMessageGTE applies the GTE predicate on the "error_message" field.
func ErrorMessageGTE(v string) predicate.ScheduleSyncRun {
	return predicate.ScheduleSyncRun(sql.FieldGTE(FieldErrorMessage, v))
}

// ErrorMessageLT applies the LT predicate on the "error_message" field.
func ErrorMessageLT(v string) predicate.ScheduleSyncRun {
	return predicate.ScheduleSyncRun(sql.FieldLT(FieldErrorMessage, v))
}

// ErrorMessageLTE applies the LTE predicate on the "error_message" field.
func ErrorMessageLTE(v string) predicate.ScheduleSyncRun {
	return predicate.ScheduleSyncRun(sql.FieldLTE(FieldErrorMessage, v))
}

// ErrorMessageContains applies the Contains predicate on the "error_message" field.
func ErrorMessageContains(v string) predicate.ScheduleSyncRun {
	return predicate.ScheduleSyncRun(sql.FieldContains(FieldErrorMessage, v))
}

// ErrorMessageHasPrefix applies the HasPrefix predicate on the "error_message" field.
func ErrorMessageHasPrefix(v string) predicate.ScheduleSyncRun {
	return predicate.ScheduleSyncRun(sql.FieldHasPrefix(FieldErrorMessage, v))
}

// ErrorMessageHasSuffix applies the HasSuffix predicate on the "error_message" field.
func ErrorMessageHasSuffix(v string) predicate.ScheduleSyncRun {
	return predicate.ScheduleSyncRun(sql.FieldHasSuffix(FieldErrorMessage, v))
}

// ErrorMessageIsNil applies the IsNil predicate on the "error_message" field.
func ErrorMessageIsNil() predicate.ScheduleSyncRun {
	return predicate.ScheduleSyncRun(sql.FieldIsNull(FieldErrorMessage))
}

// ErrorMessageNotNil applies the NotNil predicate on the "error_message" field.
func ErrorMessageNotNil() predicate.ScheduleSyncRun {
	return predicate.ScheduleSyncRun(sql.FieldNotNull(FieldErrorMessage))
}

// ErrorMessageEqualFold applies the EqualFold predicate on the "error_message" field.
func ErrorMessageEqualFold(v string) predicate.ScheduleSyncRun {
	return predicate.ScheduleSyncRun(sql.FieldEqualFold(FieldErrorMessage, v))
}

// ErrorMessageContainsFold applies the ContainsFold predicate on the "error_message" field.
func ErrorMessageContainsFold(v string) predicate.ScheduleSyncRun {
	return predicate.ScheduleSyncRun(sql.FieldContainsFold(FieldErrorMessage, v))
}

// RangeStartEQ applies the EQ predicate on the "range_start" field.
func RangeStartEQ(v time.Time) predicate.ScheduleSyncRun {
	return predicate.ScheduleSyncRun(sql.FieldEQ(FieldRangeStart, v))
}

// RangeStartNEQ applies the NEQ predicate on the "range_start" field.
func RangeStartNEQ(v time.Time) predicate.ScheduleSyncRun {
	return predicate.ScheduleSyncRun(sql.FieldNEQ(FieldRangeStart, v))
}

// RangeStartIn applies the In predicate on the "range_start" field.
func RangeStartIn(vs ...time.Time) predicate.ScheduleSyncRun {
	return predicate.ScheduleSyncRun(sql.FieldIn(FieldRangeStart, vs...))
}

// RangeStartNotIn applies the NotIn predicate on the "range_start" field.
func RangeStartNotIn(vs ...time.Time) predicate.ScheduleSyncRun {
	return predicate.ScheduleSyncRun(sql.FieldNotIn(FieldRangeStart, vs...))
}

// RangeStartGT applies the GT predicate on the "range_start" field.
func RangeStartGT(v time.Time) predicate.ScheduleSyncRun {
	return predicate.ScheduleSyncRun(sql.FieldGT(FieldRangeStart, v))
}

// RangeStartGTE applies the GTE predicate on the "range_start" field.
func RangeStartGTE(v time.Time) predicate.ScheduleSyncRun {
	return predicate.ScheduleSyncRun(sql.FieldGTE(FieldRangeStart, v))
}

// RangeStartLT applies the LT predicate on the "range_start" field.
func RangeStartLT(v time.Time) predicate.ScheduleSyncRun {
	return predicate.ScheduleSyncRun(sql.FieldLT(FieldRangeStart, v))
}

// RangeStartLTE applies the LTE predicate on the "range_start" field.
func RangeStartLTE(v time.Time) predicate.ScheduleSyncRun {
	return predicate.ScheduleSyncRun(sql.FieldLTE(FieldRangeStart, v))
}

// RangeEndEQ applies the EQ predicate on the "range_end" field.
func RangeEndEQ(v time.Time) predicate.ScheduleSyncRun {
	return predicate.ScheduleSyncRun(sql.FieldEQ(FieldRangeEnd, v))
}

// RangeEndNEQ applies the NEQ predicate on the "range_end" field.
func RangeEndNEQ(v time.Time) predicate.ScheduleSyncRun {
	return predicate.ScheduleSyncRun(sql.FieldNEQ(FieldRangeEnd, v))
}

// RangeEndIn applies the In predicate on the "range_end" field.
func RangeEndIn(vs ...time.Time) predicate.ScheduleSyncRun {
	return predicate.ScheduleSyncRun(sql.FieldIn(FieldRangeEnd, vs...))
}

// RangeEndNotIn applies the NotIn predicate on the "range_end" field.
func RangeEndNotIn(vs ...time.Time) predicate.ScheduleSyncRun {
	return predicate.ScheduleSyncRun(sql.FieldNotIn(FieldRangeEnd, vs...))
}

// RangeEndGT applies the GT predicate on the "range_end" field.
func RangeEndGT(v time.Time) predicate.ScheduleSyncRun {
	return predicate.ScheduleSyncRun(sql.FieldGT(FieldRangeEnd, v))
}

// RangeEndGTE applies the GTE predicate on the "range_end" field.
func RangeEndGTE(v time.Time) predicate.ScheduleSyncRun {
	return predicate.ScheduleSyncRun(sql.FieldGTE(FieldRangeEnd, v))
}

// RangeEndLT applies the LT predicate on the "range_end" field.
func RangeEndLT(v time.Time) predicate.ScheduleSyncRun {
	return predicate.ScheduleSyncRun(sql.FieldLT(FieldRangeEnd, v))
}

// RangeEndLTE applies the LTE predicate on the "range_end" field.
func RangeEndLTE(v time.Time) predicate.ScheduleSyncRun {
	return predicate.ScheduleSyncRun(sql.FieldLTE(FieldRangeEnd, v))
}

// EntryCountEQ applies the EQ predicate on the "entry_count" field.
func EntryCountEQ(v int) predicate.ScheduleSyncRun {
	return predicate.ScheduleSyncRun(sql.FieldEQ(FieldEntryCount, v))
}

// EntryCountNEQ applies the NEQ predicate on the "entry_count" field.
func EntryCountNEQ(v int) predicate.ScheduleSyncRun {
	return predicate.ScheduleSyncRun(sql.FieldNEQ(FieldEntryCount, v))
}

// EntryCountIn applies the In predicate on the "entry_count" field.
func EntryCountIn(vs ...int) predicate.ScheduleSyncRun {
	return predicate.ScheduleSyncRun(sql.FieldIn(FieldEntryCount, vs...))
}

// EntryCountNotIn applies the NotIn predicate on the "entry_count" field.
func EntryCountNotIn(vs ...int) predicate.ScheduleSyncRun {
	return predicate.ScheduleSyncRun(sql.FieldNotIn(FieldEntryCount, vs...))
}

// EntryCountGT applies the GT predicate on the "entry_count" field.
func EntryCountGT(v int) predicate.ScheduleSyncRun {
	return predicate.ScheduleSyncRun(sql.FieldGT(FieldEntryCount, v))
}

// EntryCountGTE applies the GTE predicate on the "entry_count" field.
func EntryCountGTE(v int) predicate.ScheduleSyncRun {
	return predicate.ScheduleSyncRun(sql.FieldGTE(FieldEntryCount, v))
}

// EntryCountLT applies the LT predicate on the "entry_count" field.
func EntryCountLT(v int) predicate.ScheduleSyncRun {
	return predicate.ScheduleSyncRun(sql.FieldLT(FieldEntryCount, v))
}

// EntryCountLTE applies the LTE predicate on the "entry_count" field.
func EntryCountLTE(v int) predicate.ScheduleSyncRun {
	return predicate.ScheduleSyncRun(sql.FieldLTE(FieldEntryCount, v))
}

// MarkedAtEQ applies the EQ predicate on the "marked_at" field.
func MarkedAtEQ(v time.Time) predicate.ScheduleSyncRun {
	return predicate.ScheduleSyncRun(sql.FieldEQ(FieldMarkedAt, v))
}

// MarkedAtNEQ applies the NEQ predicate on the "marked_at" field.
func MarkedAtNEQ(v time.Time) predicate.ScheduleSyncRun {
	return predicate.ScheduleSyncRun(sql.FieldNEQ(FieldMarkedAt, v))
}

// MarkedAtIn applies the In predicate on the "marked_at" field.
func MarkedAtIn(vs ...time.Time) predicate.ScheduleSyncRun {
	return predicate.ScheduleSyncRun(sql.FieldIn(FieldMarkedAt, vs...))
}

// MarkedAtNotIn applies the NotIn predicate on the "marked_at" field.
func MarkedAtNotIn(vs ...time.Time) predicate.ScheduleSyncRun {
	return predicate.ScheduleSyncRun(sql.FieldNotIn(FieldMarkedAt, vs...))
}

// MarkedAtGT applies the GT predicate on the "marked_at" field.
func MarkedAtGT(v time.Time) predicate.ScheduleSyncRun {
	return predicate.ScheduleSyncRun(sql.FieldGT(FieldMarkedAt, v))
}

// MarkedAtGTE applies the GTE predicate on the "marked_at" field.
func MarkedAtGTE(v time.Time) predicate.ScheduleSyncRun {
	return predicate.ScheduleSyncRun(sql.FieldGTE(FieldMarkedAt, v))
}

// MarkedAtLT applies the LT predicate on the "marked_at" field.
func MarkedAtLT(v time.Time) predicate.ScheduleSyncRun {
	return predicate.ScheduleSyncRun(sql.FieldLT(FieldMarkedAt, v))
}

// MarkedAtLTE applies the LTE predicate on the "marked_at" field.
func MarkedAtLTE(v time.Time) predicate.ScheduleSyncRun {
	return predicate.ScheduleSyncRun(sql.FieldLTE(FieldMarkedAt, v))
}

// MarkedAtIsNil applies the IsNil predicate on the "marked_at" field.
func MarkedAtIsNil() predicate.ScheduleSyncRun {
	return predicate.ScheduleSyncRun(sql.FieldIsNull(FieldMarkedAt))
}

// MarkedAtNotNil applies the NotNil predicate on the "marked_at" field.
func MarkedAtNotNil() predicate.ScheduleSyncRun {
	return predicate.ScheduleSyncRun(sql.FieldNotNull(FieldMarkedAt))
}

// HasUser applies the HasEdge predicate on the "user" edge.
func HasUser() predicate.ScheduleSyncRun {
	return predicate.ScheduleSyncRun(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, UserTable, UserColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasUserWith applies the HasEdge predicate on the "user" edge with a given conditions (other predicates).
func HasUserWith(preds ...predicate.User) predicate.ScheduleSyncRun {
	return predicate.ScheduleSyncRun(func(s *sql.Selector) {
		step := newUserStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.ScheduleSyncRun) predicate.ScheduleSyncRun {
	return predicate.ScheduleSyncRun(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.ScheduleSyncRun) predicate.ScheduleSyncRun {
	return predicate.ScheduleSyncRun(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.ScheduleSyncRun) predicate.ScheduleSyncRun {
	return predicate.ScheduleSyncRun(sql.NotPredicates(p))
}
